(function(){
  var extra = [{"id": "devtools-coverage-temukan-css-tak-terpakai", "langs": {"id": {"title": "Pakai Coverage DevTools untuk CSS yang Tak Terpakai", "desc": "Panel Coverage menandai byte CSS dan JS yang tidak pernah dieksekusi pada alur yang Anda buka.", "content": "<p class=\"mb-4\">Di Chrome DevTools buka More tools, lalu Coverage. Mulai rekaman, lalu jalankan alur utama di editor.clincoo.buzz: buka halaman, isi form, simpan.</p><p class=\"mb-4\">Baris merah adalah byte yang tidak terpakai pada rekaman itu. Jangan hapus semuanya: halaman lain di app.clincoo.buzz mungkin masih memakai aturan itu.</p><p class=\"mb-4\">Catat selektor dengan porsi merah besar. Cek apakah itu sisa template, reset pihak ketiga, atau aturan yang hanya hidup di mode cetak.</p><p class=\"mb-4\">Ulangi rekaman di lebar ponsel. Aturan desktop yang hijau di laptop bisa merah di viewport sempit, atau sebaliknya.</p><p class=\"mb-4\">Minta AI menjelaskan selektor yang merah, bukan menghapus berkas CSS global. Tempel cuplikan kecil dan sebut halaman yang diuji.</p><p class=\"mb-4\">Simpan tangkapan di catatan rilis blog.clincoo.buzz supaya penghapusan berikutnya ada bukti, bukan tebakan.</p>", "source": "Chrome Developers", "sourceUrl": "https://developer.chrome.com/docs/devtools/coverage", "sourceSnippet": "Coverage shows unused CSS and JS", "source2": "Chrome DevTools: Coverage", "source3": "Clincoo Editor"}, "en": {"title": "Use DevTools Coverage to Find Unused CSS", "desc": "The Coverage panel marks CSS and JS bytes that never run on the flow you opened.", "content": "<p class=\"mb-4\">In Chrome DevTools open More tools, then Coverage. Start recording, then run the main flow on editor.clincoo.buzz: open a page, fill a form, save.</p><p class=\"mb-4\">Red lines are bytes unused in that recording. Do not delete all of them: another page on app.clincoo.buzz may still use the rule.</p><p class=\"mb-4\">Note selectors with a large red share. Check whether they are leftover template CSS, a third-party reset, or rules that only live in print mode.</p><p class=\"mb-4\">Repeat the recording at phone width. A desktop rule that is green on a laptop can be red on a narrow viewport, or the reverse.</p><p class=\"mb-4\">Ask AI to explain the red selectors, not to delete the global stylesheet. Paste a small snippet and name the page you tested.</p><p class=\"mb-4\">Save the capture in the blog.clincoo.buzz release note so the next deletion has evidence, not a guess.</p>", "source": "Chrome Developers", "sourceUrl": "https://developer.chrome.com/docs/devtools/coverage", "sourceSnippet": "Coverage shows unused CSS and JS", "source2": "Chrome DevTools: Coverage", "source3": "Clincoo Editor"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['devtools']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['devtools'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
