// Clincoo Blog — artikel error tambahan 2026-10-02
(function(){
  var extra = [{id:"error-resize-observer-loop",langs:{id:{title:"Baca ResizeObserver Loop Limit sebelum Menganggap Layout Rusak",desc:"Peringatan loop limit sering muncul saat callback mengubah ukuran yang sedang diamati. Bedakan peringatan browser dari bug Clincoo.",content:"<p class=\"mb-4\">Konsol di pratinjau app.clincoo.buzz kadang menampilkan ResizeObserver loop completed with undelivered notifications. Halaman tetap bisa dipakai.</p><p class=\"mb-4\">Cek callback observer. Jika ia menulis style yang mengubah ukuran elemen yang sama, browser menunda notifikasi berikutnya.</p><p class=\"mb-4\">Pindahkan penulisan layout ke requestAnimationFrame, atau amati elemen induk yang tidak diubah callback.</p><p class=\"mb-4\">Jangan minta AI menghapus semua ResizeObserver. Tempel cuplikan callback dan tanyakan baris yang mengubah ukuran.</p><p class=\"mb-4\">Jika layout di blog.clincoo.buzz stabil dan tidak ada loop visual, catat peringatan sebagai derau. Perbaiki hanya jika tinggi kartu bergetar.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Editor resmi Clincoo",source2:"Clincoo App",source3:"Clincoo Blog"},en:{title:"Read ResizeObserver Loop Limit before Treating the Layout as Broken",desc:"The loop limit warning often appears when a callback changes the size being observed. Separate the browser warning from a Clincoo bug.",content:"<p class=\"mb-4\">The console in the app.clincoo.buzz preview sometimes shows ResizeObserver loop completed with undelivered notifications. The page can still be used.</p><p class=\"mb-4\">Check the observer callback. If it writes a style that changes the size of the same element, the browser defers the next notification.</p><p class=\"mb-4\">Move the layout write to requestAnimationFrame, or observe a parent that the callback does not change.</p><p class=\"mb-4\">Do not ask the AI to delete every ResizeObserver. Paste the callback and ask which line changes the size.</p><p class=\"mb-4\">If the layout on blog.clincoo.buzz is stable and there is no visual loop, record the warning as noise. Fix it only if card height jitters.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Official Clincoo editor",source2:"Clincoo App",source3:"Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["error"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["error"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
