// Clincoo Blog — artikel seo extra2 2026-10-01
(function(){
  var extra = [
    {id:'seo-meta-robots-index-follow',langs:{id:{title:'Setel Meta Robots Index Follow pada Halaman Publik Clincoo',desc:'Halaman publik yang tertinggal noindex tidak muncul di hasil cari. Periksa meta robots sebelum rilis.',content:'<p class="mb-4">Di editor.clincoo.buzz, template draf sering membawa noindex ke halaman yang sudah dipublikasikan.</p><p class="mb-4">Buka View Source pada URL publik. Pastikan meta robots berisi index, follow, bukan noindex.</p><p class="mb-4">Jangan minta AI menghapus semua meta. Minta hanya ganti nilai robots pada rute publik app.clincoo.buzz.</p><p class="mb-4">Catat pengecualian pratinjau di blog.clincoo.buzz agar draf tetap noindex.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Set Meta Robots to Index Follow on Public Clincoo Pages',desc:'A public page that keeps noindex never shows in search. Check the robots meta before release.',content:'<p class="mb-4">On editor.clincoo.buzz, a draft template often carries noindex onto a page that is already public.</p><p class="mb-4">View Source on the public URL. Confirm the robots meta is index, follow, not noindex.</p><p class="mb-4">Do not ask AI to delete every meta tag. Ask only to change robots on public app.clincoo.buzz routes.</p><p class="mb-4">Document the preview exception on blog.clincoo.buzz so drafts stay noindex.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'seo-cek-status-200-sebelum-indeks',langs:{id:{title:'Cek Status 200 sebelum Mengirim URL Clincoo ke Indeks',desc:'URL 404 atau 302 berantai membuang crawl budget. Pastikan dokumen final menjawab 200.',content:'<p class="mb-4">Di Network tab pratinjau editor.clincoo.buzz, dokumen utama harus 200, bukan 404 setelah slug diganti.</p><p class="mb-4">Jika ada redirect, pastikan satu hop 301 ke URL kanonis, lalu 200.</p><p class="mb-4">Tempel status line ke AI, bukan seluruh HAR. Minta satu perbaikan rute.</p><p class="mb-4">Ulangi di app.clincoo.buzz dan tautkan checklist status di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Check for HTTP 200 before Sending a Clincoo URL to the Index',desc:'A 404 or a redirect chain wastes crawl budget. Confirm the final document returns 200.',content:'<p class="mb-4">In the Network tab of the editor.clincoo.buzz preview, the main document must be 200, not 404 after a slug change.</p><p class="mb-4">If a redirect exists, keep one 301 hop to the canonical URL, then 200.</p><p class="mb-4">Paste the status line to AI, not the whole HAR. Ask for one route fix.</p><p class="mb-4">Repeat on app.clincoo.buzz and link the status checklist on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'seo-hreflang-id-en-pasangan',langs:{id:{title:'Pasangkan hreflang id dan en pada Artikel Clincoo',desc:'Versi bahasa tanpa tautan balik membuat mesin cari memilih URL yang salah.',content:'<p class="mb-4">Setiap artikel bilingual di editor.clincoo.buzz butuh rel alternate hreflang id dan en yang saling menunjuk.</p><p class="mb-4">Tambah x-default ke versi yang paling sering dibuka. Jangan arahkan ke 404.</p><p class="mb-4">Minta AI dua baris link, bukan rewrite head. Cek View Source kedua file.</p><p class="mb-4">Pratinjau pasangan di app.clincoo.buzz. Contoh resmi ada di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Pair hreflang id and en on Clincoo Articles',desc:'Language versions without reciprocal links make search engines pick the wrong URL.',content:'<p class="mb-4">Every bilingual article on editor.clincoo.buzz needs rel alternate hreflang id and en that point at each other.</p><p class="mb-4">Add x-default to the version visitors open most. Do not point it at a 404.</p><p class="mb-4">Ask AI for two link tags, not a head rewrite. Check View Source on both files.</p><p class="mb-4">Preview the pair on app.clincoo.buzz. Official examples live on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'seo-og-image-rasio-aman',langs:{id:{title:'Pakai OG Image Rasio Aman saat Membagikan Halaman Clincoo',desc:'Gambar 1:1 terpotong di kartu sosial. Siapkan aset 1200x630 khusus bagikan.',content:'<p class="mb-4">Logo kotak di editor.clincoo.buzz terlihat kecil atau terpotong di pratinjau Facebook dan X.</p><p class="mb-4">Unggah PNG atau JPG 1200x630. Isi og:image dengan URL absolut https.</p><p class="mb-4">Jangan minta AI men-generate foto stok. Minta hanya tag og:image dan ukuran.</p><p class="mb-4">Uji debugger sosial, lalu simpan aset di app.clincoo.buzz dan catatan di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Use a Safe OG Image Ratio When Sharing a Clincoo Page',desc:'A 1:1 image gets cropped on social cards. Prepare a 1200x630 asset for sharing.',content:'<p class="mb-4">A square logo on editor.clincoo.buzz looks tiny or cropped in Facebook and X previews.</p><p class="mb-4">Upload a 1200x630 PNG or JPG. Set og:image to an absolute https URL.</p><p class="mb-4">Do not ask AI for stock photos. Ask only for the og:image tag and dimensions.</p><p class="mb-4">Test a social debugger, then store the asset on app.clincoo.buzz and a note on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'seo-redirect-301-bukan-javascript',langs:{id:{title:'Alihkan URL Lama Clincoo dengan 301, Bukan JavaScript',desc:'Redirect lewat location.href terlambat untuk crawler. Pakai 301 di server atau meta refresh hanya sebagai cadangan.',content:'<p class="mb-4">Saat slug berubah di editor.clincoo.buzz, crawler masih meminta URL lama. JS redirect sering diabaikan.</p><p class="mb-4">Set 301 dari path lama ke kanonis. Pastikan rantai berhenti di 200.</p><p class="mb-4">Tempel daftar slug lama ke AI dan minta aturan redirect, bukan skrip window.location.</p><p class="mb-4">Uji curl -I di app.clincoo.buzz. Dokumentasikan map slug di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Redirect Old Clincoo URLs with 301, Not JavaScript',desc:'A location.href redirect is too late for crawlers. Use a server 301; keep meta refresh only as backup.',content:'<p class="mb-4">When a slug changes on editor.clincoo.buzz, crawlers still request the old URL. JS redirects are often ignored.</p><p class="mb-4">Set a 301 from the old path to the canonical. Make sure the chain ends at 200.</p><p class="mb-4">Paste the old slug list to AI and ask for redirect rules, not a window.location script.</p><p class="mb-4">Test with curl -I on app.clincoo.buzz. Document the slug map on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['seo']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['seo'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
