// Clincoo Blog — artikel schema tambahan 2026-10-02
(function(){
  var extra = [{"id": "schema-faqpage-hanya-jika-terlihat", "langs": {"id": {"title": "Pakai FAQPage Schema hanya jika FAQ Terlihat di Clincoo", "desc": "JSON-LD FAQ yang tidak ada di halaman bisa ditolak. Tulis tanya-jawab yang sama di HTML dan di schema.", "content": "<p class=\"mb-4\">Beberapa template Clincoo menempel FAQPage agar cuplikan kaya muncul. Jika pertanyaannya tidak terlihat di halaman, markup itu menyesatkan.</p><p class=\"mb-4\">Salin teks pertanyaan dan jawaban dari blok yang benar-benar dirender. Jangan menulis FAQ hanya di script JSON-LD.</p><p class=\"mb-4\">Satu halaman, satu jenis utama. Jika sudah ada Article, FAQ hanya tambahan untuk bagian tanya-jawab, bukan pengganti judul artikel.</p><p class=\"mb-4\">Uji di pratinjau app.clincoo.buzz: lihat sumber, pastikan jumlah Question sama dengan jumlah item di halaman.</p><p class=\"mb-4\">Minta AI menyamakan teks HTML dan JSON-LD, bukan menambah pertanyaan baru yang tidak ingin Anda tampilkan.</p>", "source": "Clincoo Editor", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Clincoo Editor", "source2": "Clincoo Blog", "source3": "Google Search Central"}, "en": {"title": "Use FAQPage Schema Only When the FAQ Is Visible in Clincoo", "desc": "FAQ JSON-LD that is not on the page can be rejected. Write the same questions in HTML and in the schema.", "content": "<p class=\"mb-4\">Some Clincoo templates paste FAQPage so a rich result might appear. If the questions are not visible on the page, that markup is misleading.</p><p class=\"mb-4\">Copy question and answer text from the block that actually renders. Do not write an FAQ only inside the JSON-LD script.</p><p class=\"mb-4\">One page, one primary type. If Article is already there, FAQ is only an addition for the Q&A section, not a replacement for the article title.</p><p class=\"mb-4\">Test in the app.clincoo.buzz preview: view source and confirm the Question count matches the items on the page.</p><p class=\"mb-4\">Ask AI to align the HTML text and the JSON-LD, not to invent questions you do not want to show.</p>", "source": "Clincoo Editor", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Clincoo Editor", "source2": "Clincoo Blog", "source3": "Google Search Central"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["schema"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["schema"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
