// Clincoo Blog shortcut extra 2026-09-30
(function(){
  var extra = [
    {id:'shortcut-ctrl-vs-meta',langs:{id:{title:'Bedakan Ctrl dan Meta pada Shortcut Clincoo di Windows dan Mac',desc:'Pintasan yang hanya cek ctrlKey gagal di Mac. Pakai metaKey untuk Command.',content:'<p class="mb-4">Di editor.clincoo.buzz, Ctrl+S menyimpan di Windows. Di Mac pengguna menekan Command+S dan tidak terjadi apa-apa.</p><p class="mb-4">Deteksi platform atau terima ctrlKey atau metaKey untuk aksi simpan. Jangan tabrak Command+T milik browser.</p><p class="mb-4">Kirim listener keydown ke AI. Minta cabang Windows/Mac, bukan keymap baru.</p><p class="mb-4">Uji di app.clincoo.buzz pada kedua OS. Catat kombinasi di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Split Ctrl and Meta for Clincoo Shortcuts on Windows and Mac',desc:'A shortcut that only checks ctrlKey fails on Mac. Use metaKey for Command.',content:'<p class="mb-4">On editor.clincoo.buzz, Ctrl+S saves on Windows. On Mac, Command+S does nothing.</p><p class="mb-4">Detect the platform or accept ctrlKey or metaKey for save. Do not override Command+T.</p><p class="mb-4">Send the keydown listener to AI. Ask for a Windows/Mac branch, not a new keymap.</p><p class="mb-4">Test on app.clincoo.buzz on both OS. Document the combo on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'shortcut-escape-lepas-fokus',langs:{id:{title:'Lepaskan Fokus Editor Clincoo dengan Escape tanpa Menutup Tab',desc:'Escape yang men-close modal dan blur sekaligus membuat pengguna tersesat. Urutkan satu aksi per tekan.',content:'<p class="mb-4">Di editor.clincoo.buzz, Escape menutup panel lalu blur ke body. Pengguna tidak tahu ke mana kursor pergi.</p><p class="mb-4">Jika overlay terbuka, Escape hanya menutup overlay. Jika tidak, blur elemen aktif.</p><p class="mb-4">Jangan panggil window.close. Tempel urutan handler ke AI.</p><p class="mb-4">Uji di app.clincoo.buzz: buka panel, Escape sekali, lalu lagi. Tulis urutan di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Release Clincoo Editor Focus with Escape without Closing the Tab',desc:'Escape that both closes a modal and blurs focus leaves users lost. One action per press.',content:'<p class="mb-4">On editor.clincoo.buzz, Escape closes a panel then blurs to body. Users lose the caret.</p><p class="mb-4">If an overlay is open, Escape only closes it. Otherwise blur the active element.</p><p class="mb-4">Do not call window.close. Paste the handler order to AI.</p><p class="mb-4">Test on app.clincoo.buzz: open a panel, Escape once, then again. Write the order on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['shortcut']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['shortcut'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
