// Clincoo Blog — artikel clipboard tambahan 2026-09-30
(function(){
  var extra = [
    {"id": "clipboard-izin-sebelum-tulis", "langs": {"id": {"title": "Minta Izin Clipboard Sebelum Menulis Teks Clincoo", "desc": "navigator.clipboard.writeText gagal diam-diam jika halaman bukan HTTPS atau belum fokus. Cek izin dulu.", "content": "<p class=\"mb-4\">Tombol salin di editor.clincoo.buzz sering gagal di pratinjau HTTP. API clipboard hanya andal di konteks aman dan saat tab fokus.</p><p class=\"mb-4\">Bungkus writeText dalam try/catch. Jika rejected, tampilkan fallback: pilih teks di input lalu document.execCommand(\"copy\") sekali.</p><p class=\"mb-4\">Jangan panggil clipboard saat halaman baru dimuat. Panggil hanya dari klik pengguna agar browser tidak memblokir.</p><p class=\"mb-4\">Tempel error NotAllowedError ke AI. Jangan minta AI menulis polyfill besar sebelum Anda cek HTTPS di app.clincoo.buzz.</p><p class=\"mb-4\">Clincoo di blog.clincoo.buzz tetap memakai tombol salin yang sama; yang berubah hanya penanganan izin.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Ask for Clipboard Permission Before Writing Clincoo Text", "desc": "navigator.clipboard.writeText fails quietly if the page is not HTTPS or not focused. Check permission first.", "content": "<p class=\"mb-4\">The copy button on editor.clincoo.buzz often fails on HTTP preview. The clipboard API is reliable only in a secure context while the tab is focused.</p><p class=\"mb-4\">Wrap writeText in try/catch. On reject, show a fallback: select text in an input and call document.execCommand(\"copy\") once.</p><p class=\"mb-4\">Do not call clipboard on page load. Call it only from a user click so the browser does not block it.</p><p class=\"mb-4\">Paste the NotAllowedError to AI. Do not ask AI for a large polyfill before you check HTTPS on app.clincoo.buzz.</p><p class=\"mb-4\">Clincoo on blog.clincoo.buzz keeps the same copy button; only permission handling changes.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}},
    {"id": "clipboard-baca-paste-dari-event", "langs": {"id": {"title": "Baca Teks Paste dari Event, Bukan Hanya Clipboard API Clincoo", "desc": "Membaca clipboard tanpa event paste sering ditolak. Ambil data dari event.clipboardData saat pengguna menempel.", "content": "<p class=\"mb-4\">Di editor.clincoo.buzz, tombol Tempel yang memanggil readText gagal di Safari meski HTTPS aktif.</p><p class=\"mb-4\">Pasang listener paste pada area editor. Baca event.clipboardData.getData('text/plain') lalu preventDefault hanya jika Anda menangani format sendiri.</p><p class=\"mb-4\">Jangan baca clipboard saat halaman load. Browser menolak tanpa gestur. Tempel error ke AI, bukan seluruh modul editor.</p><p class=\"mb-4\">Uji di app.clincoo.buzz dengan Ctrl+V dan menu klik kanan. Catat hasil di blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Read Pasted Text from the Event, Not Only the Clincoo Clipboard API", "desc": "Reading the clipboard without a paste event is often blocked. Take data from event.clipboardData when the user pastes.", "content": "<p class=\"mb-4\">On editor.clincoo.buzz, a Paste button that calls readText fails in Safari even on HTTPS.</p><p class=\"mb-4\">Attach a paste listener on the editor area. Read event.clipboardData.getData('text/plain') and preventDefault only if you handle the format yourself.</p><p class=\"mb-4\">Do not read the clipboard on page load. The browser rejects it without a gesture. Paste the error to AI, not the whole editor module.</p><p class=\"mb-4\">Test on app.clincoo.buzz with Ctrl+V and the context menu. Record the result on blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}
  ,
    {"id": "clipboard-salin-pesan-error-utuh", "langs": {"id": {"title": "Salin Pesan Error Utuh, Bukan Potongan", "desc": "Cuplikan error yang terpotong membuat AI menebak stack. Salin pesan lengkap dari konsol sebelum meminta bantuan.", "content": "<p class=\"mb-4\">Di editor.clincoo.buzz, tombol salin error sebaiknya memakai navigator.clipboard.writeText pada string utuh, bukan innerText kartu yang terpotong CSS.</p><p class=\"mb-4\">Sertakan nama file, nomor baris, dan pesan. Jangan ikut token, cookie, atau URL yang berisi kunci.</p><p class=\"mb-4\">writeText butuh gestur pengguna dan konteks aman. Jika gagal, jatuhkan ke seleksi teks yang sudah ada, jangan diam saja.</p><p class=\"mb-4\">Jika AI hanya menerima screenshot, minta ulang dalam teks. Gambar tidak menyalin stack dengan andal.</p><p class=\"mb-4\">Uji tombol di pratinjau app.clincoo.buzz, lalu tempel ke catatan sebelum dibagikan di blog.clincoo.buzz.</p>", "source": "MDN: Clipboard", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/API/Clipboard", "sourceSnippet": "developer.mozilla.org", "source2": "MDN: Clipboard.writeText", "source3": "MDN: console.error"}, "en": {"title": "Copy the Full Error Message, Not a Fragment", "desc": "A clipped error makes the AI guess the stack. Copy the complete console message before asking for help.", "content": "<p class=\"mb-4\">On editor.clincoo.buzz, a copy-error button should call navigator.clipboard.writeText with the full string, not the CSS-truncated innerText of a card.</p><p class=\"mb-4\">Include the file name, line number, and message. Do not include tokens, cookies, or URLs that carry keys.</p><p class=\"mb-4\">writeText needs a user gesture and a secure context. If it fails, fall back to an existing text selection instead of failing silently.</p><p class=\"mb-4\">If AI only receives a screenshot, ask again in text. Images do not copy a stack reliably.</p><p class=\"mb-4\">Test the button in the app.clincoo.buzz preview, then paste into a note before sharing on blog.clincoo.buzz.</p>", "source": "MDN: Clipboard", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/API/Clipboard", "sourceSnippet": "developer.mozilla.org", "source2": "MDN: Clipboard.writeText", "source3": "MDN: console.error"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["clipboard"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["clipboard"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
