// Clincoo Blog timezone extra 2026-09-30
(function(){
  var extra = [
    {id:'timezone-simpan-utc-tampil-lokal',langs:{id:{title:'Simpan Waktu UTC, Tampilkan Zona Lokal di Halaman Clincoo',desc:'Timestamp tanpa zona membuat jadwal Clincoo bergeser saat klien buka dari negara lain. Simpan UTC, format di perangkat.',content:'<p class="mb-4">Di editor.clincoo.buzz, tanggal yang ditulis sebagai string lokal terlihat benar di laptop Anda dan salah di app.clincoo.buzz milik klien.</p><p class="mb-4">Simpan ISO 8601 dengan Z atau offset. Render lewat Intl.DateTimeFormat dengan timeZone yang dipilih pengguna.</p><p class="mb-4">Jangan andalkan new Date(stringTanpaZona). Tempel satu nilai UTC bermasalah ke AI, bukan minta rewrite kalender.</p><p class="mb-4">Uji di blog.clincoo.buzz dengan zona Asia/Jakarta dan zona lain sebelum rilis.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Store UTC, Display the Local Zone on a Clincoo Page',desc:'A timestamp without a zone shifts Clincoo schedules when a client opens the page from another country. Store UTC, format on the device.',content:'<p class="mb-4">On editor.clincoo.buzz, a local date string looks correct on your laptop and wrong on a client app.clincoo.buzz session.</p><p class="mb-4">Store ISO 8601 with Z or an offset. Render with Intl.DateTimeFormat and the user timeZone.</p><p class="mb-4">Do not rely on new Date(stringWithoutZone). Paste one bad UTC value to AI instead of asking for a calendar rewrite.</p><p class="mb-4">Test on blog.clincoo.buzz with Asia/Jakarta and another zone before release.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'timezone-iana-bukan-gmt-plus',langs:{id:{title:'Pakai Nama Zona IANA, Bukan Label GMT+7 di Clincoo',desc:'GMT+7 tidak mengikuti DST dan nama kota. IANA seperti Asia/Jakarta lebih stabil untuk jadwal Clincoo.',content:'<p class="mb-4">Label GMT+7 di form Clincoo membingungkan pengguna di zona yang berubah musim panas.</p><p class="mb-4">Simpan Asia/Jakarta, Asia/Makassar, atau Europe/London. Tampilkan nama kota, bukan angka offset mentah.</p><p class="mb-4">Tempel daftar zona yang dipakai halaman ke AI. Jangan minta konversi offset manual.</p><p class="mb-4">Cek pratinjau di editor.clincoo.buzz lalu app.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Use IANA Zone Names, Not GMT+7 Labels in Clincoo',desc:'GMT+7 ignores DST and city names. IANA IDs such as Asia/Jakarta stay stable for Clincoo schedules.',content:'<p class="mb-4">A GMT+7 label on a Clincoo form confuses users in zones that change for daylight saving.</p><p class="mb-4">Store Asia/Jakarta, Asia/Makassar, or Europe/London. Show a city name, not a raw offset number.</p><p class="mb-4">Paste the zone list the page uses to AI. Do not ask for manual offset math.</p><p class="mb-4">Check preview on editor.clincoo.buzz then app.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'timezone-format-tanggal-dengan-intl',langs:{id:{title:'Format Tanggal Clincoo lewat Intl, Bukan String Manual',desc:'Gabungan getDate dan slash mudah tertukar DD/MM. Intl mengikuti locale halaman Clincoo.',content:'<p class="mb-4">Di editor.clincoo.buzz, 03/04 dibaca Maret oleh satu pembaca dan April oleh yang lain.</p><p class="mb-4">Pakai Intl.DateTimeFormat(locale, { dateStyle: "medium", timeZone }). Locale id-ID dan en-US tidak boleh dicampur diam-diam.</p><p class="mb-4">Kirim opsi format ke AI. Jangan minta template tanggal dari potongan string.</p><p class="mb-4">Samakan output di app.clincoo.buzz dan blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Format Clincoo Dates with Intl, Not Hand-Built Strings',desc:'getDate plus slashes swaps DD/MM easily. Intl follows the Clincoo page locale.',content:'<p class="mb-4">On editor.clincoo.buzz, 03/04 reads as March for one reader and April for another.</p><p class="mb-4">Use Intl.DateTimeFormat(locale, { dateStyle: "medium", timeZone }). Do not silently mix id-ID and en-US.</p><p class="mb-4">Send the format options to AI. Do not ask for a date template from string slices.</p><p class="mb-4">Match output on app.clincoo.buzz and blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'timezone-hindari-new-date-parse-ambigu',langs:{id:{title:'Hindari new Date pada String Ambigu di Proyek Clincoo',desc:'Parser Date berbeda antar browser. String YYYY-MM-DD tanpa waktu bisa digeser ke hari sebelumnya.',content:'<p class="mb-4">Halaman jadwal Clincoo menampilkan kemarin setelah di-parse di zona UTC.</p><p class="mb-4">Pakai Date.UTC atau temporal yang eksplisit. Jika hanya tanggal kalender, simpan YYYY-MM-DD sebagai tanggal, bukan midnight lokal.</p><p class="mb-4">Tempel string yang pecah plus zona perangkat ke AI. Jangan minta polyfill Date besar.</p><p class="mb-4">Repro di editor.clincoo.buzz dengan zona diubah di OS.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Avoid new Date on Ambiguous Strings in a Clincoo Project',desc:'Date parsers differ across browsers. A YYYY-MM-DD string without time can shift to the previous day.',content:'<p class="mb-4">A Clincoo schedule page shows yesterday after parsing in a UTC zone.</p><p class="mb-4">Use Date.UTC or an explicit temporal value. If you only need a calendar day, store YYYY-MM-DD as a date, not local midnight.</p><p class="mb-4">Paste the broken string plus the device zone to AI. Do not ask for a large Date polyfill.</p><p class="mb-4">Reproduce on editor.clincoo.buzz with the OS zone changed.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'timezone-uji-wib-dan-zona-lain',langs:{id:{title:'Uji Jadwal Clincoo di WIB dan Satu Zona Lain',desc:'Lolos di Asia/Jakarta belum berarti lolos di New York. Tambah satu zona uji pada checklist rilis.',content:'<p class="mb-4">Tim Clincoo sering hanya menguji laptop WIB. Bug muncul saat webinar dibuka dari UTC-5.</p><p class="mb-4">Ubah zona OS atau pakai override di DevTools. Bandingkan label jam di editor.clincoo.buzz dan app.clincoo.buzz.</p><p class="mb-4">Catat dua hasil, tempel ke AI jika selisih tidak 7 jam tetap.</p><p class="mb-4">Tautkan checklist ini di blog.clincoo.buzz agar rilis berikutnya tidak melewatkannya.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Test Clincoo Schedules in WIB and One Other Zone',desc:'Passing in Asia/Jakarta does not mean it passes in New York. Add one extra zone to the release checklist.',content:'<p class="mb-4">Clincoo teams often test only a WIB laptop. Bugs show up when a webinar opens from UTC-5.</p><p class="mb-4">Change the OS zone or use a DevTools override. Compare clock labels on editor.clincoo.buzz and app.clincoo.buzz.</p><p class="mb-4">Record both results and paste them to AI if the gap is not a steady 7 hours.</p><p class="mb-4">Link this checklist on blog.clincoo.buzz so the next release does not skip it.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['timezone']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['timezone'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
