// Clincoo Blog featureflag extra 2026-09-30
(function(){
  var extra = [
    {id:'featureflag-nama-flag-jelas',langs:{id:{title:'Beri Nama Feature Flag Clincoo yang Menjelaskan Perilaku',desc:'Flag bernama test1 tidak bisa diaudit. Pakai kata kerja plus fitur: enable-preview-share.',content:'<p class="mb-4">Flag acak di app.clincoo.buzz membuat rekan takut menghapus cabang yang sudah mati.</p><p class="mb-4">Tulis nama yang menyebut fitur dan default. Hindari inisial dan nomor eksperimen.</p><p class="mb-4">Dokumentasikan pemilik flag di README halaman. Tanpa pemilik, flag hidup selamanya.</p><p class="mb-4">Tempel daftar flag ke AI dan minta rename yang konsisten. Jangan minta hapus massal tanpa uji.</p><p class="mb-4">Uji kedua nilai di editor.clincoo.buzz. Catat nama final di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Name Clincoo Feature Flags After the Behavior',desc:'A flag called test1 cannot be audited. Use a verb plus the feature: enable-preview-share.',content:'<p class="mb-4">Random flags on app.clincoo.buzz make teammates afraid to delete a dead branch.</p><p class="mb-4">Write a name that states the feature and the default. Avoid initials and experiment numbers.</p><p class="mb-4">Document the flag owner in the page README. Without an owner the flag lives forever.</p><p class="mb-4">Paste the flag list to AI and ask for consistent renames. Do not mass-delete without tests.</p><p class="mb-4">Test both values on editor.clincoo.buzz. Record the final name on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'featureflag-uji-kedua-cabang',langs:{id:{title:'Uji Kedua Cabang Feature Flag Clincoo sebelum Rilis',desc:'Hanya menguji flag menyala meninggalkan regresi saat flag mati. Kedua jalur harus render.',content:'<p class="mb-4">Pratinjau editor.clincoo.buzz sering hanya dijalankan dengan flag on. Pengguna lama mendapat layout pecah.</p><p class="mb-4">Buat checklist: on, off, dan nilai undefined. Undefined harus jatuh ke default aman.</p><p class="mb-4">Jangan biarkan cabang off mengeksekusi fetch rahasia. Guard di awal fungsi.</p><p class="mb-4">Minta AI menulis tabel uji dua baris. Jangan minta refactor besar di commit yang sama.</p><p class="mb-4">Simpan hasil uji di catatan rilis app.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Test Both Clincoo Feature-Flag Branches before Release',desc:'Testing only the on path leaves a regression when the flag is off. Both paths must render.',content:'<p class="mb-4">Previews on editor.clincoo.buzz often run only with the flag on. Older users get a broken layout.</p><p class="mb-4">Make a checklist: on, off, and undefined. Undefined must fall back to a safe default.</p><p class="mb-4">Do not let the off branch fire a secret fetch. Guard at the start of the function.</p><p class="mb-4">Ask AI for a two-row test table. Do not request a large refactor in the same commit.</p><p class="mb-4">Store the test result in the app.clincoo.buzz release note.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'featureflag-hapus-flag-mati',langs:{id:{title:'Hapus Feature Flag Clincoo yang Sudah Default Permanen',desc:'Flag yang selalu true adalah utang kode. Jadwalkan penghapusan setelah satu rilis stabil.',content:'<p class="mb-4">Cabang if (flag) menumpuk di bundle halaman Clincoo dan membingungkan AI saat debug.</p><p class="mb-4">Setelah fitur stabil di produksi selama satu siklus, hapus flag dan cabang mati.</p><p class="mb-4">Cari semua pemakaian nama flag sebelum commit. Satu sisa if merusak tree-shake.</p><p class="mb-4">Tempel grep hasil ke AI. Minta diff penghapusan saja, bukan rewrite modul.</p><p class="mb-4">Umumkan di blog.clincoo.buzz agar editor.clincoo.buzz dan app.clincoo.buzz selaras.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Remove Clincoo Feature Flags that Are Permanently Default',desc:'A flag that is always true is code debt. Schedule deletion after one stable release.',content:'<p class="mb-4">if (flag) branches pile up in the Clincoo page bundle and confuse AI during debug.</p><p class="mb-4">After the feature is stable in production for one cycle, delete the flag and the dead branch.</p><p class="mb-4">Search every use of the flag name before you commit. One leftover if breaks tree-shaking.</p><p class="mb-4">Paste the grep result to AI. Ask for a deletion diff only, not a module rewrite.</p><p class="mb-4">Announce it on blog.clincoo.buzz so editor.clincoo.buzz and app.clincoo.buzz stay aligned.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['featureflag']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['featureflag'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
