// Clincoo Blog — pulihkan artikel audit lama
(function(){
  var extra = [
    {id:"audit-cek-tautan-rusak-sebelum-rilis",langs:{"id":{title:"Cek Tautan Rusak di Proyek Clincoo sebelum Rilis",desc:"href ke halaman yang dihapus atau # kosong merusak kepercayaan. Audit tautan internal dulu.",content:"<p class=\"mb-4\">Menu Clincoo masih menunjuk layanan-lama.html setelah folder diganti nama. Pengunjung mendarat di 404.</p><p class=\"mb-4\">Di editor.clincoo.buzz, kumpulkan semua href internal. Buka satu per satu di pratinjau.</p><p class=\"mb-4\">Perbaiki path, jangan andalkan mesin telusur.</p><p class=\"mb-4\">Minta AI membuat daftar tautan dari satu file menu.</p><p class=\"mb-4\">Clincoo tidak memindai tautan otomatis. Daftar tautan yang hidup menjaga app.clincoo.buzz terasa utuh.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Editor resmi Clincoo"},"en":{title:"Check Broken Links in a Clincoo Project before Release",desc:"href values to deleted pages or empty hashes break trust. Audit internal links first.",content:"<p class=\"mb-4\">A Clincoo menu still points at layanan-lama.html after the folder was renamed.</p><p class=\"mb-4\">In editor.clincoo.buzz, collect every internal href and open them in preview.</p><p class=\"mb-4\">Fix the path. Do not wait for a search engine.</p><p class=\"mb-4\">Ask AI to list links from one menu file.</p><p class=\"mb-4\">A living link list keeps app.clincoo.buzz feeling whole.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Official Clincoo editor"}}},
    {id:"audit-daftar-aset-tak-terpakai",langs:{"id":{title:"Buat Daftar Aset Tak Terpakai saat Audit Proyek Clincoo",desc:"Gambar dan skrip sisa template memperlambat unduhan. Catat berkas yang tidak dirujuk.",content:"<p class=\"mb-4\">Folder assets Clincoo masih berisi hero-old.webp dan slider.js yang tidak dipanggil.</p><p class=\"mb-4\">Di editor.clincoo.buzz, bandingkan daftar file dengan src, href, dan url() CSS.</p><p class=\"mb-4\">Jangan hapus font yang masih dipakai di halaman dalam.</p><p class=\"mb-4\">Minta AI mencocokkan nama file aset dengan markup yang kamu tempel.</p><p class=\"mb-4\">Audit aset menjaga unduhan di app.clincoo.buzz tetap ringan.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Editor resmi Clincoo"},"en":{title:"List Unused Assets when You Audit a Clincoo Project",desc:"Leftover template images and scripts slow the download.",content:"<p class=\"mb-4\">A Clincoo assets folder still holds unused hero-old.webp and slider.js.</p><p class=\"mb-4\">Compare the file list with src, href, and CSS url() values.</p><p class=\"mb-4\">Do not delete a font still used on an inner page.</p><p class=\"mb-4\">Ask AI to match asset filenames to the markup you paste.</p><p class=\"mb-4\">An asset audit keeps downloads on app.clincoo.buzz light.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Official Clincoo editor"}}},
    {id:"audit-title-dan-meta-unik",langs:{"id":{title:"Audit Title dan Meta Description Unik per Halaman Clincoo",desc:"Title sama di semua halaman membuat cuplikan telusur kabur.",content:"<p class=\"mb-4\">Template Clincoo menyalin title Beranda ke halaman harga dan blog.</p><p class=\"mb-4\">Di editor.clincoo.buzz, buka setiap index.html. Catat title dan meta description.</p><p class=\"mb-4\">Tulis title yang menyebut halaman itu, bukan hanya merek.</p><p class=\"mb-4\">Minta AI merangkum isi halaman menjadi title 50–60 karakter.</p><p class=\"mb-4\">Title unik menjaga cuplikan mengarah ke app.clincoo.buzz dengan benar.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Editor resmi Clincoo"},"en":{title:"Audit Unique Title and Meta Description on Each Clincoo Page",desc:"The same title on every page blurs search snippets.",content:"<p class=\"mb-4\">A Clincoo template copies the Home title onto pricing and blog pages.</p><p class=\"mb-4\">Open each index.html and note title and meta description.</p><p class=\"mb-4\">Write a title that names that page, not only the brand.</p><p class=\"mb-4\">Ask AI for a 50–60 character title from the page you pasted.</p><p class=\"mb-4\">Unique titles keep snippets pointing at app.clincoo.buzz correctly.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Official Clincoo editor"}}},
    {id:"audit-satu-h1-per-halaman",langs:{"id":{title:"Audit Satu H1 per Halaman di Proyek Clincoo",desc:"Dua H1 atau H1 slogan merek membingungkan outline.",content:"<p class=\"mb-4\">Halaman layanan Clincoo punya H1 di logo dan H1 lagi di hero.</p><p class=\"mb-4\">Cari semua h1 di satu file. Sisakan satu yang menyebut topik halaman.</p><p class=\"mb-4\">Jangan pakai h1 untuk gaya huruf besar. Gunakan kelas CSS.</p><p class=\"mb-4\">Tempel header ke AI dan minta daftar heading berurutan.</p><p class=\"mb-4\">Satu H1 membuat struktur di app.clincoo.buzz mudah diaudit.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Editor resmi Clincoo"},"en":{title:"Audit a Single H1 per Page in a Clincoo Project",desc:"Two H1s break the document outline.",content:"<p class=\"mb-4\">A Clincoo services page has an H1 in the logo and another in the hero.</p><p class=\"mb-4\">Keep one H1 that names the page topic. Demote the rest to h2.</p><p class=\"mb-4\">Do not use h1 just to get large type.</p><p class=\"mb-4\">Paste the header into AI and ask for a heading list.</p><p class=\"mb-4\">One H1 makes structure on app.clincoo.buzz easy to audit.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Official Clincoo editor"}}},
    {id:"audit-error-konsol-sebelum-rilis",langs:{"id":{title:"Audit Error Konsol Pratinjau Clincoo sebelum Rilis",desc:"404 skrip dan CORS di konsol sering lolos mata.",content:"<p class=\"mb-4\">Pratinjau terlihat rapi, tetapi konsol penuh Failed to load resource.</p><p class=\"mb-4\">Buka pratinjau, tekan F12, tab Console dan Network.</p><p class=\"mb-4\">Perbaiki src yang salah atau hapus skrip yang tidak dipakai.</p><p class=\"mb-4\">Tempel stack trace lengkap ke AI. Sertakan nama file.</p><p class=\"mb-4\">Konsol bersih berarti app.clincoo.buzz lebih bisa diprediksi.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Editor resmi Clincoo"},"en":{title:"Audit Console Errors in Clincoo Preview before Release",desc:"Script 404s and CORS issues slip past a visual check.",content:"<p class=\"mb-4\">Preview looks fine, but the console is full of failed resources.</p><p class=\"mb-4\">Open preview, press F12, then Console and Network.</p><p class=\"mb-4\">Fix the bad src or delete the unused script.</p><p class=\"mb-4\">Paste the full stack trace into AI with the filename.</p><p class=\"mb-4\">A clean preview console makes app.clincoo.buzz more predictable.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Official Clincoo editor"}}},
    {id:"audit-label-form-wajib",langs:{"id":{title:"Audit Label dan Field Wajib pada Form Clincoo",desc:"Placeholder bukan label. Cek for/id dan tanda required.",content:"<p class=\"mb-4\">Form kontak hanya punya placeholder Nama. Setelah diketik, petunjuk hilang.</p><p class=\"mb-4\">Setiap input perlu label dengan for yang sama dengan id.</p><p class=\"mb-4\">Uji kirim kosong di pratinjau. Pesan error harus menyebut field.</p><p class=\"mb-4\">Tempel markup form ke AI dan minta daftar input tanpa label.</p><p class=\"mb-4\">Form yang diaudit membuat app.clincoo.buzz bisa dipakai tanpa menebak.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Editor resmi Clincoo"},"en":{title:"Audit Labels and Required Fields on a Clincoo Form",desc:"A placeholder is not a label.",content:"<p class=\"mb-4\">A contact form only has a Name placeholder.</p><p class=\"mb-4\">Give every input a label whose for matches the id.</p><p class=\"mb-4\">Submit empty in preview. The error must name the field.</p><p class=\"mb-4\">Paste the form markup into AI and ask for unlabeled inputs.</p><p class=\"mb-4\">An audited form makes app.clincoo.buzz usable without guessing.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Official Clincoo editor"}}},
    {id:"audit-alt-dan-berat-gambar",langs:{"id":{title:"Audit Teks Alt dan Berat Gambar di Halaman Clincoo",desc:"Alt kosong dan PNG 4 MB lolos desain.",content:"<p class=\"mb-4\">Hero memakai foto studio 4000px dalam PNG. LCP lambat dan alt-nya image1.</p><p class=\"mb-4\">Daftar semua img. Isi alt yang menjelaskan fungsi gambar.</p><p class=\"mb-4\">Ganti PNG foto menjadi WebP atau JPEG. Tetapkan width dan height.</p><p class=\"mb-4\">Kirim nama file plus ukuran ke AI dan minta usulan format.</p><p class=\"mb-4\">Audit alt dan berat gambar menjaga app.clincoo.buzz cepat dan bisa dibaca.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Editor resmi Clincoo"},"en":{title:"Audit Image Alt Text and File Weight on a Clincoo Page",desc:"Empty alt and a 4 MB PNG slip past design review.",content:"<p class=\"mb-4\">A hero uses a 4000px studio photo as PNG. LCP is slow.</p><p class=\"mb-4\">List every img. Write alt that explains the image job.</p><p class=\"mb-4\">Swap photo PNGs for WebP or JPEG. Set width and height.</p><p class=\"mb-4\">Send filenames plus sizes to AI for a format suggestion.</p><p class=\"mb-4\">Auditing alt and weight keeps app.clincoo.buzz fast and readable.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Official Clincoo editor"}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["audit"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["audit"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
