// Clincoo Blog auth extra2 2026-10-02 WIB
(function(){
  var extra = [
    {id:'auth-jangan-log-token-di-konsol',langs:{id:{title:'Jangan Cetak Token Auth di Konsol saat Debug Clincoo',desc:'console.log pada sesi sering tertinggal sampai produksi. Log status login, bukan isi token.',content:'<p class=\"mb-4\">Saat login gagal di editor.clincoo.buzz, banyak draf menempel seluruh objek sesi ke konsol. Token ikut tersalin ke tangkapan layar dan riwayat chat AI.</p><p class=\"mb-4\">Log hanya boolean sudah login, kode status, dan waktu kedaluwarsa. Jangan cetak access token, refresh token, atau cookie.</p><p class=\"mb-4\">Sebelum deploy ke app.clincoo.buzz, cari console.log dan debugger di file auth. Minta AI menandai baris itu, jangan minta rewrite modul login.</p><p class=\"mb-4\">Jika perlu jejak, pakai id permintaan acak. Id itu aman dibagikan di blog.clincoo.buzz, token tidak.</p><p class=\"mb-4\">Hapus log setelah bug tertutup. Pratinjau yang bersih lebih berguna daripada konsol yang ramai.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Do Not Print Auth Tokens in the Console while Debugging Clincoo',desc:'A console.log of the session often survives into production. Log the login state, not the token value.',content:'<p class=\"mb-4\">When login fails in editor.clincoo.buzz, many drafts paste the whole session object into the console. The token then lands in screenshots and AI chat history.</p><p class=\"mb-4\">Log only a logged-in boolean, the status code, and the expiry time. Do not print the access token, refresh token, or cookie.</p><p class=\"mb-4\">Before deploying to app.clincoo.buzz, search for console.log and debugger in the auth file. Ask AI to flag those lines, not to rewrite the login module.</p><p class=\"mb-4\">If you need a trace, use a random request id. That id is safe to share on blog.clincoo.buzz; the token is not.</p><p class=\"mb-4\">Remove the log after the bug is closed. A clean preview is more useful than a noisy console.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ,{id:'auth-jangan-token-di-query',langs:{id:{title:'Jangan Taruh Token Sesi di Query URL Clincoo',desc:'Token di query ikut tersimpan di riwayat, log server, dan header Referer. Pindahkan ke header atau cookie yang tidak dibaca skrip.',content:'<p class="mb-4">Tautan berbagi dari app.clincoo.buzz kadang menyisipkan access_token di query. URL itu masuk riwayat browser dan log analytics.</p><p class="mb-4">Kirim sesi lewat header Authorization atau cookie HttpOnly Secure SameSite. Jangan letakkan rahasia di hash jika skrip halaman masih bisa membacanya.</p><p class="mb-4">Jika tautan undangan wajib membawa kode sekali pakai, buat kode pendek yang kedaluwarsa dan tukar di server. Jangan kirim token sesi penuh.</p><p class="mb-4">Saat minta AI memperbaiki login, tempel pesan error tanpa nilai token. Minta contoh header, bukan contoh URL berisi rahasia.</p><p class="mb-4">Cek Network di editor.clincoo.buzz: request dokumen tidak boleh menampilkan token di kolom query. Catat temuan di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Aplikasi resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Do Not Put a Session Token in a Clincoo URL Query',desc:'A token in the query is stored in history, server logs, and the Referer header. Move it to a header or a cookie scripts cannot read.',content:'<p class="mb-4">A share link from app.clincoo.buzz sometimes appends access_token to the query. That URL lands in browser history and analytics logs.</p><p class="mb-4">Send the session in an Authorization header or an HttpOnly Secure SameSite cookie. Do not put the secret in the hash if page scripts can still read it.</p><p class="mb-4">If an invite link must carry a one-time code, use a short expiring code and exchange it on the server. Do not send the full session token.</p><p class="mb-4">When asking AI to fix login, paste the error without the token value. Ask for a header example, not a URL that contains a secret.</p><p class="mb-4">Check Network on editor.clincoo.buzz: document requests must not show a token in the query column. Note the finding on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo app',source2:'Clincoo App',source3:'Clincoo Blog'}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['auth']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['auth'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
