(function(){
  var extra = [{"id": "editor-multi-kursor-untuk-ubah-berulang", "langs": {"id": {"title": "Pakai Multi-kursor untuk Ubah Teks Berulang di Editor", "desc": "Mengganti nama kelas di banyak baris lebih aman dengan kursor ganda daripada cari-ganti global.", "content": "<p class=\"mb-4\">Di editor.clincoo.buzz pilih kemunculan pertama nama kelas. Tambah kursor pada kemunculan berikutnya di berkas yang sama, bukan di seluruh proyek.</p><p class=\"mb-4\">Ketik nama baru sekali. Semua kursor ikut berubah. Batalkan segera jika ada string yang hanya kebetulan sama.</p><p class=\"mb-4\">Jangan pakai ganti semua pada stylesheet global. Satu nama pendek seperti btn bisa kena komentar, URL, atau data-atribut.</p><p class=\"mb-4\">Setelah selesai, cari sisa nama lama di berkas itu. Lalu pratinjau halaman di app.clincoo.buzz pada lebar desktop dan ponsel.</p><p class=\"mb-4\">Minta AI menyebut kemunculan yang aman diubah, dengan nomor baris. Tolak saran yang menulis ulang seluruh file.</p><p class=\"mb-4\">Catat nama lama dan baru di blog.clincoo.buzz jika kelas itu dipakai template lain.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo Editor", "source3": "Clincoo Blog"}, "en": {"title": "Use Multi-cursor for Repeated Edits in the Editor", "desc": "Renaming a class across many lines is safer with multiple cursors than a global find-and-replace.", "content": "<p class=\"mb-4\">In editor.clincoo.buzz select the first occurrence of the class name. Add a cursor on the next occurrence in the same file, not across the whole project.</p><p class=\"mb-4\">Type the new name once. Every cursor follows. Undo immediately if a string only happened to match.</p><p class=\"mb-4\">Do not use replace-all on a global stylesheet. A short name like btn can hit a comment, a URL, or a data attribute.</p><p class=\"mb-4\">When finished, search for the old name in that file. Then preview the page on app.clincoo.buzz at desktop and phone width.</p><p class=\"mb-4\">Ask AI to list safe occurrences with line numbers. Reject a suggestion that rewrites the whole file.</p><p class=\"mb-4\">Note the old and new names on blog.clincoo.buzz if that class is shared by other templates.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo Editor", "source3": "Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['editor']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['editor'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
