// Clincoo Blog pagination extra2 2026-09-30
(function(){
  var extra = [
    {id:'pagination-ellipsis-jangkauan-tengah',langs:{id:{title:'Tampilkan Ellipsis di Pager Clincoo yang Panjang',desc:'Dua puluh nomor halaman membuat toolbar pecah. Ellipsis menjaga halaman pertama, terakhir, dan tetangga.',content:'<p class="mb-4">Pager daftar proyek di app.clincoo.buzz yang menampilkan semua nomor membuat layout HP overflow.</p><p class="mb-4">Tampilkan 1, last, halaman aktif, plus satu tetangga kiri-kanan. Sisanya jadi ellipsis yang tidak bisa diklik.</p><p class="mb-4">Jangan buat ellipsis sebagai tautan ke halaman acak. Pengguna mengira itu lompat cepat.</p><p class="mb-4">Tempel rumus window pager ke AI. Minta implementasi tanpa library.</p><p class="mb-4">Uji di editor.clincoo.buzz dengan total 30 halaman. Catat pola di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Show Ellipsis on a Long Clincoo Pager',desc:'Twenty page numbers break the toolbar. Ellipsis keeps first, last, and neighbors.',content:'<p class="mb-4">A project list pager on app.clincoo.buzz that prints every number overflows on a phone.</p><p class="mb-4">Show 1, last, the active page, plus one neighbor on each side. The rest becomes non-clickable ellipsis.</p><p class="mb-4">Do not turn ellipsis into a link to a random page. Users think it is a fast jump.</p><p class="mb-4">Paste the pager window formula to AI. Ask for an implementation without a library.</p><p class="mb-4">Test on editor.clincoo.buzz with 30 total pages. Note the pattern on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'pagination-rel-next-prev-head',langs:{id:{title:'Pasang rel=next dan rel=prev di Head Daftar Clincoo',desc:'Halaman daftar tanpa rel next/prev membuat crawler mengira setiap page URL adalah dokumen terpisah tanpa urutan.',content:'<p class="mb-4">Arsip template Clincoo di page=2 sering diindeks tanpa tautan ke page=1. Crawler tidak melihat urutan.</p><p class="mb-4">Tambah link rel=prev dan rel=next di head sesuai nomor halaman. Hilangkan rel yang tidak relevan di ujung.</p><p class="mb-4">Samakan dengan query yang sudah ada. Jangan buat URL kanonik yang membuang filter.</p><p class="mb-4">Tanya AI: tempel head HTML plus URL page. Minta hanya dua tautan rel.</p><p class="mb-4">Cek di editor.clincoo.buzz lalu sitemap blog.clincoo.buzz agar page dalam tidak orphan.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Add rel=next and rel=prev in the Clincoo List Head',desc:'A list page without rel next/prev makes crawlers treat each page URL as an unordered document.',content:'<p class="mb-4">Clincoo template archives on page=2 are often indexed with no link to page=1. Crawlers miss the order.</p><p class="mb-4">Add link rel=prev and rel=next in the head for the current page number. Drop the unused rel at the ends.</p><p class="mb-4">Keep existing query params. Do not invent a canonical that strips filters.</p><p class="mb-4">Ask AI: paste the head HTML plus the page URL. Request only the two rel links.</p><p class="mb-4">Check on editor.clincoo.buzz then the blog.clincoo.buzz sitemap so inner pages are not orphans.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['pagination']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['pagination'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
