// Clincoo Blog — artikel testing tambahan 2026-09-29
(function(){
  var extra = [{"id": "testing-repro-di-tab-baru", "langs": {"id": {"title": "Ulangi Bug di Tab Baru Sebelum Menulis Tes Clincoo", "desc": "Jika bug tidak muncul di tab bersih, itu state lokal, bukan regresi kode.", "content": "<p class=\"mb-4\">Sebelum menulis tes di editor.clincoo.buzz, buka URL yang sama di tab penyamaran. Banyak bug hanya sisa localStorage.</p><p class=\"mb-4\">Catat langkah repro: URL, klik, data yang diketik. Tes yang baik meniru langkah itu, bukan menguji kerangka tes itu sendiri.</p><p class=\"mb-4\">Jika gagal hanya di satu browser, tempel User-Agent dan pesan console ke AI. Jangan minta rewrite seluruh suite.</p><p class=\"mb-4\">Satu tes untuk satu perilaku. Jangan gabungkan login, unggah, dan ekspor dalam satu fungsi.</p><p class=\"mb-4\">Alur ini dipakai saat memeriksa pratinjau app.clincoo.buzz dan tautan di blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Reproduce the Bug in a Fresh Tab Before Writing Clincoo Tests", "desc": "If the bug does not appear in a clean tab, it is local state, not a code regression.", "content": "<p class=\"mb-4\">Before writing a test in editor.clincoo.buzz, open the same URL in a private tab. Many bugs are leftover localStorage.</p><p class=\"mb-4\">Write the repro steps: URL, clicks, typed data. A good test mirrors those steps, not the test harness.</p><p class=\"mb-4\">If it fails in one browser only, paste the User-Agent and console message to AI. Do not ask for a full suite rewrite.</p><p class=\"mb-4\">One test per behavior. Do not mix login, upload, and export in one function.</p><p class=\"mb-4\">This flow is used when checking the app.clincoo.buzz preview and links on blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["testing"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["testing"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
