(function(){
  var extra = [{"id": "deploy-cek-redirect-https-setelah-rilis", "langs": {"id": {"title": "Cek Redirect HTTPS setelah Rilis Clincoo", "desc": "HTTP yang tidak meloncat ke HTTPS membuat aset tercampur dan peringatan browser muncul.", "content": "<p class=\"mb-4\">Setelah rilis dari editor.clincoo.buzz, buka tab baru dan ketik URL dengan http://, bukan https://.</p><p class=\"mb-4\">Respons harus 301 atau 308 ke host yang sama di https. Jangan biarkan 200 di HTTP hanya karena pratinjau internal lolos.</p><p class=\"mb-4\">Di DevTools, panel Network, pastikan dokumen, CSS, dan JS semuanya https. Aset http memicu mixed content dan bisa diblokir.</p><p class=\"mb-4\">Uji juga URL dengan garis miring akhir dan tanpa garis miring. Keduanya harus mendarat di satu canonical.</p><p class=\"mb-4\">Minta AI menyusun daftar URL yang dicek, bukan menulis ulang server. Tempel hanya status dan header Location.</p><p class=\"mb-4\">Catat hasil di blog.clincoo.buzz lalu buka app.clincoo.buzz sekali lagi dari jaringan selain Wi-Fi kantor.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content", "sourceSnippet": "Mixed content diblokir browser", "source2": "MDN: Mixed content", "source3": "Clincoo Editor"}, "en": {"title": "Check the HTTPS Redirect after a Clincoo Release", "desc": "HTTP that does not jump to HTTPS mixes assets and triggers browser warnings.", "content": "<p class=\"mb-4\">After a release from editor.clincoo.buzz, open a fresh tab and type the URL with http://, not https://.</p><p class=\"mb-4\">The response should be 301 or 308 to the same host on https. Do not accept a 200 on HTTP just because the internal preview passed.</p><p class=\"mb-4\">In DevTools, Network panel, confirm the document, CSS, and JS are all https. An http asset triggers mixed content and may be blocked.</p><p class=\"mb-4\">Also test the URL with and without a trailing slash. Both should land on one canonical.</p><p class=\"mb-4\">Ask AI to draft the checklist of URLs, not to rewrite the server. Paste only the status and the Location header.</p><p class=\"mb-4\">Record the result on blog.clincoo.buzz, then open app.clincoo.buzz once more from a network other than the office Wi-Fi.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content", "sourceSnippet": "Mixed content diblokir browser", "source2": "MDN: Mixed content", "source3": "Clincoo Editor"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['deploy']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['deploy'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
