// Clincoo Blog print extra 2026-09-30
(function(){
  var extra = [
    {id:'print-background-izin-browser',langs:{id:{title:'Aktifkan Cetak Warna Latar di Browser untuk Halaman Clincoo',desc:'Browser sering mematikan background-color saat print. Izinkan grafis latar agar kartu Clincoo tetap terbaca.',content:'<p class="mb-4">Di editor.clincoo.buzz, kartu harga yang andalkan background hilang jadi kotak putih saat Print Preview.</p><p class="mb-4">Tambah print-color-adjust: exact pada blok yang wajib berwarna.</p><p class="mb-4">Di Chrome centang Background graphics. Tempel screenshot preview kosong ke AI.</p><p class="mb-4">Uji di app.clincoo.buzz dan blog.clincoo.buzz sebelum klien mencetak.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Enable Background Colors When Printing a Clincoo Page',desc:'Browsers often drop background-color on print. Allow background graphics so Clincoo cards stay readable.',content:'<p class="mb-4">On editor.clincoo.buzz, price cards become empty white boxes in Print Preview.</p><p class="mb-4">Add print-color-adjust: exact on blocks that must keep color.</p><p class="mb-4">In Chrome enable Background graphics. Paste a blank preview screenshot to AI.</p><p class="mb-4">Test on app.clincoo.buzz and blog.clincoo.buzz before a client prints.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'print-ukuran-kertas-a4-margin',langs:{id:{title:'Setel Ukuran Kertas A4 dan Margin pada @page Clincoo',desc:'Halaman invoice yang mepet tepi terpotong di printer rumah. Atur size dan margin di aturan @page.',content:'<p class="mb-4">Di editor.clincoo.buzz, konten selebar viewport sering terpotong di printer.</p><p class="mb-4">Tambah @page { size: A4; margin: 16mm; } khusus media print.</p><p class="mb-4">Kirim potongan @page ke AI, bukan minta layout ulang dashboard.</p><p class="mb-4">Pratinjau A4 di app.clincoo.buzz dan blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Set A4 Paper Size and Margins with @page in Clincoo',desc:'Invoice pages that hug the viewport get clipped on home printers. Set size and margin in @page.',content:'<p class="mb-4">On editor.clincoo.buzz, viewport-wide content often loses space on a home printer.</p><p class="mb-4">Add @page { size: A4; margin: 16mm; } for print media only.</p><p class="mb-4">Send the @page snippet to AI instead of a full rewrite.</p><p class="mb-4">Preview A4 on app.clincoo.buzz and blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'print-gambar-lebar-penuh-kertas',langs:{id:{title:'Batasi Lebar Gambar agar Tidak Meluber saat Cetak Clincoo',desc:'Foto produk max-width 100% di layar masih bisa overflow di kertas. Atur ulang gambar di media print.',content:'<p class="mb-4">Di editor.clincoo.buzz, hero image 1200px merusak halaman cetak.</p><p class="mb-4">Di @media print set img { max-width: 100%; height: auto; }.</p><p class="mb-4">Tempel HTML img bermasalah ke AI. Uji di app.clincoo.buzz dan blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Cap Image Width so Photos Do Not Overflow Clincoo Print',desc:'Product photos that are max-width 100% on screen can still overflow paper. Reset images in print media.',content:'<p class="mb-4">On editor.clincoo.buzz, a 1200px hero image wrecks the printed page.</p><p class="mb-4">In @media print set img { max-width: 100%; height: auto; }.</p><p class="mb-4">Paste the img markup to AI. Test on app.clincoo.buzz and blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'print-sembunyikan-footer-sosial',langs:{id:{title:'Sembunyikan Footer Sosial saat Mencetak Halaman Clincoo',desc:'Ikon share dan widget chat memakan kertas kosong. Sembunyikan elemen interaktif di media print.',content:'<p class="mb-4">Di editor.clincoo.buzz, footer sosial tidak berguna di kertas.</p><p class="mb-4">Pakai kelas .no-print dan display:none di @media print. Jangan sembunyikan alamat invoice.</p><p class="mb-4">Pratinjau di app.clincoo.buzz dan blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Hide Social Footers When Printing a Clincoo Page',desc:'Share icons and chat widgets waste blank paper. Hide interactive chrome in print media.',content:'<p class="mb-4">On editor.clincoo.buzz, a social footer is useless on paper.</p><p class="mb-4">Use .no-print and display:none in @media print. Keep invoice address.</p><p class="mb-4">Preview on app.clincoo.buzz and blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'print-cek-pratinjau-sebelum-kirim',langs:{id:{title:'Cek Print Preview sebelum Membagikan Halaman Clincoo',desc:'Bug cetak baru terlihat setelah klien menekan Ctrl+P. Jadikan pratinjau kertas bagian dari checklist rilis.',content:'<p class="mb-4">Di editor.clincoo.buzz, halaman rapi di layar bisa pecah di Print Preview.</p><p class="mb-4">Buka Ctrl+P, pilih A4, simpan PDF uji, perbaiki satu aturan print.</p><p class="mb-4">Uji ulang di app.clincoo.buzz dan tautkan contoh di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Check Print Preview before Sharing a Clincoo Page',desc:'Print bugs show up only after a client hits Ctrl+P. Make paper preview part of the release checklist.',content:'<p class="mb-4">On editor.clincoo.buzz, a page can look fine on screen and break in Print Preview.</p><p class="mb-4">Open Ctrl+P, choose A4, save a test PDF, fix one print rule.</p><p class="mb-4">Retest on app.clincoo.buzz and link an example on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['print']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['print'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
