// Clincoo Blog — artikel svg tambahan 2026-09-29
(function(){
  var extra = [
    {"id":"svg-fokusable-false-pada-path","langs":{"id":{"title":"Matikan Fokus pada Path SVG Ikon Clincoo","desc":"Path di dalam tombol ikon bisa jadi target Tab. Tandai fokusable=false agar fokus tetap di tombol.","content":"<p class=\"mb-4\">Ikon SVG di tombol Clincoo kadang menerima fokus sendiri. Pengguna keyboard berhenti di path, bukan di kontrol.</p><p class=\"mb-4\">Tambah focusable=\"false\" pada svg dekoratif, plus aria-hidden=\"true\" jika ikon tidak membawa arti sendiri.</p><p class=\"mb-4\">Uji Tab di editor.clincoo.buzz. Urutan harus lompat antar tombol, bukan masuk ke dalam gambar.</p><p class=\"mb-4\">Minta AI menandai svg tanpa focusable di komponen tombol. Jangan minta rewrite seluruh sprite.</p><p class=\"mb-4\">Clincoo di app.clincoo.buzz terasa rapi jika ikon tidak mencuri fokus.</p>","source":"Clincoo","sourceUrl":"https://editor.clincoo.buzz/","sourceSnippet":"Editor resmi Clincoo","source2":"Clincoo App","source3":"Clincoo Blog"},"en":{"title":"Turn Off Focus on Clincoo Icon SVG Paths","desc":"Paths inside an icon button can become Tab targets. Mark focusable=false so focus stays on the button.","content":"<p class=\"mb-4\">SVG icons in Clincoo buttons sometimes take focus themselves. Keyboard users stop on a path, not on the control.</p><p class=\"mb-4\">Add focusable=\"false\" on decorative svg, plus aria-hidden=\"true\" when the icon has no meaning of its own.</p><p class=\"mb-4\">Test Tab in editor.clincoo.buzz. Order should jump between buttons, not into the drawing.</p><p class=\"mb-4\">Ask AI to flag svg without focusable in button components. Do not ask it to rewrite the whole sprite.</p><p class=\"mb-4\">Clincoo on app.clincoo.buzz feels tidy when icons do not steal focus.</p>","source":"Clincoo","sourceUrl":"https://editor.clincoo.buzz/","sourceSnippet":"Official Clincoo editor","source2":"Clincoo App","source3":"Clincoo Blog"}}},
    {"id":"svg-minify-path-sebelum-inline","langs":{"id":{"title":"Minify Path SVG Clincoo sebelum Inline di Halaman","desc":"Path panjang dari editor desain membengkakkan HTML. Rapikan dulu, lalu tempel di komponen.","content":"<p class=\"mb-4\">SVG mentah dari alat desain membawa desimal panjang dan grup kosong. Inline ke halaman Clincoo membuat HTML berat.</p><p class=\"mb-4\">Jalankan minify path: buang metadata, pendekkan angka, gabungkan path sejenis. Simpan hasil di komponen ikon.</p><p class=\"mb-4\">Bandingkan pratinjau sebelum dan sesudah di editor.clincoo.buzz. Bentuk harus sama, ukuran file turun.</p><p class=\"mb-4\">Tempel satu svg ke AI dan minta versi ringkas. Jangan kirim seluruh set ikon sekaligus.</p><p class=\"mb-4\">Clincoo di blog.clincoo.buzz lebih cepat jika path sudah ramping sebelum rilis.</p>","source":"Clincoo","sourceUrl":"https://blog.clincoo.buzz/","sourceSnippet":"Clincoo Blog","source2":"Clincoo Editor","source3":"Clincoo App"},"en":{"title":"Minify Clincoo SVG Paths before Inlining Them","desc":"Long paths from a design tool bloat HTML. Clean them first, then paste into the component.","content":"<p class=\"mb-4\">Raw SVG from a design tool carries long decimals and empty groups. Inlining that into a Clincoo page makes HTML heavy.</p><p class=\"mb-4\">Minify the path: drop metadata, shorten numbers, merge similar paths. Store the result in the icon component.</p><p class=\"mb-4\">Compare preview before and after in editor.clincoo.buzz. Shape should match, file size should drop.</p><p class=\"mb-4\">Paste one svg to AI and ask for a compact version. Do not send the whole icon set at once.</p><p class=\"mb-4\">Clincoo on blog.clincoo.buzz is faster when paths are slim before release.</p>","source":"Clincoo","sourceUrl":"https://blog.clincoo.buzz/","sourceSnippet":"Clincoo Blog","source2":"Clincoo Editor","source3":"Clincoo App"}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["svg"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["svg"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
