// Clincoo Blog — artikel form tambahan 2026-09-29
(function(){
  var extra = [{"id": "form-novalidate-lalu-cek-custom", "langs": {"id": {"title": "Pakai novalidate, Lalu Cek Field Sendiri di Clincoo", "desc": "Validasi native browser sering tidak cocok dengan desain form Clincoo. Matikan default, periksa field satu per satu.", "content": "<p class=\"mb-4\">Atribut novalidate pada form di editor.clincoo.buzz menahan pop-up native yang menutupi pesan error kustom Anda.</p><p class=\"mb-4\">Setelah submit, loop setiap input required. Jika kosong, set textContent pada elemen error di dekat field, lalu focus ke input pertama yang gagal.</p><p class=\"mb-4\">Jangan andalkan alert(). Di pratinjau app.clincoo.buzz alert memutus alur dan sulit dibaca di ponsel.</p><p class=\"mb-4\">Tempel fungsi cek ke AI dan minta ia tunjuk field yang belum punya pesan. Satu form, satu permintaan.</p><p class=\"mb-4\">Uji di pratinjau Clincoo: kirim kosong, kirim email rusak, lalu kirim valid. Tiga jalur itu menutup sebagian besar bug form.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Use novalidate, Then Check Fields Yourself in Clincoo", "desc": "Native browser validation often clashes with Clincoo form design. Turn the default off and inspect fields one by one.", "content": "<p class=\"mb-4\">The novalidate attribute on a form in editor.clincoo.buzz stops native popups from covering your custom error text.</p><p class=\"mb-4\">After submit, loop each required input. If empty, set textContent on the error element next to the field, then focus the first failure.</p><p class=\"mb-4\">Do not rely on alert(). In the app.clincoo.buzz preview an alert breaks the flow and is hard to read on a phone.</p><p class=\"mb-4\">Paste the check function into AI and ask it which field still has no message. One form, one request.</p><p class=\"mb-4\">Test in Clincoo preview: submit empty, submit a broken email, then submit valid data. Those three paths catch most form bugs.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["form"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["form"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
