// Clincoo Blog — artikel offline tambahan 2026-10-02
(function(){
  var extra = [{"id": "offline-jangan-simpan-token-di-localstorage", "langs": {"id": {"title": "Jangan Simpan Token Sesi di localStorage untuk Mode Offline Clincoo", "desc": "Draf offline boleh di perangkat. Token login tidak boleh. localStorage bisa dibaca skrip lain di origin yang sama.", "content": "<p class=\"mb-4\">Mode offline di editor.clincoo.buzz sering menyimpan draf ke localStorage atau IndexedDB. Jangan ikut menyimpan access token, refresh token, atau kunci sesi di tempat yang sama.</p><p class=\"mb-4\">localStorage bisa dibaca JavaScript mana pun di origin itu. Satu skrip pihak ketiga atau cuplikan yang disisipkan XSS langsung mengambil token tanpa perlu membuka jaringan.</p><p class=\"mb-4\">Simpan hanya isi draf dan id antrian. Autentikasi tetap di cookie HttpOnly yang dikirim browser saat online kembali. Jika token harus ada di klien, pakai memori tab, bukan penyimpanan permanen.</p><p class=\"mb-4\">Cek Application panel di DevTools. Jika kunci token muncul di Local Storage, pindahkan. Uji juga mode offline: draf tetap ada, sesi tidak tersalin ke file cadangan.</p>", "source": "MDN localStorage", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage", "sourceSnippet": "localStorage is accessible to JavaScript on the same origin.", "source2": "OWASP HTML5 Security Cheat Sheet", "source3": "Clincoo App"}, "en": {"title": "Do Not Store Session Tokens in localStorage for Clincoo Offline Mode", "desc": "Offline drafts may live on the device. Login tokens must not. localStorage is readable by any script on the same origin.", "content": "<p class=\"mb-4\">Offline mode in editor.clincoo.buzz often stores drafts in localStorage or IndexedDB. Do not store access tokens, refresh tokens, or session keys in the same place.</p><p class=\"mb-4\">localStorage is readable by any JavaScript on that origin. One third-party script or an XSS snippet can take the token without touching the network.</p><p class=\"mb-4\">Store only the draft body and a queue id. Keep authentication in an HttpOnly cookie that the browser sends when the network returns. If a token must exist on the client, keep it in tab memory, not durable storage.</p><p class=\"mb-4\">Check the Application panel in DevTools. If a token key appears in Local Storage, move it. Test offline mode too: the draft remains, the session is not copied into a backup file.</p>", "source": "MDN localStorage", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage", "sourceSnippet": "localStorage is accessible to JavaScript on the same origin.", "source2": "OWASP HTML5 Security Cheat Sheet", "source3": "Clincoo App"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["offline"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["offline"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
