// Clincoo Blog — artikel branding tambahan 2026-10-01
(function(){
  var extra = [
    {"id": "branding-token-warna-jangan-ditimpa-inline", "langs": {"id": {"title": "Jangan Timpa Token Warna Branding dengan Warna Inline di Clincoo", "desc": "Warna inline di satu halaman memecah token merek. Pakai variabel CSS yang sama di semua template.", "content": "<p class=\"mb-4\">Di editor.clincoo.buzz, tombol hijau di satu section dan biru di section lain biasanya muncul karena style inline menimpa token. Pengunjung melihat merek yang tidak konsisten.</p><p class=\"mb-4\">Tetapkan --brand dan --brand-ink di :root. Semua tombol, tautan, dan aksen memakai var(--brand), bukan kode heksa di atribut style.</p><p class=\"mb-4\">Cari di DevTools: Computed lalu warna yang tidak cocok. Jika sumbernya style attribute, pindahkan nilai ke kelas token.</p><p class=\"mb-4\">Saat minta bantuan AI, tempel potongan :root dan kelas tombol. Minta AI mengganti heksa inline ke variabel, jangan minta palet baru.</p><p class=\"mb-4\">Pratinjau di app.clincoo.buzz dan blog.clincoo.buzz. Jika satu kartu masih menyimpang, itu halaman yang belum memakai token.</p>", "source": "MDN CSS custom properties", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties", "sourceSnippet": "CSS variables keep brand colors in one place.", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Do Not Override Branding Color Tokens with Inline Colors in Clincoo", "desc": "Inline colors on one page break brand tokens. Use the same CSS variables across every template.", "content": "<p class=\"mb-4\">On editor.clincoo.buzz, a green button in one section and a blue button in another usually means an inline style overrode the token. Visitors see an inconsistent brand.</p><p class=\"mb-4\">Define --brand and --brand-ink on :root. Buttons, links, and accents should use var(--brand), not a hex code in a style attribute.</p><p class=\"mb-4\">In DevTools open Computed and find the mismatched color. If the source is a style attribute, move the value into a token class.</p><p class=\"mb-4\">When asking AI for help, paste the :root block and the button class. Ask it to replace inline hex with the variable, not to invent a new palette.</p><p class=\"mb-4\">Preview on app.clincoo.buzz and blog.clincoo.buzz. If one card still drifts, that page is not using the token yet.</p>", "source": "MDN CSS custom properties", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties", "sourceSnippet": "CSS variables keep brand colors in one place.", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["branding"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["branding"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
