// Clincoo Blog — artikel privacy 2026-09-30
(function(){
  var extra = [
    {id:'privacy-jangan-log-token-di-console',langs:{id:{title:'Jangan Log Token atau Cookie di Konsol Clincoo',desc:'console.log token memaparkan sesi saat share screen atau saat AI membaca screenshot error.',content:'<p class="mb-4">Saat debug di editor.clincoo.buzz, token di console.log ikut terekam di rekaman layar dan issue tracker.</p><p class="mb-4">Log hanya prefix pendek atau boolean "ada token". Jangan tempel Authorization header utuh ke chat AI.</p><p class="mb-4">Bersihkan konsol sebelum screenshot untuk blog.clincoo.buzz atau tiket. Revoke token yang sempat bocor.</p><p class="mb-4">Minta AI meninjau kode log, bukan menjelaskan cara menyimpan token di localStorage tanpa batas.</p><p class="mb-4">Clincoo di app.clincoo.buzz memperlakukan sesi sebagai data sensitif, bukan teks debug.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Do Not Log Tokens or Cookies in the Clincoo Console',desc:'Logging a token exposes the session when you share a screen or when AI reads an error screenshot.',content:'<p class="mb-4">While debugging on editor.clincoo.buzz, a token in console.log is captured in screen recordings and issue trackers.</p><p class="mb-4">Log only a short prefix or a "has token" boolean. Do not paste a full Authorization header into an AI chat.</p><p class="mb-4">Clear the console before a screenshot for blog.clincoo.buzz or a ticket. Revoke any token that leaked.</p><p class="mb-4">Ask AI to review logging code, not how to store tokens in localStorage forever.</p><p class="mb-4">Clincoo on app.clincoo.buzz treats the session as sensitive data, not debug text.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'privacy-masking-data-form-sebelum-screenshot',langs:{id:{title:'Samarkan Data Form sebelum Screenshot Bug Clincoo',desc:'Laporan bug yang berisi nama, email, atau nomor klien menyebar lebih jauh dari yang Anda kira.',content:'<p class="mb-4">Sebelum mengirim screenshot pratinjau editor.clincoo.buzz ke AI atau ke kanal tim, tutup field email, telepon, dan alamat.</p><p class="mb-4">Pakai data dummy yang jelas palsu. Jangan unggah isi form produksi ke chat publik.</p><p class="mb-4">Jika file HAR ikut dilampirkan, buka dulu dan hapus cookie plus query token.</p><p class="mb-4">Minta AI menjelaskan langkah repro dari UI yang sudah disamarkan. Jangan kirim basis data klien.</p><p class="mb-4">Clincoo di blog.clincoo.buzz dan app.clincoo.buzz merawat kepercayaan klien mulai dari lampiran bug.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Mask Form Data before a Clincoo Bug Screenshot',desc:'A bug report that includes a client name, email, or phone travels farther than you think.',content:'<p class="mb-4">Before you send an editor.clincoo.buzz preview screenshot to AI or a team channel, cover email, phone, and address fields.</p><p class="mb-4">Use dummy data that is obviously fake. Do not upload production form values to a public chat.</p><p class="mb-4">If you attach a HAR file, open it first and strip cookies plus token query strings.</p><p class="mb-4">Ask AI to explain repro steps from the masked UI. Do not send a client database.</p><p class="mb-4">Clincoo on blog.clincoo.buzz and app.clincoo.buzz protects client trust starting with bug attachments.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['privacy']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['privacy'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
