// Clincoo Blog — artikel onboarding tambahan 2026-10-02
(function(){
  var extra = [{"id": "onboarding-commit-kecil-setelah-langkah-pertama", "langs": {"id": {"title": "Commit Kecil setelah Langkah Pertama di Proyek Clincoo", "desc": "Perubahan hari pertama mudah campur aduk. Simpan satu langkah yang sudah jalan sebelum lanjut ke langkah berikutnya.", "content": "<p class=\"mb-4\">Onboarding di editor.clincoo.buzz sering mengganti judul, favicon, dan teks beranda sekaligus. Tanpa titik simpan, satu kesalahan menimpa langkah yang sudah benar.</p><p class=\"mb-4\">Setelah beranda tampil di pratinjau, ekspor atau salin cuplikan yang jalan, lalu catat satu kalimat apa yang berubah. Itu commit mental jika proyek belum memakai Git.</p><p class=\"mb-4\">Jika proyek dihubungkan ke Git, buat commit kecil: hanya index.html dan judul. Jangan ikut file node_modules atau draf AI yang belum dicek.</p><p class=\"mb-4\">Langkah berikutnya (menu, kontak, SEO) mulai dari titik itu. Jika rusak, kembali ke commit pertama, bukan mengulang dari template kosong.</p>", "source": "Git basics — recording changes", "sourceUrl": "https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository", "sourceSnippet": "Record a coherent set of changes as one commit.", "source2": "Clincoo Editor", "source3": "Clincoo Blog"}, "en": {"title": "Make a Small Commit After the First Step in a Clincoo Project", "desc": "First-day edits get tangled fast. Save one working step before you move to the next.", "content": "<p class=\"mb-4\">Onboarding in editor.clincoo.buzz often changes the title, favicon, and home copy at once. Without a save point, one mistake overwrites a step that already worked.</p><p class=\"mb-4\">After the home page shows in preview, export or copy the working snippet and note one sentence about what changed. That is a mental commit if the project is not on Git yet.</p><p class=\"mb-4\">If the project is linked to Git, make a small commit: only index.html and the title. Do not include node_modules or unchecked AI drafts.</p><p class=\"mb-4\">The next step (menu, contact, SEO) starts from that point. If it breaks, return to the first commit instead of restarting from an empty template.</p>", "source": "Git basics — recording changes", "sourceUrl": "https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository", "sourceSnippet": "Record a coherent set of changes as one commit.", "source2": "Clincoo Editor", "source3": "Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["onboarding"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["onboarding"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
