// Clincoo Blog — artikel panduan tambahan 2026-10-02
(function(){
  var extra = [{"id": "panduan-struktur-folder-aset-css-js", "langs": {"id": {"title": "Rapikan Struktur Folder Aset, CSS, dan JS di Proyek Clincoo", "desc": "File menumpuk di root membuat pratinjau dan deploy sulit dilacak. Pisahkan halaman, gaya, skrip, dan gambar.", "content": "<p class=\"mb-4\">Proyek baru di editor.clincoo.buzz sering menaruh style.css, app.js, dan logo.png sejajar dengan index.html. Itu cukup untuk satu halaman, kacau setelah ada tentang dan kontak.</p><p class=\"mb-4\">Pakai pola sederhana: halaman di root atau folder tiap rute, CSS di assets/css, JS di assets/js, gambar di assets/img. Nama file huruf kecil dan tanda hubung.</p><p class=\"mb-4\">Tautan relatif harus mengikuti kedalaman folder. Dari /kontak/index.html, logo ada di ../assets/img/logo.png. Cek di pratinjau, bukan hanya di editor.</p><p class=\"mb-4\">Jangan salin seluruh template ke folder baru. Pindahkan satu jenis file, refresh, lalu lanjut. Struktur yang rapi juga memudahkan saat minta bantuan AI: sebut path yang tepat.</p>", "source": "MDN organizing a page", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files", "sourceSnippet": "Keep HTML, CSS, and assets in a clear file structure.", "source2": "Clincoo Editor", "source3": "Clincoo Blog"}, "en": {"title": "Tidy the Asset, CSS, and JS Folder Structure in a Clincoo Project", "desc": "Files piled in the root make preview and deploy hard to trace. Separate pages, styles, scripts, and images.", "content": "<p class=\"mb-4\">A new project in editor.clincoo.buzz often puts style.css, app.js, and logo.png next to index.html. That is fine for one page and messy after about and contact exist.</p><p class=\"mb-4\">Use a simple pattern: pages at the root or one folder per route, CSS in assets/css, JS in assets/js, images in assets/img. File names stay lowercase with hyphens.</p><p class=\"mb-4\">Relative links must follow folder depth. From /kontak/index.html the logo is ../assets/img/logo.png. Check in preview, not only in the editor.</p><p class=\"mb-4\">Do not copy the whole template into a new folder. Move one kind of file, refresh, then continue. A tidy tree also helps when you ask AI: name the exact path.</p>", "source": "MDN organizing a page", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files", "sourceSnippet": "Keep HTML, CSS, and assets in a clear file structure.", "source2": "Clincoo Editor", "source3": "Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["panduan"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["panduan"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
