// Clincoo Blog — artikel grid tambahan 2026-09-29
(function(){
  var extra = [{"id": "grid-minmax-kolom-responsif", "langs": {"id": {"title": "Kolom Grid Responsif dengan minmax di Clincoo", "desc": "Jangan hardcode tiga kolom. Pakai repeat(auto-fit, minmax) agar kartu merapat.", "content": "<p class=\"mb-4\">Kartu template di editor.clincoo.buzz pecah di layar kecil jika grid-template-columns: 1fr 1fr 1fr dipaksa.</p><p class=\"mb-4\">Gunakan grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr)) plus gap. Kartu turun baris tanpa media query ekstra.</p><p class=\"mb-4\">Jika satu kartu melebar aneh, cek min-width pada anak. minmax kalah jika anak punya min-width lebih besar.</p><p class=\"mb-4\">Kirim screenshot layout pecah ke AI bersama aturan grid. Jangan minta framework baru hanya untuk tiga kartu.</p><p class=\"mb-4\">Uji di app.clincoo.buzz lalu bandingkan listing di blog.clincoo.buzz agar ritme kolom sama.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Responsive Grid Columns with minmax in Clincoo", "desc": "Do not hardcode three columns. Use repeat(auto-fit, minmax) so cards pack cleanly.", "content": "<p class=\"mb-4\">Template cards on editor.clincoo.buzz break on small screens if grid-template-columns: 1fr 1fr 1fr is forced.</p><p class=\"mb-4\">Use grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr)) plus gap. Cards wrap without extra media queries.</p><p class=\"mb-4\">If one card stretches oddly, check min-width on children. minmax loses when a child min-width is larger.</p><p class=\"mb-4\">Send a screenshot of the broken layout to AI with the grid rule. Do not ask for a new framework for three cards.</p><p class=\"mb-4\">Test on app.clincoo.buzz then compare the listing on blog.clincoo.buzz so column rhythm matches.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["grid"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["grid"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
