// Clincoo Blog — artikel darkmode tambahan 2026-10-01 WIB
(function(){
  var extra = [{"id": "darkmode-jangan-invert-seluruh-halaman", "langs": {"id": {"title": "Jangan Pakai filter: invert untuk Mode Gelap Clincoo", "desc": "filter: invert(1) membalik foto, logo, dan bagan. Token warna dan prefers-color-scheme menjaga merek Clincoo tetap benar.", "content": "<p class=\"mb-4\">Beberapa draf di editor.clincoo.buzz memakai filter: invert(1) hue-rotate(180deg) pada body. Logo dan foto produk ikut terbalik.</p><p class=\"mb-4\">Mode gelap yang benar mengganti token latar, teks, dan border. Gambar tetap utuh, kecuali ada aset versi gelap yang disiapkan.</p><p class=\"mb-4\">invert juga merusak kontras fokus dan warna status form. Hijau sukses bisa jadi ungu yang tidak dikenali.</p><p class=\"mb-4\">Jika AI menawarkan filter invert sebagai jalan cepat, tolak. Minta variabel CSS dan media query prefers-color-scheme.</p><p class=\"mb-4\">Bandingkan pratinjau terang dan gelap di app.clincoo.buzz sebelum publish. Tulis pengecualian gambar di blog.clincoo.buzz.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme", "sourceSnippet": "MDN: prefers-color-scheme", "source2": "MDN: color-scheme", "source3": "web.dev: dark mode"}, "en": {"title": "Do Not Use filter: invert for Clincoo Dark Mode", "desc": "filter: invert(1) flips photos, logos, and charts. Color tokens and prefers-color-scheme keep the Clincoo brand correct.", "content": "<p class=\"mb-4\">Some drafts on editor.clincoo.buzz use filter: invert(1) hue-rotate(180deg) on body. The logo and product photos flip too.</p><p class=\"mb-4\">Real dark mode swaps background, text, and border tokens. Images stay intact unless a dark asset was prepared.</p><p class=\"mb-4\">invert also breaks focus contrast and form status colors. Success green can become an unrecognizable purple.</p><p class=\"mb-4\">If AI offers filter invert as a shortcut, reject it. Ask for CSS variables and a prefers-color-scheme media query.</p><p class=\"mb-4\">Compare light and dark preview on app.clincoo.buzz before publish. Note image exceptions on blog.clincoo.buzz.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme", "sourceSnippet": "MDN: prefers-color-scheme", "source2": "MDN: color-scheme", "source3": "web.dev: dark mode"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["darkmode"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["darkmode"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
