// Clincoo Blog — artikel env tambahan 2026-09-29
(function(){
  var extra = [
    {"id":"env-jangan-hardcode-host-api","langs":{"id":{"title":"Jangan Hardcode Host API Clincoo di Berkas Editor","desc":"Host yang tertulis di JS merusak pratinjau saat domain berubah. Baca dari env publik, bukan string tetap.","content":"<p class=\"mb-4\">Banyak proyek Clincoo menempel https://app.clincoo.buzz langsung di fetch. Saat pindah ke staging, setiap file harus diubah manual.</p><p class=\"mb-4\">Simpan host di variabel env publik, lalu baca sekali di modul konfigurasi editor.clincoo.buzz. File lain hanya mengimpor objek itu.</p><p class=\"mb-4\">Uji di pratinjau: ganti nilai env, muat ulang, pastikan request menuju host baru. Jika masih ke host lama, ada string yang terlewat.</p><p class=\"mb-4\">Minta AI mencari literal https di proyek. Jangan minta rewrite seluruh app.</p><p class=\"mb-4\">Clincoo di app.clincoo.buzz tetap sama; yang berubah hanya sumber host.</p>","source":"Clincoo","sourceUrl":"https://editor.clincoo.buzz/","sourceSnippet":"Editor resmi Clincoo","source2":"Clincoo App","source3":"Clincoo Blog"},"en":{"title":"Do Not Hardcode the Clincoo API Host in Editor Files","desc":"A host written in JS breaks preview when the domain changes. Read a public env value, not a fixed string.","content":"<p class=\"mb-4\">Many Clincoo projects paste https://app.clincoo.buzz straight into fetch. After a staging move, every file must change by hand.</p><p class=\"mb-4\">Store the host in a public env variable, then read it once in a config module on editor.clincoo.buzz. Other files only import that object.</p><p class=\"mb-4\">Test in preview: change the env value, reload, confirm requests hit the new host. If they still hit the old one, a literal remains.</p><p class=\"mb-4\">Ask AI to find https literals in the project. Do not ask it to rewrite the whole app.</p><p class=\"mb-4\">Clincoo on app.clincoo.buzz stays the same; only the host source changes.</p>","source":"Clincoo","sourceUrl":"https://editor.clincoo.buzz/","sourceSnippet":"Official Clincoo editor","source2":"Clincoo App","source3":"Clincoo Blog"}}},
    {"id":"env-pisahkan-kunci-preview-dan-produksi","langs":{"id":{"title":"Pisahkan Kunci Env Pratinjau dan Produksi Clincoo","desc":"Satu kunci untuk semua lingkungan membuat uji merusak data hidup. Buat pasangan env yang berbeda.","content":"<p class=\"mb-4\">Pratinjau Clincoo yang memakai kunci produksi menulis ke data pengguna sungguhan. Satu klik uji bisa merusak catatan live.</p><p class=\"mb-4\">Buat dua set: PREVIEW_ dan PROD_. Isi preview dengan sandbox. Jangan salin nilai produksi ke berkas lokal.</p><p class=\"mb-4\">Di editor.clincoo.buzz, tampilkan lencana lingkungan di pojok agar kamu sadar sedang uji atau live.</p><p class=\"mb-4\">Minta AI menandai pemakaian process.env tanpa membedakan lingkungan. Perbaiki satu modul konfigurasi dulu.</p><p class=\"mb-4\">Clincoo di app.clincoo.buzz aman jika kunci uji tidak pernah menyentuh produksi.</p>","source":"Clincoo","sourceUrl":"https://app.clincoo.buzz/","sourceSnippet":"Aplikasi Clincoo","source2":"Clincoo Editor","source3":"Clincoo Blog"},"en":{"title":"Split Clincoo Preview and Production Env Keys","desc":"One key for every environment lets tests touch live data. Create separate env pairs.","content":"<p class=\"mb-4\">A Clincoo preview that uses the production key writes to real user data. One test click can damage live records.</p><p class=\"mb-4\">Make two sets: PREVIEW_ and PROD_. Fill preview with a sandbox. Do not copy production values into a local file.</p><p class=\"mb-4\">On editor.clincoo.buzz, show an environment badge in the corner so you know test from live.</p><p class=\"mb-4\">Ask AI to flag process.env usage that does not distinguish environments. Fix one config module first.</p><p class=\"mb-4\">Clincoo on app.clincoo.buzz stays safe when test keys never touch production.</p>","source":"Clincoo","sourceUrl":"https://app.clincoo.buzz/","sourceSnippet":"Clincoo app","source2":"Clincoo Editor","source3":"Clincoo Blog"}}},
    {"id":"env-cek-missing-env-di-pratinjau","langs":{"id":{"title":"Cek Env Hilang di Pratinjau Clincoo sebelum Deploy","desc":"Variabel kosong baru ketahuan setelah rilis. Gagal cepat di pratinjau lebih murah.","content":"<p class=\"mb-4\">Halaman Clincoo tampak normal di editor, lalu fetch gagal di produksi karena env tidak terpasang di host.</p><p class=\"mb-4\">Tulis fungsi boot yang memuat daftar kunci wajib. Jika ada yang kosong, tampilkan banner di pratinjau, jangan diam.</p><p class=\"mb-4\">Samakan nama kunci di .env.example dan dashboard host. Bedanya satu huruf membuat nilai undefined.</p><p class=\"mb-4\">Tempel daftar kunci ke AI dan minta checklist uji. Jangan minta AI mengisi nilai rahasia.</p><p class=\"mb-4\">Clincoo di blog.clincoo.buzz dan app.clincoo.buzz lebih mudah di-debug jika env dicek sebelum rilis.</p>","source":"Clincoo","sourceUrl":"https://blog.clincoo.buzz/","sourceSnippet":"Clincoo Blog","source2":"Clincoo Editor","source3":"Clincoo App"},"en":{"title":"Check Missing Clincoo Env in Preview before Deploy","desc":"Empty variables often show up only after release. Failing fast in preview is cheaper.","content":"<p class=\"mb-4\">A Clincoo page looks fine in the editor, then fetch fails in production because the host never received the env.</p><p class=\"mb-4\">Write a boot function that loads a list of required keys. If any is empty, show a preview banner instead of staying silent.</p><p class=\"mb-4\">Keep key names identical in .env.example and the host dashboard. One letter off makes the value undefined.</p><p class=\"mb-4\">Paste the key list to AI and ask for a test checklist. Do not ask AI to fill secret values.</p><p class=\"mb-4\">Clincoo on blog.clincoo.buzz and app.clincoo.buzz is easier to debug when env is checked before release.</p>","source":"Clincoo","sourceUrl":"https://blog.clincoo.buzz/","sourceSnippet":"Clincoo Blog","source2":"Clincoo Editor","source3":"Clincoo App"}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["env"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["env"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
