// Clincoo Blog sourcemap extra 2026-09-30
(function(){
  var extra = [
    {id:'sourcemap-404-file-map-di-network',langs:{id:{title:'Perbaiki 404 File .map di Tab Network Clincoo',desc:'DevTools mencari berkas .map yang tidak ada. Stack tetap minified dan debug jadi lambat.',content:'<p class="mb-4">Di editor.clincoo.buzz, konsol menunjuk baris bundel minified. Tab Network menampilkan 404 untuk file .map.</p><p class="mb-4">Cek komentar sourceMappingURL di ujung berkas JS. Pastikan path relatif sesuai folder deploy.</p><p class="mb-4">Jangan unggah .map ke produksi publik. Aktifkan hanya di pratinjau debug Clincoo.</p><p class="mb-4">Tempel URL 404 dan cuplikan sourceMappingURL ke AI. Uji ulang di app.clincoo.buzz dan catat di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Fix 404 .map Files in the Clincoo Network Tab',desc:'DevTools looks for a missing .map file. The stack stays minified and debugging slows down.',content:'<p class="mb-4">On editor.clincoo.buzz, the console points at a minified bundle line. The Network tab shows 404 for the .map file.</p><p class="mb-4">Check the sourceMappingURL comment at the end of the JS file. Keep the relative path aligned with the deploy folder.</p><p class="mb-4">Do not upload .map files to public production. Enable them only on a Clincoo debug preview.</p><p class="mb-4">Paste the 404 URL and the sourceMappingURL snippet to AI. Retest on app.clincoo.buzz and note it on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'sourcemap-sourcescontent-tanpa-file-asli',langs:{id:{title:'Sertakan sourcesContent agar Peta Clincoo Tidak Butuh File Asli',desc:'Peta tanpa isi sumber gagal jika path lokal tidak ada di mesin lain.',content:'<p class="mb-4">Rekan membuka app.clincoo.buzz di laptop lain. DevTools minta file sumber yang hanya ada di folder kamu.</p><p class="mb-4">Di editor.clincoo.buzz, aktifkan sourcesContent saat membangun peta debug. Isi sumber tertanam di berkas .map.</p><p class="mb-4">Jangan andalkan path absolut Windows atau Mac. AI cukup melihat opsi bundler, bukan seluruh repo.</p><p class="mb-4">Uji di mesin bersih lalu tautkan langkahnya di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Include sourcesContent so Clincoo Maps Do Not Need Original Files',desc:'A map without embedded sources fails when another machine lacks the local paths.',content:'<p class="mb-4">A teammate opens app.clincoo.buzz on another laptop. DevTools asks for source files that only exist in your folder.</p><p class="mb-4">In editor.clincoo.buzz, enable sourcesContent when building a debug map. Source text is embedded in the .map file.</p><p class="mb-4">Do not rely on Windows or Mac absolute paths. AI only needs the bundler option, not the whole repo.</p><p class="mb-4">Test on a clean machine and link the steps on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'sourcemap-vite-dev-vs-build',langs:{id:{title:'Bedakan Source Map Mode Dev dan Build Clincoo',desc:'Peta di server dev tidak sama dengan keluaran build. Jangan debug produksi pakai asumsi dev.',content:'<p class="mb-4">Hot reload di editor.clincoo.buzz menampilkan baris asli. Setelah build, stack kembali ke bundel.</p><p class="mb-4">Set sourcemap: true hanya untuk pratinjau. Untuk rilis app.clincoo.buzz matikan atau pakai hidden source map internal.</p><p class="mb-4">Kirim cuplikan vite.config ke AI, bukan minta rewrite seluruh pipeline.</p><p class="mb-4">Catat mode yang dipakai di blog.clincoo.buzz agar tim tidak salah langkah.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Separate Clincoo Source Map Modes for Dev and Build',desc:'Maps on the dev server are not the same as build output. Do not debug production with dev assumptions.',content:'<p class="mb-4">Hot reload on editor.clincoo.buzz shows original lines. After a build, the stack points at the bundle again.</p><p class="mb-4">Set sourcemap: true only for previews. For an app.clincoo.buzz release, turn it off or use a hidden internal map.</p><p class="mb-4">Send the vite.config snippet to AI instead of asking for a full pipeline rewrite.</p><p class="mb-4">Document the mode on blog.clincoo.buzz so the team does not mix steps.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'sourcemap-cors-saat-load-map',langs:{id:{title:'Perbaiki CORS saat Browser Memuat Source Map Clincoo',desc:'Berkas .map di CDN lain ditolak. DevTools diam dan stack tetap minified.',content:'<p class="mb-4">JS Clincoo di CDN, berkas .map di origin lain. Konsol app.clincoo.buzz tidak memetakan baris.</p><p class="mb-4">Samakan origin atau kirim header CORS untuk .map. Jangan taruh peta di domain yang memblokir.</p><p class="mb-4">Di editor.clincoo.buzz uji Network: status 200 untuk .map, bukan blocked.</p><p class="mb-4">Tempel header gagal ke AI. Tulis hasil uji di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Fix CORS When the Browser Loads a Clincoo Source Map',desc:'A .map file on another CDN is rejected. DevTools stays quiet and the stack stays minified.',content:'<p class="mb-4">Clincoo JS sits on a CDN, the .map file on another origin. The app.clincoo.buzz console never remaps lines.</p><p class="mb-4">Use the same origin or send CORS headers for .map. Do not host maps on a domain that blocks them.</p><p class="mb-4">In editor.clincoo.buzz check Network: the .map should be 200, not blocked.</p><p class="mb-4">Paste the failing headers to AI. Write the test result on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'sourcemap-breakpoint-baris-geser',langs:{id:{title:'Perbaiki Breakpoint Clincoo yang Loncat ke Baris Salah',desc:'Peta usang membuat breakpoint mendarat di fungsi lain. Debug jadi menyesatkan.',content:'<p class="mb-4">Kamu menaruh breakpoint di handler simpan editor.clincoo.buzz. Eksekusi berhenti di helper lain.</p><p class="mb-4">Rebuild peta setelah mengubah sumber. Hard refresh agar browser tidak memakai .map lama.</p><p class="mb-4">Matikan cache DevTools saat menguji. Kirim screenshot Sources ke AI, bukan seluruh bundel.</p><p class="mb-4">Ulangi di app.clincoo.buzz sampai baris cocok, lalu catat di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Fix Clincoo Breakpoints that Jump to the Wrong Line',desc:'A stale map lands breakpoints in another function. Debugging becomes misleading.',content:'<p class="mb-4">You set a breakpoint on the save handler in editor.clincoo.buzz. Execution stops in a different helper.</p><p class="mb-4">Rebuild the map after changing sources. Hard-refresh so the browser does not keep an old .map.</p><p class="mb-4">Disable DevTools cache while testing. Send a Sources screenshot to AI, not the whole bundle.</p><p class="mb-4">Repeat on app.clincoo.buzz until the line matches, then note it on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['sourcemap']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['sourcemap'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
