// Clincoo Blog — artikel javascript tambahan 2026-10-02
(function(){
  var extra = [{id:"js-optional-chaining-hindari-null",langs:{id:{title:"Pakai Optional Chaining agar Akses Null tidak Melempar Error",desc:"Membaca properti dari respons yang belum ada menghasilkan TypeError. Optional chaining menghentikan rantai tanpa menyembunyikan bug lain.",content:"<p class=\"mb-4\">Di editor.clincoo.buzz, kode sering membaca data.user.name sebelum fetch selesai. Konsol lalu menampilkan cannot read properties of undefined.</p><p class=\"mb-4\">Pakai optional chaining hanya pada rantai yang memang boleh kosong, misalnya data?.user?.name. Jangan bungkus seluruh fungsi.</p><p class=\"mb-4\">Tetap tampilkan keadaan kosong di UI. Operator ini mencegah crash, bukan mengganti pesan belum ada data.</p><p class=\"mb-4\">Minta AI mengganti satu akses yang jatuh. Tolak menulis ulang modul jika stack hanya menunjuk satu baris.</p><p class=\"mb-4\">Uji di pratinjau app.clincoo.buzz dengan respons kosong dan respons lengkap. Clincoo menjalankan skrip yang kamu simpan, jadi kedua jalur harus aman.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Editor resmi Clincoo",source2:"Clincoo App",source3:"Clincoo Blog"},en:{title:"Use Optional Chaining so a Null Access does not Throw",desc:"Reading a property on a response that is not there yet throws a TypeError. Optional chaining stops the chain without hiding other bugs.",content:"<p class=\"mb-4\">In editor.clincoo.buzz, code often reads data.user.name before fetch finishes. The console then shows cannot read properties of undefined.</p><p class=\"mb-4\">Use optional chaining only on a chain that may be empty, such as data?.user?.name. Do not wrap the whole function.</p><p class=\"mb-4\">Still show an empty state in the UI. The operator prevents a crash; it does not replace a missing-data message.</p><p class=\"mb-4\">Ask the AI to replace the one access that throws. Refuse a module rewrite if the stack points at one line.</p><p class=\"mb-4\">Test in the app.clincoo.buzz preview with an empty response and a full response. Clincoo runs the script you save, so both paths must be safe.</p>",source:"Clincoo",sourceUrl:"https://editor.clincoo.buzz/",sourceSnippet:"Official Clincoo editor",source2:"Clincoo App",source3:"Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["javascript"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["javascript"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
