// Clincoo Blog — artikel performa tambahan 2026-10-02
(function(){
  var extra = [{"id": "performa-content-visibility-section-panjang", "langs": {"id": {"title": "Pakai content-visibility pada Section Panjang di Situs Clincoo", "desc": "Halaman panjang memaksa browser menghitung layout yang belum kelihatan. content-visibility: auto menunda kerja itu.", "content": "<p class=\"mb-4\">Halaman layanan atau dokumentasi di blog.clincoo.buzz dan situs klien sering punya banyak section di bawah lipatan. Browser tetap menghitung ukuran semuanya saat load.</p><p class=\"mb-4\">Pada section yang jauh di bawah, tambah content-visibility: auto dan contain-intrinsic-size agar scrollbar tidak meloncat. Jangan pakai pada hero atau konten LCP.</p><p class=\"mb-4\">Uji di DevTools Performance. Waktu rendering awal harus turun, teks hero tetap langsung terlihat. Jika tinggi perkiraan salah, halaman terasa melompat saat scroll.</p><p class=\"mb-4\">Ini bukan pengganti gambar lazy atau CSS yang ringan. Pakai setelah lebar gambar dan font sudah beres, khusus daftar atau blok yang panjang.</p>", "source": "web.dev content-visibility", "sourceUrl": "https://web.dev/articles/content-visibility", "sourceSnippet": "content-visibility: auto skips rendering offscreen content.", "source2": "MDN content-visibility", "source3": "Clincoo Blog"}, "en": {"title": "Use content-visibility on Long Sections of a Clincoo Site", "desc": "A long page forces the browser to lay out content that is not visible yet. content-visibility: auto defers that work.", "content": "<p class=\"mb-4\">Service or docs pages on blog.clincoo.buzz and client sites often have many sections below the fold. The browser still measures all of them on load.</p><p class=\"mb-4\">On sections far below, add content-visibility: auto and contain-intrinsic-size so the scrollbar does not jump. Do not use it on the hero or LCP content.</p><p class=\"mb-4\">Test in the DevTools Performance panel. Initial render time should drop, and hero text stays visible immediately. If the guessed height is wrong, the page jumps while scrolling.</p><p class=\"mb-4\">This does not replace lazy images or a light stylesheet. Use it after image dimensions and fonts are settled, and only on long lists or blocks.</p>", "source": "web.dev content-visibility", "sourceUrl": "https://web.dev/articles/content-visibility", "sourceSnippet": "content-visibility: auto skips rendering offscreen content.", "source2": "MDN content-visibility", "source3": "Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["performa"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["performa"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
