// Clincoo Blog typography extra 2026-10-01
(function(){
  var extra = [
    {"id": "typography-line-height-bacaan-panjang", "langs": {"id": {"title": "Naikkan Line-Height pada Teks Bacaan Panjang Clincoo", "desc": "Teks padat di kartu blog sulit dibaca di ponsel. Pisahkan line-height judul dan paragraf.", "content": "<p class=\"mb-4\">Banyak template Clincoo memakai line-height 1.2 untuk semua teks. Paragraf di blog.clincoo.buzz lalu terasa sesak di layar sempit.</p><p class=\"mb-4\">Di editor.clincoo.buzz, set heading ke 1.2–1.3 dan body ke 1.5–1.7. Jangan wariskan satu nilai dari body ke h1.</p><p class=\"mb-4\">Uji di pratinjau mobile: jika baris saling menempel, naikkan line-height body saja, bukan font-size global.</p><p class=\"mb-4\">Minta AI mengusulkan token tipografi, bukan rewrite CSS lengkap app.clincoo.buzz.</p><p class=\"mb-4\">Clincoo tetap memakai font merek; yang diubah hanya jarak baris bacaan.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Raise Line-Height on Long-Form Clincoo Text", "desc": "Dense text on blog cards is hard to read on a phone. Split heading and paragraph line-height.", "content": "<p class=\"mb-4\">Many Clincoo templates use line-height 1.2 for every text node. Paragraphs on blog.clincoo.buzz then feel cramped on a narrow screen.</p><p class=\"mb-4\">On editor.clincoo.buzz, set headings to 1.2–1.3 and body copy to 1.5–1.7. Do not inherit one value from body onto h1.</p><p class=\"mb-4\">Test in mobile preview: if lines stick together, raise body line-height only, not the global font-size.</p><p class=\"mb-4\">Ask AI for typography tokens, not a full CSS rewrite of app.clincoo.buzz.</p><p class=\"mb-4\">Clincoo keeps the brand font; only reading line gap changes.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}},
    {id:'typography-tabular-nums-harga',langs:{id:{title:'Pakai tabular-nums pada Harga dan Angka Clincoo',desc:'Angka proporsional membuat kolom harga bergeser saat nilai berubah. Angka tabular menjaga lebar tetap.',content:'<p class="mb-4">Di editor.clincoo.buzz, kartu harga meloncat saat 1 menjadi 11 karena glyph 1 lebih sempit.</p><p class="mb-4">Set font-variant-numeric: tabular-nums pada harga, kuantitas, dan nomor invoice. Jangan terapkan ke paragraf biasa.</p><p class="mb-4">Kirim cuplikan CSS kartu ke AI. Minta satu kelas .num, bukan ganti font merek.</p><p class="mb-4">Uji di app.clincoo.buzz dengan nilai 1, 8, dan 1000. Tulis aturan di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Use tabular-nums on Clincoo Prices and Figures',desc:'Proportional digits make price columns jump when values change. Tabular numbers keep width stable.',content:'<p class="mb-4">On editor.clincoo.buzz, a price card jumps when 1 becomes 11 because the 1 glyph is narrower.</p><p class="mb-4">Set font-variant-numeric: tabular-nums on prices, quantities, and invoice numbers. Do not apply it to body paragraphs.</p><p class="mb-4">Send the card CSS snippet to AI. Ask for one .num class, not a brand font change.</p><p class="mb-4">Test on app.clincoo.buzz with 1, 8, and 1000. Write the rule on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}},
    {id:'typography-hindari-all-caps-paragraf',langs:{id:{title:'Hindari All Caps pada Paragraf Panjang Clincoo',desc:'Huruf kapital penuh menurunkan kecepatan baca dan terasa seperti berteriak. Caps hanya untuk label pendek.',content:'<p class="mb-4">Beberapa hero di editor.clincoo.buzz memakai text-transform: uppercase pada seluruh lead. Di ponsel baris menjadi sulit dipindai.</p><p class="mb-4">Batasi caps pada badge, tombol, dan label 1–3 kata. Body tetap sentence case. Letter-spacing caps jangan berlebihan.</p><p class="mb-4">Tempel kelas hero ke AI. Minta turunkan transform, bukan ganti font-size global.</p><p class="mb-4">Baca nyaring pratinjau di app.clincoo.buzz. Catat aturan caps di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Avoid All Caps on Long Clincoo Paragraphs',desc:'Full capitals slow reading and feel like shouting. Caps belong on short labels only.',content:'<p class="mb-4">Some heroes on editor.clincoo.buzz use text-transform: uppercase on the whole lead. On a phone the lines are hard to scan.</p><p class="mb-4">Limit caps to badges, buttons, and 1–3 word labels. Body stays sentence case. Do not overdo letter-spacing on caps.</p><p class="mb-4">Paste the hero class to AI. Ask to drop the transform, not to change global font-size.</p><p class="mb-4">Read the preview aloud on app.clincoo.buzz. Write the caps rule on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['typography']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['typography'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
