// Clincoo Blog — artikel flexbox tambahan 2026-09-30
(function(){
  var extra = [
    {"id": "flexbox-gap-bukan-margin-anak", "langs": {"id": {"title": "Pakai gap Flexbox, Bukan Margin Anak di Clincoo", "desc": "Margin pada item flex sering pecah rata kiri-kanan. Gunakan gap pada kontainer.", "content": "<p class=\"mb-4\">Di editor.clincoo.buzz, baris tombol sering tidak rata karena margin-right pada anak terakhir masih ada. gap pada parent tidak menambah ruang di tepi.</p><p class=\"mb-4\">Set display:flex dan gap:0.75rem pada satu kelas kontainer. Hapus margin horizontal pada anak agar hitungan lebar konsisten.</p><p class=\"mb-4\">Cek DevTools: pilih parent, lihat flex overlay. Jika anak terdorong keluar, kurangi flex-basis atau izinkan wrap.</p><p class=\"mb-4\">Tempel aturan CSS yang gagal ke AI. Jangan minta AI menulis grid lengkap jika masalahnya hanya jarak antar tombol.</p><p class=\"mb-4\">Pratinjau hasil di app.clincoo.buzz dan blog.clincoo.buzz dengan lebar sempit supaya wrap terlihat sebelum rilis.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Use Flexbox gap, Not Child Margins in Clincoo", "desc": "Margins on flex items often break left-right alignment. Put gap on the container.", "content": "<p class=\"mb-4\">On editor.clincoo.buzz, button rows often misalign because the last child still has margin-right. gap on the parent does not add space on the edges.</p><p class=\"mb-4\">Set display:flex and gap:0.75rem on one container class. Remove horizontal margins on children so width math stays consistent.</p><p class=\"mb-4\">In DevTools select the parent and inspect the flex overlay. If children overflow, shrink flex-basis or allow wrap.</p><p class=\"mb-4\">Paste the failing CSS rule to AI. Do not ask AI for a full grid if the only issue is spacing between buttons.</p><p class=\"mb-4\">Preview on app.clincoo.buzz and blog.clincoo.buzz at a narrow width so wrap shows before release.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}},
    {"id": "flexbox-min-width-nol-item-teks", "langs": {"id": {"title": "Set min-width 0 pada Item Flex Clincoo yang Menyimpan Teks", "desc": "Item flex default min-width:auto menolak menyusut. Teks panjang mendorong layout keluar viewport.", "content": "<p class=\"mb-4\">Kartu judul panjang di editor.clincoo.buzz memaksa baris flex melebihi layar. Overlay DevTools menunjukkan item tidak boleh lebih kecil dari konten.</p><p class=\"mb-4\">Tambah min-width:0 dan overflow-wrap pada item yang memuat teks. Jangan andalkan flex-shrink saja.</p><p class=\"mb-4\">Tempel kelas item ke AI. Minta satu aturan, bukan rewrite layout. Uji 320px di app.clincoo.buzz.</p><p class=\"mb-4\">Catat pola ini di blog.clincoo.buzz agar judul panjang tidak merusak header.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Set min-width 0 on Clincoo Flex Items that Hold Text", "desc": "Flex items default to min-width:auto and refuse to shrink. Long text pushes the layout past the viewport.", "content": "<p class=\"mb-4\">A long title card on editor.clincoo.buzz forces the flex row past the screen. The DevTools overlay shows the item cannot shrink below its content.</p><p class=\"mb-4\">Add min-width:0 and overflow-wrap on the text item. Do not rely on flex-shrink alone.</p><p class=\"mb-4\">Paste the item class to AI. Ask for one rule, not a layout rewrite. Test 320px on app.clincoo.buzz.</p><p class=\"mb-4\">Record this pattern on blog.clincoo.buzz so long titles do not break the header.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}
  ,
    {"id": "flexbox-flex-1-basis-nol", "langs": {"id": {"title": "Pakai flex: 1 1 0 agar Kolom Clincoo Berbagi Ruang", "desc": "flex: 1 memakai basis konten, jadi kolom teks panjang menelan ruang. Basis 0 membagi sisa secara adil.", "content": "<p class=\"mb-4\">Di editor.clincoo.buzz, dua kolom dengan flex: 1 sering tidak sama karena basis otomatis mengikuti isi.</p><p class=\"mb-4\">Gunakan flex: 1 1 0 pada kedua anak, plus min-width: 0 jika ada teks panjang. Ruang bebas lalu dibagi rata.</p><p class=\"mb-4\">Jangan campur flex: 1 dan lebar piksel tetap pada saudara yang seharusnya setara. Itu menggandakan aturan.</p><p class=\"mb-4\">Cek overlay Flexbox di DevTools. Basis 0 tampak sebagai ruang yang tumbuh, bukan sebagai lebar konten.</p><p class=\"mb-4\">Uji di app.clincoo.buzz pada lebar 360px. Tulis pola ini di blog.clincoo.buzz agar layout tidak diulang asal.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/CSS/flex", "sourceSnippet": "flex adalah singkatan grow, shrink, dan basis.", "source2": "Clincoo Editor", "source3": "Clincoo Blog"}, "en": {"title": "Use flex: 1 1 0 so Clincoo Columns Share Space", "desc": "flex: 1 uses content basis, so a long text column swallows space. A basis of 0 splits free space evenly.", "content": "<p class=\"mb-4\">On editor.clincoo.buzz, two columns with flex: 1 are often unequal because the automatic basis follows the content.</p><p class=\"mb-4\">Use flex: 1 1 0 on both children, plus min-width: 0 if text is long. Free space is then shared equally.</p><p class=\"mb-4\">Do not mix flex: 1 and a fixed pixel width on siblings that should match. That doubles the rule.</p><p class=\"mb-4\">Check the Flexbox overlay in DevTools. A basis of 0 shows as growing space, not as content width.</p><p class=\"mb-4\">Test on app.clincoo.buzz at 360px. Write this pattern on blog.clincoo.buzz so layouts are not guessed again.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/CSS/flex", "sourceSnippet": "flex is shorthand for grow, shrink, and basis.", "source2": "Clincoo Editor", "source3": "Clincoo Blog"}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["flexbox"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["flexbox"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
