// Clincoo Blog search extra 2026-09-30
(function(){
  var extra = [
    {id:'search-batalkan-fetch-lama',langs:{id:{title:'Batalkan Fetch Cari Lama di Clincoo dengan AbortController',desc:'Query baru yang menumpuk request lama menampilkan hasil usang. Batalkan fetch sebelumnya sebelum kirim yang baru.',content:'<p class="mb-4">Di editor.clincoo.buzz, ketikan cepat membuat tiga fetch jalan bersamaan. Hasil yang terakhir tiba bukan selalu query terakhir.</p><p class="mb-4">Simpan satu AbortController per sesi cari. Abort signal lama sebelum fetch baru.</p><p class="mb-4">Tempel handler input ke AI, bukan seluruh modul search.</p><p class="mb-4">Uji di app.clincoo.buzz: ketik cepat lalu berhenti. Hasil harus cocok dengan query terakhir. Catat di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Cancel Stale Clincoo Search Fetches with AbortController',desc:'Stacked requests from fast typing show stale results. Abort the previous fetch before sending a new one.',content:'<p class="mb-4">On editor.clincoo.buzz, fast typing fires three fetches at once. The last response is not always the last query.</p><p class="mb-4">Keep one AbortController per search session. Abort the old signal before a new fetch.</p><p class="mb-4">Paste the input handler to AI, not the whole search module.</p><p class="mb-4">Test on app.clincoo.buzz: type quickly, then stop. Results must match the last query. Note it on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'search-simpan-query-terakhir',langs:{id:{title:'Simpan Query Cari Terakhir Clincoo di sessionStorage',desc:'Pengunjung yang kembali ke halaman kehilangan kata kunci. Simpan query singkat di sessionStorage, bukan cookie.',content:'<p class="mb-4">Di editor.clincoo.buzz, pengguna menutup hasil lalu kembali. Kotak cari kosong meski mereka baru mencari.</p><p class="mb-4">Simpan string query di sessionStorage saat submit atau debounce selesai. Isi ulang input saat halaman dimuat.</p><p class="mb-4">Jangan simpan PII. Batasi panjang. Minta AI menambah dua baris restore, bukan rewrite search.</p><p class="mb-4">Uji di app.clincoo.buzz: cari, pindah halaman, kembali. Query masih ada. Tulis langkah di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Persist the Last Clincoo Search Query in sessionStorage',desc:'Visitors who leave the page lose their keyword. Store a short query in sessionStorage, not a cookie.',content:'<p class="mb-4">On editor.clincoo.buzz, a user closes results then returns. The search box is empty even after a recent search.</p><p class="mb-4">Save the query string in sessionStorage when submit or debounce finishes. Restore the input on load.</p><p class="mb-4">Do not store PII. Cap the length. Ask AI for two restore lines, not a search rewrite.</p><p class="mb-4">Test on app.clincoo.buzz: search, leave, return. The query remains. Write the steps on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['search']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['search'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
