// Clincoo Blog — artikel modal tambahan 2026-10-01 WIB
(function(){
  var extra = [{"id": "modal-hindari-autofocus-di-ponsel", "langs": {"id": {"title": "Jangan Autofocus Input Modal Clincoo di Ponsel", "desc": "autofocus membuka keyboard dan mendorong dialog ke atas. Pindahkan fokus ke judul, bukan ke kolom, pada layar sempit.", "content": "<p class=\"mb-4\">Modal form di app.clincoo.buzz yang memakai autofocus langsung memunculkan keyboard. Tombol tutup sering tertutup.</p><p class=\"mb-4\">Pada lebar di bawah 640px, fokuskan heading dialog dengan tabindex=-1. Biarkan pengunjung mengetuk kolom sendiri.</p><p class=\"mb-4\">Di desktop, fokus ke kontrol pertama tetap masuk akal jika dialog hanya berisi satu aksi. Bedakan lewat matchMedia.</p><p class=\"mb-4\">Jangan minta AI menambah autofocus ke semua input. Sertakan lebar layar dan minta cabang ponsel versus desktop.</p><p class=\"mb-4\">Uji di pratinjau editor.clincoo.buzz dengan device toolbar. Pastikan Escape dan tombol tutup tetap terlihat.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog", "sourceSnippet": "MDN: dialog", "source2": "MDN: autofocus", "source3": "WAI-ARIA dialog pattern"}, "en": {"title": "Do Not Autofocus a Clincoo Modal Input on Phones", "desc": "autofocus opens the keyboard and pushes the dialog up. Move focus to the title, not the field, on narrow screens.", "content": "<p class=\"mb-4\">A form modal on app.clincoo.buzz that uses autofocus opens the keyboard immediately. The close button is often covered.</p><p class=\"mb-4\">Below 640px, focus the dialog heading with tabindex=-1. Let the visitor tap the field themselves.</p><p class=\"mb-4\">On desktop, focusing the first control still makes sense if the dialog has one action. Branch with matchMedia.</p><p class=\"mb-4\">Do not ask AI to add autofocus to every input. Include the viewport width and ask for a phone versus desktop branch.</p><p class=\"mb-4\">Test in the editor.clincoo.buzz preview with the device toolbar. Confirm Escape and the close button stay visible.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog", "sourceSnippet": "MDN: dialog", "source2": "MDN: autofocus", "source3": "WAI-ARIA dialog pattern"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["modal"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["modal"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
