// Clincoo Blog — artikel panduan tambahan 2026-10-02
(function(){
  var extra = [{"id": "panduan-minta-bantuan-ai-saat-stuck", "langs": {"id": {"title": "Cara Minta Bantuan AI saat Stuck di Editor Clincoo", "desc": "Chat yang hanya bilang tolong perbaiki jarang berhasil. Kirim gejala, file, cuplikan konsol, dan hasil yang diharapkan.", "content": "<p class=\"mb-4\">Saat macet di editor.clincoo.buzz, jangan menempel seluruh proyek. AI kehilangan konteks dan mengubah file yang tidak terkait.</p><p class=\"mb-4\">Tulis empat hal: apa yang Anda lakukan, apa yang terlihat, apa yang diharapkan, dan file mana yang sedang dibuka. Lampirkan satu pesan konsol, bukan tangkapan layar buram.</p><p class=\"mb-4\">Minta satu perubahan kecil dulu. Contoh: perbaiki selector yang gagal, jangan sekalian merapikan CSS seluruh halaman.</p><p class=\"mb-4\">Jalankan saran itu di pratinjau app.clincoo.buzz sebelum meminta langkah berikutnya. Jika gagal, balas dengan hasil baru, bukan prompt lama yang diulang.</p><p class=\"mb-4\">Simpan prompt yang berhasil di catatan blog.clincoo.buzz agar sesi berikutnya tidak mulai dari nol.</p>", "source": "Clincoo Editor", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Clincoo Editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "How to Ask AI for Help When You Are Stuck in the Clincoo Editor", "desc": "A chat that only says please fix this rarely works. Send the symptom, file, console snippet, and expected result.", "content": "<p class=\"mb-4\">When you are stuck in editor.clincoo.buzz, do not paste the whole project. AI loses context and edits unrelated files.</p><p class=\"mb-4\">Write four things: what you did, what you saw, what you expected, and which file is open. Attach one console message, not a blurry screenshot.</p><p class=\"mb-4\">Ask for one small change first. Example: fix the selector that failed, do not also restyle the whole page.</p><p class=\"mb-4\">Run that suggestion in the app.clincoo.buzz preview before asking for the next step. If it fails, reply with the new result instead of repeating the old prompt.</p><p class=\"mb-4\">Save prompts that worked in a note on blog.clincoo.buzz so the next session does not start from zero.</p>", "source": "Clincoo Editor", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Clincoo Editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["panduan"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["panduan"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
