// Clincoo Blog — artikel animasi tambahan 2026-10-01 WIB
(function(){
  var extra = [{"id": "animasi-contain-layout-saat-transform", "langs": {"id": {"title": "Isolasi Animasi Clincoo dengan contain, Bukan will-change Permanen", "desc": "will-change yang menempel terus memboroskan memori. contain: layout paint membatasi dampak transform tanpa menahan lapisan selamanya.", "content": "<p class=\"mb-4\">Di editor.clincoo.buzz, kartu yang di-hover sering diberi will-change: transform pada stylesheet utama. Lapisan itu tetap hidup meski elemen diam.</p><p class=\"mb-4\">Pakai contain: layout paint pada kartu yang beranimasi. Browser membatasi hitung ulang layout ke dalam kotak itu, bukan seluruh halaman.</p><p class=\"mb-4\">Pasang will-change hanya lewat kelas saat transisi mulai, lalu lepas di animationend atau transitionend. Jangan tulis will-change di aturan dasar.</p><p class=\"mb-4\">Jika AI menyarankan will-change pada semua elemen, tolak. Minta satu kelas pemicu dan contoh contain yang setara.</p><p class=\"mb-4\">Uji di pratinjau ponsel app.clincoo.buzz dengan CPU throttling. Catat pola yang tidak membuat jank ke blog.clincoo.buzz.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/CSS/contain", "sourceSnippet": "MDN: contain", "source2": "MDN: will-change", "source3": "web.dev: animations"}, "en": {"title": "Isolate Clincoo Animations with contain, Not a Permanent will-change", "desc": "A sticky will-change wastes memory. contain: layout paint limits transform cost without holding a layer forever.", "content": "<p class=\"mb-4\">On editor.clincoo.buzz, hovered cards often get will-change: transform in the main stylesheet. That layer stays alive even when the element is idle.</p><p class=\"mb-4\">Use contain: layout paint on cards that animate. The browser limits layout work to that box instead of the whole page.</p><p class=\"mb-4\">Add will-change only through a class when the transition starts, then remove it on animationend or transitionend. Do not put will-change on the base rule.</p><p class=\"mb-4\">If AI suggests will-change on every element, reject it. Ask for one trigger class and an equivalent contain example.</p><p class=\"mb-4\">Test in the app.clincoo.buzz phone preview with CPU throttling. Write the pattern that does not jank on blog.clincoo.buzz.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/CSS/contain", "sourceSnippet": "MDN: contain", "source2": "MDN: will-change", "source3": "web.dev: animations"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["animasi"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["animasi"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
