// Clincoo Blog — artikel cookie tambahan 2026-10-01 WIB
(function(){
  var extra = [{"id": "cookie-prefix-host-untuk-sesi", "langs": {"id": {"title": "Pakai Prefiks __Host- untuk Cookie Sesi Clincoo", "desc": "Prefiks __Host- menolak cookie tanpa Secure, tanpa Domain, dan path selain /. Itu mengurangi cookie sesi yang bisa ditimpa subdomain.", "content": "<p class=\"mb-4\">Cookie sesi di app.clincoo.buzz kadang disetel dengan Domain=.clincoo.buzz. Subdomain lain bisa menimpa nama yang sama.</p><p class=\"mb-4\">Nama __Host-session mewajibkan Secure, path=/, dan tanpa atribut Domain. Browser menolak set cookie jika salah satu syarat gagal.</p><p class=\"mb-4\">Jangan pakai prefiks ini untuk cookie yang memang harus dibaca subdomain. Untuk itu, SameSite dan Secure tetap wajib, tapi tanpa __Host-.</p><p class=\"mb-4\">Cek di DevTools, tab Application. Jika cookie tidak muncul, lihat baris Set-Cookie yang ditolak di Network.</p><p class=\"mb-4\">Minta AI hanya mengubah nama dan atribut cookie, bukan menulis ulang seluruh auth. Uji login di editor.clincoo.buzz setelahnya.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie", "sourceSnippet": "MDN: Set-Cookie", "source2": "MDN: cookie prefixes", "source3": "web.dev: same-site cookies"}, "en": {"title": "Use the __Host- Prefix for Clincoo Session Cookies", "desc": "The __Host- prefix rejects cookies without Secure, with a Domain attribute, or with a path other than /. That limits session cookies a subdomain can overwrite.", "content": "<p class=\"mb-4\">Session cookies on app.clincoo.buzz are sometimes set with Domain=.clincoo.buzz. Another subdomain can overwrite the same name.</p><p class=\"mb-4\">The name __Host-session requires Secure, path=/, and no Domain attribute. The browser rejects the cookie if any rule fails.</p><p class=\"mb-4\">Do not use this prefix for a cookie that a subdomain must read. SameSite and Secure still apply, but skip __Host-.</p><p class=\"mb-4\">Check DevTools, Application tab. If the cookie is missing, read the rejected Set-Cookie line in Network.</p><p class=\"mb-4\">Ask AI to change only the cookie name and attributes, not rewrite all auth. Test login on editor.clincoo.buzz afterward.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie", "sourceSnippet": "MDN: Set-Cookie", "source2": "MDN: cookie prefixes", "source3": "web.dev: same-site cookies"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["cookie"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["cookie"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
