// Clincoo Blog — artikel privacy extra2 2026-09-30
(function(){
  var extra = [
    {id:'privacy-referrer-policy-ketat',langs:{id:{title:'Setel Referrer-Policy Ketat di Situs Clincoo',desc:'URL draf atau token di query bisa bocor ke domain luar lewat header Referer.',content:'<p class="mb-4">Halaman di editor.clincoo.buzz yang menaut ke analitik atau font pihak ketiga mengirim Referer secara default.</p><p class="mb-4">Pakai referrer-policy: strict-origin-when-cross-origin atau stricter pada meta dan header host.</p><p class="mb-4">Jangan taruh token atau id draf di query string jika tautan bisa diklik ke luar.</p><p class="mb-4">Tempel head plus header ke AI. Minta satu kebijakan, bukan daftar 10 nilai yang membingungkan.</p><p class="mb-4">Clincoo di blog.clincoo.buzz dan app.clincoo.buzz menjaga URL internal tetap internal.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Set a Strict Referrer-Policy on Clincoo Sites',desc:'A draft URL or a token in the query can leak to a third-party host through the Referer header.',content:'<p class="mb-4">A page on editor.clincoo.buzz that links to third-party analytics or fonts sends Referer by default.</p><p class="mb-4">Use referrer-policy: strict-origin-when-cross-origin or stricter on both the meta tag and the host header.</p><p class="mb-4">Do not put a token or draft id in the query string if the link can be clicked outbound.</p><p class="mb-4">Paste the head plus headers to AI. Ask for one policy, not a confusing list of ten values.</p><p class="mb-4">Clincoo on blog.clincoo.buzz and app.clincoo.buzz keeps internal URLs internal.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'privacy-hapus-query-sensitif-dari-url',langs:{id:{title:'Hapus Query Sensitif dari URL Clincoo setelah Login',desc:'Token di ?access= tetap ada di history, log server, dan screenshot bilah alamat.',content:'<p class="mb-4">Alur auth yang mendarat di app.clincoo.buzz dengan token di query harus segera diganti ke history.replaceState tanpa parameter.</p><p class="mb-4">Cek document.referrer dan analytics: query ikut terekam jika tidak dipangkas.</p><p class="mb-4">Jangan bagikan URL pratinjau editor.clincoo.buzz yang masih memuat session di query.</p><p class="mb-4">Tempel lokasi URL plus kode router ke AI. Minta diff kecil, bukan rewrite auth.</p><p class="mb-4">Clincoo di blog.clincoo.buzz mengajarkan URL bersih sebagai bagian privasi, bukan hanya SEO.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Strip Sensitive Query Params from Clincoo URLs after Login',desc:'A token in ?access= stays in history, server logs, and address-bar screenshots.',content:'<p class="mb-4">An auth flow that lands on app.clincoo.buzz with a token in the query must immediately history.replaceState without the parameter.</p><p class="mb-4">Check document.referrer and analytics: the query is recorded if you do not strip it.</p><p class="mb-4">Do not share an editor.clincoo.buzz preview URL that still carries a session in the query.</p><p class="mb-4">Paste the URL location plus router code to AI. Ask for a small diff, not an auth rewrite.</p><p class="mb-4">Clincoo on blog.clincoo.buzz treats a clean URL as privacy work, not only SEO.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['privacy']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['privacy'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
