// Clincoo Blog timezone extra2 2026-09-30
(function(){
  var extra = [
    {id:'timezone-gettimezoneoffset-bukan-label',langs:{id:{title:'Jangan Andalkan getTimezoneOffset sebagai Label Zona Clincoo',desc:'Offset menit berubah saat DST. Label jadwal Clincoo harus memakai nama IANA, bukan angka dari Date.',content:'<p class="mb-4">Di editor.clincoo.buzz, menampilkan GMT+7 dari getTimezoneOffset terlihat benar di Januari dan salah setelah DST di zona klien.</p><p class="mb-4">Pakai Intl.DateTimeFormat().resolvedOptions().timeZone untuk nama zona. Offset hanya untuk hitung selisih sesaat.</p><p class="mb-4">Tempel nilai offset plus tanggal uji ke AI. Jangan minta rumus menit sepanjang tahun.</p><p class="mb-4">Samakan label di app.clincoo.buzz dan blog.clincoo.buzz sebelum rilis webinar.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Do not Rely on getTimezoneOffset as a Clincoo Zone Label',desc:'Minute offsets change with DST. Clincoo schedule labels need an IANA name, not a Date number.',content:'<p class="mb-4">On editor.clincoo.buzz, showing GMT+7 from getTimezoneOffset looks right in January and wrong after a client DST change.</p><p class="mb-4">Use Intl.DateTimeFormat().resolvedOptions().timeZone for the zone name. Use the offset only for a one-shot difference.</p><p class="mb-4">Paste the offset plus the test date to AI. Do not ask for a year-long minute formula.</p><p class="mb-4">Match labels on app.clincoo.buzz and blog.clincoo.buzz before a webinar ships.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'timezone-uji-dst-dua-tanggal',langs:{id:{title:'Uji Jadwal Clincoo pada Dua Tanggal di Zona DST',desc:'Satu tanggal di musim dingin tidak membuktikan jam musim panas. Checklist Clincoo butuh dua titik kalender.',content:'<p class="mb-4">Halaman countdown di app.clincoo.buzz lolos di Maret lalu mundur satu jam saat zona klien masuk DST.</p><p class="mb-4">Pilih satu tanggal Januari dan satu Juli di zona uji. Bandingkan output Intl dengan zona Asia/Jakarta yang tidak DST.</p><p class="mb-4">Kirim kedua hasil ke AI jika selisih tidak tetap. Jangan minta toggle DST palsu di kode produksi.</p><p class="mb-4">Catat langkah ini di editor.clincoo.buzz agar blog.clincoo.buzz punya checklist yang sama.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Test Clincoo Schedules on Two Dates in a DST Zone',desc:'One winter date does not prove summer time. The Clincoo checklist needs two calendar points.',content:'<p class="mb-4">A countdown page on app.clincoo.buzz passed in March then slipped one hour when the client zone entered DST.</p><p class="mb-4">Pick one January date and one July date in the test zone. Compare Intl output with Asia/Jakarta, which has no DST.</p><p class="mb-4">Send both results to AI if the gap is not steady. Do not ask for a fake DST toggle in production code.</p><p class="mb-4">Record the steps on editor.clincoo.buzz so blog.clincoo.buzz shares the same checklist.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'timezone-satu-sumber-waktu-server',langs:{id:{title:'Pakai Satu Sumber Waktu Server untuk Acara Clincoo',desc:'Jam perangkat klien bisa salah. Acara Clincoo harus dihitung dari UTC server, lalu diformat lokal.',content:'<p class="mb-4">Di editor.clincoo.buzz, countdown yang memakai Date.now() klien mundur jika jam laptop pengguna tidak sinkron.</p><p class="mb-4">Ambil now dari server atau header Date, simpan target dalam UTC, render sisa detik di perangkat.</p><p class="mb-4">Tempel selisih server versus klien ke AI. Jangan minta sinkron NTP di browser.</p><p class="mb-4">Uji di app.clincoo.buzz dengan jam OS digeser sengaja, lalu cek blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Use One Server Clock Source for Clincoo Events',desc:'A client device clock can be wrong. Clincoo events should be computed from server UTC, then formatted locally.',content:'<p class="mb-4">On editor.clincoo.buzz, a countdown that uses the client Date.now() slips if the user laptop clock is off.</p><p class="mb-4">Read now from the server or the Date header, store the target in UTC, and render remaining seconds on the device.</p><p class="mb-4">Paste the server versus client gap to AI. Do not ask for NTP sync in the browser.</p><p class="mb-4">Test on app.clincoo.buzz with the OS clock shifted on purpose, then check blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'timezone-countdown-dari-utc',langs:{id:{title:'Hitung Countdown Clincoo dari UTC, Bukan String Lokal',desc:'Sisa detik harus dikurangi dari instansi UTC. String lokal membuat countdown loncat saat zona berubah.',content:'<p class="mb-4">Timer di app.clincoo.buzz meloncat 7 jam setelah pengguna ganti zona OS di tengah sesi.</p><p class="mb-4">Parse target sebagai Instant UTC. Kurangi dengan Date.now() atau waktu server. Format tampilan terpisah.</p><p class="mb-4">Tempel target ISO dan sisa detik yang salah ke AI. Jangan minta interval per zona.</p><p class="mb-4">Pratinjau di editor.clincoo.buzz lalu bagikan rumus singkat di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Compute Clincoo Countdowns from UTC, Not Local Strings',desc:'Remaining seconds must subtract from a UTC instant. Local strings make the countdown jump when the zone changes.',content:'<p class="mb-4">A timer on app.clincoo.buzz jumped 7 hours after the user changed the OS zone mid-session.</p><p class="mb-4">Parse the target as a UTC instant. Subtract Date.now() or server time. Format the display separately.</p><p class="mb-4">Paste the ISO target and the wrong remaining seconds to AI. Do not ask for a per-zone interval.</p><p class="mb-4">Preview on editor.clincoo.buzz then share the short formula on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'timezone-datetime-local-ke-utc',langs:{id:{title:'Konversi input datetime-local ke UTC sebelum Simpan Clincoo',desc:'Nilai datetime-local tanpa zona. Simpan ke backend Clincoo sebagai ISO UTC agar tidak bergeser.',content:'<p class="mb-4">Form jadwal di editor.clincoo.buzz mengirim 2026-09-30T19:00 tanpa Z. Server membaca sebagai UTC dan acara mundur.</p><p class="mb-4">Baca value, gabungkan dengan timeZone pengguna, lalu toISOString sebelum fetch ke app.clincoo.buzz.</p><p class="mb-4">Tempel payload form plus zona perangkat ke AI. Jangan minta parser datetime-local custom.</p><p class="mb-4">Uji satu slot WIB dan satu slot zona lain, dokumentasikan di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Convert datetime-local Input to UTC before Saving Clincoo',desc:'A datetime-local value has no zone. Store it on the Clincoo backend as ISO UTC so it does not shift.',content:'<p class="mb-4">A schedule form on editor.clincoo.buzz sends 2026-09-30T19:00 without Z. The server reads UTC and the event slips.</p><p class="mb-4">Read the value, combine it with the user timeZone, then call toISOString before fetch to app.clincoo.buzz.</p><p class="mb-4">Paste the form payload plus the device zone to AI. Do not ask for a custom datetime-local parser.</p><p class="mb-4">Test one WIB slot and one other-zone slot, then document it on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['timezone']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['timezone'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
