// Clincoo Blog — artikel git tambahan 2026-09-29
(function(){
  var extra = [{"id": "git-status-sebelum-pindah-cabang", "langs": {"id": {"title": "Jalankan git status Sebelum Pindah Cabang", "desc": "Pindah cabang dengan file kotor mencampur draf Clincoo ke fitur lain. Cek status dulu, simpan atau commit.", "content": "<p class=\"mb-4\">Sebelum checkout di proyek yang akan diunggah ke app.clincoo.buzz, ketik git status. File merah adalah pekerjaan yang belum masuk commit.</p><p class=\"mb-4\">Jika pekerjaan belum selesai, git stash push -m 'draf hero' atau commit di cabang saat ini. Jangan pindah sambil membawa diff acak.</p><p class=\"mb-4\">Setelah pindah, status harus bersih kecuali file yang memang di-ignore. Kalau masih ada sisa, Anda membawa perubahan lintas fitur.</p><p class=\"mb-4\">Kalau AI menyarankan checkout -f, tolak. Perintah itu membuang suntingan di editor.clincoo.buzz tanpa konfirmasi.</p><p class=\"mb-4\">Clincoo di blog.clincoo.buzz mengikuti ritme yang sama: lihat status, simpan niat, baru ganti konteks.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Run git status Before Switching Branches", "desc": "Switching branches with dirty files mixes a Clincoo draft into another feature. Check status first, then stash or commit.", "content": "<p class=\"mb-4\">Before checkout on a project you will upload to app.clincoo.buzz, type git status. Red files are work that is not committed yet.</p><p class=\"mb-4\">If the work is unfinished, git stash push -m 'hero draft' or commit on the current branch. Do not switch while carrying a random diff.</p><p class=\"mb-4\">After you switch, status should be clean except ignored files. Leftover files mean you carried changes across features.</p><p class=\"mb-4\">If AI suggests checkout -f, refuse. That command drops edits from editor.clincoo.buzz without asking.</p><p class=\"mb-4\">Clincoo on blog.clincoo.buzz follows the same rhythm: read status, save intent, then change context.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["git"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["git"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
