// Clincoo Blog — artikel pwa tambahan 2026-10-02
(function(){
  var extra = [{"id": "pwa-orientation-any-agar-hp-tidak-terkunci", "langs": {"id": {"title": "Set orientation any agar PWA Clincoo Tidak Mengunci Layar HP", "desc": "Manifest yang memaksa portrait mengunci situs saat pengguna memutar HP. Untuk situs konten, biarkan any.", "content": "<p class=\"mb-4\">Manifest PWA di situs Clincoo kadang menyalin orientation: portrait dari contoh aplikasi game. Situs blog atau company profile lalu tidak bisa dibaca landscape.</p><p class=\"mb-4\">Untuk situs konten, pakai orientation: any atau hapus field itu. Browser mengikuti orientasi perangkat. Portrait-primary hanya masuk akal untuk alur yang memang dirancang satu arah.</p><p class=\"mb-4\">Uji setelah install di Chrome Android: buka dari ikon layar utama, putar HP, pastikan layout tidak terpotong. CSS tetap butuh media query, manifest tidak menggantikan responsive.</p><p class=\"mb-4\">Jangan ubah orientation setelah pengguna sudah memasang aplikasi tanpa menjelaskan. Perubahan manifest bisa butuh install ulang agar terlihat.</p>", "source": "MDN Web App Manifest orientation", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/Manifest/reference/orientation", "sourceSnippet": "orientation sets the default orientation for the web app.", "source2": "web.dev Add a web app manifest", "source3": "Clincoo App"}, "en": {"title": "Set orientation to any so a Clincoo PWA Does Not Lock the Phone Screen", "desc": "A manifest that forces portrait locks the site when the user rotates the phone. For a content site, leave it as any.", "content": "<p class=\"mb-4\">A Clincoo site PWA manifest sometimes copies orientation: portrait from a game sample. A blog or company profile then cannot be read in landscape.</p><p class=\"mb-4\">For a content site, use orientation: any or omit the field. The browser follows the device. portrait-primary only makes sense for a flow designed for one direction.</p><p class=\"mb-4\">Test after install on Chrome Android: open from the home-screen icon, rotate the phone, and confirm the layout is not clipped. CSS still needs media queries; the manifest does not replace responsive layout.</p><p class=\"mb-4\">Do not change orientation after users have installed the app without saying so. A manifest change may need a reinstall before it shows up.</p>", "source": "MDN Web App Manifest orientation", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/Manifest/reference/orientation", "sourceSnippet": "orientation sets the default orientation for the web app.", "source2": "web.dev Add a web app manifest", "source3": "Clincoo App"}}},
  {"id": "pwa-konfirmasi-sebelum-skipwaiting", "langs": {"id": {"title": "Konfirmasi sebelum skipWaiting agar isian PWA tidak hilang", "desc": "skipWaiting langsung mengganti service worker dan bisa memuat ulang halaman di tengah isian. Minta konfirmasi dulu.", "content": "<p class=\"mb-4\">Di editor.clincoo.buzz, service worker baru sering memanggil skipWaiting begitu terpasang. Halaman yang sedang diisi lalu ikut memuat ulang.</p><p class=\"mb-4\">Tampilkan banner versi baru, jangan panggil skipWaiting di dalam install. Simpan draf form ke memori atau IndexedDB sebelum pengguna setuju.</p><p class=\"mb-4\">Setelah pengguna menekan Muat ulang, baru kirim pesan ke worker agar skipWaiting, lalu dengarkan controllerchange sekali saja.</p><p class=\"mb-4\">Minta AI menjelaskan beda skipWaiting dan clients.claim. Tolak cuplikan yang memuat ulang tanpa tombol.</p><p class=\"mb-4\">Uji di pratinjau app.clincoo.buzz dengan isian setengah jalan. Versi baru tidak boleh menghapus teks yang belum dikirim.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Confirm before skipWaiting so a PWA form is not lost", "desc": "skipWaiting swaps the service worker immediately and can reload a page mid-form. Ask for confirmation first.", "content": "<p class=\"mb-4\">On editor.clincoo.buzz, a new service worker often calls skipWaiting as soon as it installs. A page with an open form then reloads.</p><p class=\"mb-4\">Show a new-version banner. Do not call skipWaiting inside install. Save the form draft to memory or IndexedDB before the user agrees.</p><p class=\"mb-4\">After the user presses Reload, send a message so the worker can skipWaiting, then listen for controllerchange only once.</p><p class=\"mb-4\">Ask AI to explain skipWaiting versus clients.claim. Refuse a snippet that reloads with no button.</p><p class=\"mb-4\">Test on the app.clincoo.buzz preview with a half-filled form. A new version must not wipe text that was not submitted.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}
];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["pwa"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["pwa"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
