// Clincoo Blog — artikel console tambahan 2026-09-30
(function(){
  var extra = [
    {"id": "console-baca-stack-bukan-satu-baris", "langs": {"id": {"title": "Baca Stack Console, Bukan Hanya Satu Baris Merah", "desc": "Pesan error tanpa stack menyesatkan. Buka baris sumber di DevTools sebelum mengubah file Clincoo.", "content": "<p class=\"mb-4\">Banyak orang menyalin hanya teks Uncaught TypeError ke AI. Tanpa stack, AI menebak file yang salah di editor.clincoo.buzz.</p><p class=\"mb-4\">Klik segitiga di Console, buka frame pertama yang milik kode Anda, bukan milik pustaka. Catat nama file dan nomor baris.</p><p class=\"mb-4\">Jika sumber menunjuk berkas minify, hidupkan sourcemap di pratinjau. Jangan mengedit berkas hasil build.</p><p class=\"mb-4\">Tempel stack lengkap ke AI dan minta satu perbaikan. Jangan minta rewrite seluruh app.clincoo.buzz.</p><p class=\"mb-4\">Clincoo di blog.clincoo.buzz lebih cepat diperbaiki bila stack dibaca sebelum kode diubah.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Read the Console Stack, Not Only the Red Line", "desc": "An error message without a stack misleads you. Open the source line in DevTools before you change a Clincoo file.", "content": "<p class=\"mb-4\">Many people paste only Uncaught TypeError into AI. Without a stack, AI guesses the wrong file on editor.clincoo.buzz.</p><p class=\"mb-4\">Expand the Console row, open the first frame that belongs to your code, not a library. Note the file name and line number.</p><p class=\"mb-4\">If the source points at a minified file, enable sourcemaps in preview. Do not edit the build output.</p><p class=\"mb-4\">Paste the full stack to AI and ask for one fix. Do not ask it to rewrite all of app.clincoo.buzz.</p><p class=\"mb-4\">Clincoo on blog.clincoo.buzz is faster to repair when you read the stack before you change code.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}},
    {"id": "console-filter-log-pihak-ketiga", "langs": {"id": {"title": "Saring Log Pihak Ketiga di Console Clincoo", "desc": "Pixel iklan dan widget chat memenuhi Console. Saring domain sendiri sebelum debug.", "content": "<p class=\"mb-4\">Di editor.clincoo.buzz, Console penuh peringatan dari analitik. Error Clincoo tenggelam.</p><p class=\"mb-4\">Pakai kotak filter Console dengan nama berkas halaman Anda. Centang Hide network atau saring level Error saat mencari crash.</p><p class=\"mb-4\">Jangan matikan semua log. Simpan satu console.error di jalur gagal fetch. Tempel hanya baris milik kode Anda ke AI.</p><p class=\"mb-4\">Uji ulang di app.clincoo.buzz dengan filter aktif. Tulis langkah saring di blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Filter Third-Party Logs in the Clincoo Console", "desc": "Ad pixels and chat widgets flood the Console. Filter to your own domain before you debug.", "content": "<p class=\"mb-4\">On editor.clincoo.buzz, the Console fills with analytics warnings. The Clincoo error drowns.</p><p class=\"mb-4\">Use the Console filter box with your page file name. Check Hide network or filter to Error when hunting a crash.</p><p class=\"mb-4\">Do not mute every log. Keep one console.error on the failed fetch path. Paste only lines from your code to AI.</p><p class=\"mb-4\">Retest on app.clincoo.buzz with the filter on. Write the filter steps on blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}
  ,
    {"id": "console-table-untuk-objek", "langs": {"id": {"title": "Tampilkan Objek di console.table, Bukan console.log Mentah", "desc": "Daftar objek yang di-log mentah sulit dibandingkan. console.table merapikan kolom sebelum Anda minta bantuan AI.", "content": "<p class=\"mb-4\">Di editor.clincoo.buzz, console.log pada array objek sering tampil sebagai [Object] yang harus diklik satu per satu.</p><p class=\"mb-4\">Ganti dengan console.table(rows) untuk melihat kolom id, status, dan pesan dalam satu grid.</p><p class=\"mb-4\">Batasi kolom: console.table(rows, ['id','status']). Jangan log seluruh payload yang berisi token.</p><p class=\"mb-4\">Salin tabel itu ke chat AI bersama langkah reproduksi. Jangan tempel objek melingkar yang gagal di-stringify.</p><p class=\"mb-4\">Hapus log tabel sebelum rilis ke app.clincoo.buzz. Simpan pola ini di blog.clincoo.buzz agar debug tidak berisik.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/API/console/table_static", "sourceSnippet": "console.table menampilkan data tabular di konsol.", "source2": "Clincoo Editor", "source3": "Clincoo Blog"}, "en": {"title": "Show Objects with console.table, Not a Raw console.log", "desc": "A raw log of object lists is hard to compare. console.table lines up columns before you ask AI for help.", "content": "<p class=\"mb-4\">On editor.clincoo.buzz, console.log of an object array often shows [Object] that you must expand one by one.</p><p class=\"mb-4\">Switch to console.table(rows) to see id, status, and message columns in one grid.</p><p class=\"mb-4\">Limit columns: console.table(rows, ['id','status']). Do not log a full payload that contains a token.</p><p class=\"mb-4\">Copy that table into the AI chat with the repro steps. Do not paste a circular object that fails to stringify.</p><p class=\"mb-4\">Remove the table log before release to app.clincoo.buzz. Keep this pattern on blog.clincoo.buzz so debugging stays quiet.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/API/console/table_static", "sourceSnippet": "console.table displays tabular data in the console.", "source2": "Clincoo Editor", "source3": "Clincoo Blog"}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["console"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["console"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
