(function(){
  var extra = [{"id": "event-passive-listener-untuk-scroll", "langs": {"id": {"title": "Pasang Listener Scroll secara Passive", "desc": "Listener scroll yang bukan passive memaksa browser menunggu preventDefault dan membuat geser terasa macet.", "content": "<p class=\"mb-4\">Di editor.clincoo.buzz cari addEventListener untuk scroll, wheel, atau touchmove. Jika handler tidak pernah memanggil preventDefault, tambahkan opsi passive true.</p><p class=\"mb-4\">Jangan menandai passive lalu tetap memanggil preventDefault. Browser mengabaikan panggilan itu dan konsol memberi peringatan.</p><p class=\"mb-4\">Untuk menutup menu saat scroll, cukup setel state. Tidak perlu membatalkan scroll halaman.</p><p class=\"mb-4\">Uji di ponsel pada app.clincoo.buzz. Geser harus tetap mengikuti jari, bukan menunggu frame berikutnya.</p><p class=\"mb-4\">Minta AI menandai listener yang aman dijadikan passive. Tempel fungsi handler, bukan seluruh bundel.</p><p class=\"mb-4\">Catat pengecualian di blog.clincoo.buzz, misalnya kanvas yang memang harus menelan event wheel.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener", "sourceSnippet": "passive listener option", "source2": "MDN: addEventListener", "source3": "Clincoo Editor"}, "en": {"title": "Attach Scroll Listeners as Passive", "desc": "A non-passive scroll listener forces the browser to wait for preventDefault and makes swipes feel stuck.", "content": "<p class=\"mb-4\">In editor.clincoo.buzz find addEventListener for scroll, wheel, or touchmove. If the handler never calls preventDefault, add the passive true option.</p><p class=\"mb-4\">Do not mark it passive and still call preventDefault. The browser ignores the call and the console warns.</p><p class=\"mb-4\">To close a menu on scroll, set state. You do not need to cancel page scrolling.</p><p class=\"mb-4\">Test on a phone at app.clincoo.buzz. The swipe should follow the finger, not wait for the next frame.</p><p class=\"mb-4\">Ask AI to mark listeners that are safe to make passive. Paste the handler function, not the whole bundle.</p><p class=\"mb-4\">Note exceptions on blog.clincoo.buzz, such as a canvas that really must consume the wheel event.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener", "sourceSnippet": "passive listener option", "source2": "MDN: addEventListener", "source3": "Clincoo Editor"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['event']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['event'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
