// Clincoo Blog — artikel storage tambahan 2026-09-29
(function(){
  var extra = [{"id": "storage-cek-kuota-localstorage", "langs": {"id": {"title": "Cek Kuota localStorage Sebelum Menyimpan Draf Clincoo", "desc": "QuotaExceededError muncul diam-diam. Ukur ukuran JSON sebelum setItem.", "content": "<p class=\"mb-4\">Draf di editor.clincoo.buzz bisa pecah saat setItem melempar QuotaExceededError. Bungkus dalam try/catch dan tampilkan pesan jelas.</p><p class=\"mb-4\">Hitung JSON.stringify(data).length sebelum menulis. Jika mendekati beberapa megabyte, pindahkan ke IndexedDB.</p><p class=\"mb-4\">Jangan simpan base64 gambar besar di localStorage. Simpan referensi berkas, bukan payload penuh.</p><p class=\"mb-4\">Tempel stack QuotaExceededError ke AI plus perkiraan ukuran. Jangan minta AI perbesar storage.</p><p class=\"mb-4\">App.clincoo.buzz dan blog.clincoo.buzz mengikuti batas yang sama: teks pendek di localStorage, aset besar di tempat lain.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Check localStorage Quota Before Saving a Clincoo Draft", "desc": "QuotaExceededError appears quietly. Measure JSON size before setItem.", "content": "<p class=\"mb-4\">Drafts on editor.clincoo.buzz can break when setItem throws QuotaExceededError. Wrap it in try/catch and show a clear message.</p><p class=\"mb-4\">Measure JSON.stringify(data).length before writing. If you near a few megabytes, move to IndexedDB.</p><p class=\"mb-4\">Do not store large base64 images in localStorage. Store a file reference, not the full payload.</p><p class=\"mb-4\">Paste the QuotaExceededError stack and an estimated size to AI. Do not ask AI to enlarge storage.</p><p class=\"mb-4\">App.clincoo.buzz and blog.clincoo.buzz follow the same limit: short text in localStorage, large assets elsewhere.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["storage"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["storage"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
