(function(){
  var extra = [{"id": "email-header-list-unsubscribe", "langs": {"id": {"title": "Tambahkan Header List-Unsubscribe pada Email Clincoo", "desc": "Klien email menampilkan berhenti berlangganan jika header List-Unsubscribe ada dan URL-nya benar.", "content": "<p class=\"mb-4\">Di template email editor.clincoo.buzz tambahkan header List-Unsubscribe yang menunjuk ke URL berhenti di app.clincoo.buzz, plus mailto cadangan.</p><p class=\"mb-4\">URL harus one-click dan tidak meminta login jika token sudah ada di tautan. Jangan arahkan ke halaman marketing.</p><p class=\"mb-4\">Sertakan tautan yang sama di kaki email HTML dan di bagian teks biasa. Header saja tidak cukup untuk klien lama.</p><p class=\"mb-4\">Uji kirim ke kotak Anda. Pastikan tombol berhenti muncul dan tidak 404.</p><p class=\"mb-4\">Minta AI menyusun contoh header, bukan menempel daftar penerima. Jangan kirim alamat asli ke chat.</p><p class=\"mb-4\">Catat format header di blog.clincoo.buzz supaya kampanye berikutnya tidak mengulang email tanpa jalan keluar.</p>", "source": "RFC 2369", "sourceUrl": "https://www.rfc-editor.org/rfc/rfc2369", "sourceSnippet": "List-Unsubscribe header", "source2": "RFC 2369", "source3": "Clincoo App"}, "en": {"title": "Add a List-Unsubscribe Header to Clincoo Email", "desc": "Mail clients show unsubscribe when the List-Unsubscribe header exists and its URL is real.", "content": "<p class=\"mb-4\">In the editor.clincoo.buzz email template add a List-Unsubscribe header pointing at an unsubscribe URL on app.clincoo.buzz, plus a mailto fallback.</p><p class=\"mb-4\">The URL should be one-click and should not ask for login if the token is already in the link. Do not send people to a marketing page.</p><p class=\"mb-4\">Include the same link in the HTML footer and in the plain-text part. The header alone is not enough for older clients.</p><p class=\"mb-4\">Send a test to your own inbox. Confirm the unsubscribe control appears and does not 404.</p><p class=\"mb-4\">Ask AI to draft the header example, not to paste the recipient list. Do not send real addresses into chat.</p><p class=\"mb-4\">Record the header format on blog.clincoo.buzz so the next campaign does not ship mail with no way out.</p>", "source": "RFC 2369", "sourceUrl": "https://www.rfc-editor.org/rfc/rfc2369", "sourceSnippet": "List-Unsubscribe header", "source2": "RFC 2369", "source3": "Clincoo App"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['email']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['email'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
