// Clincoo Blog — artikel responsive tambahan 2026-10-02
(function(){
  var extra = [{"id": "responsive-font-16px-input-cegah-zoom", "langs": {"id": {"title": "Set Font Input 16px agar iOS Tidak Zoom di Form Clincoo", "desc": "Input di bawah 16px membuat Safari iOS memperbesar halaman saat fokus. Form Clincoo jadi bergeser dan sulit ditutup.", "content": "<p class=\"mb-4\">Form di editor.clincoo.buzz sering memakai font 14px agar muat di kartu. Di iPhone, fokus pada input memicu zoom otomatis.</p><p class=\"mb-4\">Set font-size minimal 16px pada input, select, dan textarea. Jangan memaksa user-scalable=no di viewport. Itu menghalangi pembesaran yang dibutuhkan pengguna.</p><p class=\"mb-4\">Jika label terasa besar, kecilkan label, bukan field. Ukuran sentuh tetap nyaman dan halaman tidak meloncat.</p><p class=\"mb-4\">Uji di pratinjau app.clincoo.buzz dengan mode perangkat, lalu di ponsel asli: ketuk input, pastikan skala halaman tidak berubah.</p><p class=\"mb-4\">Tempel aturan CSS input ke AI dan minta hanya menaikkan font field. Jangan minta mengunci viewport.</p>", "source": "Clincoo Editor", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Clincoo Editor", "source2": "Clincoo App", "source3": "MDN Web Docs"}, "en": {"title": "Set Input Font to 16px so iOS Does Not Zoom a Clincoo Form", "desc": "Inputs under 16px make iOS Safari zoom the page on focus. The Clincoo form shifts and is hard to dismiss.", "content": "<p class=\"mb-4\">Forms in editor.clincoo.buzz often use 14px type so they fit a card. On iPhone, focusing an input triggers automatic zoom.</p><p class=\"mb-4\">Set font-size to at least 16px on input, select, and textarea. Do not force user-scalable=no on the viewport. That blocks zoom people need.</p><p class=\"mb-4\">If the label feels large, shrink the label, not the field. Touch size stays comfortable and the page does not jump.</p><p class=\"mb-4\">Test in the app.clincoo.buzz preview device mode, then on a real phone: tap an input and confirm the page scale does not change.</p><p class=\"mb-4\">Paste the input CSS into AI and ask only to raise the field font. Do not ask it to lock the viewport.</p>", "source": "Clincoo Editor", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Clincoo Editor", "source2": "Clincoo App", "source3": "MDN Web Docs"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["responsive"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["responsive"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
