// Clincoo Blog — artikel logging tambahan 2026-09-30
(function(){
  var extra = [{"id": "logging-jangan-log-di-loop-hot", "langs": {"id": {"title": "Jangan console.log di Loop Hot Skrip Clincoo", "desc": "Log di dalam requestAnimationFrame atau listener scroll membuat Console macet dan menyembunyikan error asli.", "content": "<p class=\"mb-4\">Di editor.clincoo.buzz, log di loop render atau scroll membanjiri Console sampai error penting terdorong ke atas.</p><p class=\"mb-4\">Pindahkan log ke cabang yang jarang: setelah aksi pengguna, atau di belakang flag debug yang mati di produksi app.clincoo.buzz.</p><p class=\"mb-4\">Jika harus mengamati loop, log setiap N frame atau sekali saat nilai berubah. Jangan log objek DOM utuh.</p><p class=\"mb-4\">Tempel dua baris log plus stack ke AI. Jangan minta AI menonaktifkan seluruh Console.</p><p class=\"mb-4\">Clincoo di blog.clincoo.buzz memakai log hemat; halaman Anda harus sama hematnya.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Do Not console.log inside Clincoo Hot Loops", "desc": "Logs inside requestAnimationFrame or scroll listeners stall the Console and hide the real error.", "content": "<p class=\"mb-4\">On editor.clincoo.buzz, logs in a render or scroll loop flood the Console until the important error is pushed away.</p><p class=\"mb-4\">Move logs to a rare branch: after a user action, or behind a debug flag that is off in production on app.clincoo.buzz.</p><p class=\"mb-4\">If you must watch a loop, log every N frames or only when a value changes. Do not log a whole DOM node.</p><p class=\"mb-4\">Paste two log lines plus the stack to AI. Do not ask AI to disable the entire Console.</p><p class=\"mb-4\">Clincoo on blog.clincoo.buzz uses sparse logs; your pages should be just as sparse.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["logging"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["logging"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
