// Clincoo Blog pagination extra 2026-09-30
(function(){
  var extra = [
    {id:'pagination-offset-vs-cursor',langs:{id:{title:'Pilih Offset atau Cursor untuk Daftar Proyek Clincoo',desc:'Offset mudah tapi meloncat saat data baru masuk. Cursor lebih stabil untuk daftar yang sering berubah.',content:'<p class=\"mb-4\">Daftar proyek di app.clincoo.buzz bergeser jika page=2 memakai offset sementara draf baru disisip di atas.</p><p class=\"mb-4\">Pakai offset hanya untuk arsip yang jarang berubah. Untuk feed editor.clincoo.buzz, simpan id cursor item terakhir.</p><p class=\"mb-4\">Jangan campur dua mode di satu endpoint. Tempel query API ke AI dan minta satu skema.</p><p class=\"mb-4\">Uji: tambah item baru lalu pindah halaman. Urutan tidak boleh loncat. Catat di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Pick Offset or Cursor for a Clincoo Project List',desc:'Offset is easy but jumps when new rows arrive. A cursor stays stable on a changing list.',content:'<p class=\"mb-4\">A project list on app.clincoo.buzz shifts if page=2 uses offset while a new draft is inserted on top.</p><p class=\"mb-4\">Use offset only for rarely changed archives. For the editor.clincoo.buzz feed, store the last item id as a cursor.</p><p class=\"mb-4\">Do not mix both modes on one endpoint. Paste the API query to AI and ask for one schema.</p><p class=\"mb-4\">Test: add a new item then change page. Order must not jump. Note it on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'pagination-jaga-scroll-saat-ganti-halaman',langs:{id:{title:'Jaga Posisi Scroll Clincoo saat Ganti Halaman Daftar',desc:'Klik halaman 2 yang meloncat ke footer membuat pengguna kehilangan konteks kartu.',content:'<p class=\"mb-4\">Di editor.clincoo.buzz, ganti halaman daftar mengirim viewport ke bawah karena fokus pindah ke tautan halaman.</p><p class=\"mb-4\">Setelah fetch sukses, scroll ke judul daftar atau ke region hasil. Jangan biarkan window.scrollY liar.</p><p class=\"mb-4\">Tempel handler klik pager ke AI. Minta restore scroll, bukan infinite scroll baru.</p><p class=\"mb-4\">Uji di app.clincoo.buzz pada layar pendek. Tulis hasil di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Keep Clincoo Scroll Position when Changing List Pages',desc:'A page-2 click that jumps to the footer makes users lose card context.',content:'<p class=\"mb-4\">On editor.clincoo.buzz, changing the list page sends the viewport down because focus moved to the pager link.</p><p class=\"mb-4\">After a successful fetch, scroll to the list heading or the results region. Do not leave window.scrollY wild.</p><p class=\"mb-4\">Paste the pager click handler to AI. Ask to restore scroll, not a new infinite scroll.</p><p class=\"mb-4\">Test on app.clincoo.buzz on a short screen. Write the result on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'pagination-tombol-lebih-banyak-bukan-hanya-angka',langs:{id:{title:'Sediakan Muat Lebih Banyak selain Nomor Halaman Clincoo',desc:'Pager angka saja sulit di layar sempit. Tombol muat lebih banyak tetap jelas di HP.',content:'<p class=\"mb-4\">Nomor 1–12 di editor.clincoo.buzz pecah di lebar 360px. Pengunjung tidak tahu cara lanjut.</p><p class=\"mb-4\">Tambah tombol Muat lebih banyak yang memakai cursor yang sama. Tetap sediakan pager untuk arsip desktop.</p><p class=\"mb-4\">Jangan dobel-fetch jika tombol diklik dua kali. Disable selama request.</p><p class=\"mb-4\">Minta AI dua kontrol pada satu API. Uji di app.clincoo.buzz lalu catat di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Offer Load More besides Clincoo Page Numbers',desc:'Number-only pagers break on a narrow screen. A load-more button stays clear on a phone.',content:'<p class=\"mb-4\">Numbers 1–12 on editor.clincoo.buzz wrap at 360px. Visitors cannot tell how to continue.</p><p class=\"mb-4\">Add a Load more button that uses the same cursor. Keep a pager for desktop archives.</p><p class=\"mb-4\">Do not double-fetch on a double click. Disable the button during the request.</p><p class=\"mb-4\">Ask AI for two controls on one API. Test on app.clincoo.buzz and note it on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'pagination-aria-current-halaman-aktif',langs:{id:{title:'Tandai Halaman Aktif Clincoo dengan aria-current',desc:'Pager tanpa aria-current membuat pembaca layar menghitung tautan tanpa tahu posisi.',content:'<p class=\"mb-4\">Di editor.clincoo.buzz, halaman 3 terlihat tebal secara visual tapi tidak diumumkan ke pembaca layar.</p><p class=\"mb-4\">Set aria-current=\"page\" pada tautan aktif. Sisanya jangan current. Bungkus pager dengan nav dan label.</p><p class=\"mb-4\">Tempel markup pager ke AI. Minta atribut ARIA, bukan desain baru.</p><p class=\"mb-4\">Uji Tab plus pembaca layar di app.clincoo.buzz. Tulis checklist di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Mark the Active Clincoo Page with aria-current',desc:'A pager without aria-current makes a screen reader count links with no position.',content:'<p class=\"mb-4\">On editor.clincoo.buzz, page 3 looks bold visually but is not announced to a screen reader.</p><p class=\"mb-4\">Set aria-current=\"page\" on the active link. Leave the others unset. Wrap the pager in a labeled nav.</p><p class=\"mb-4\">Paste the pager markup to AI. Ask for ARIA attributes, not a new design.</p><p class=\"mb-4\">Test Tab plus a screen reader on app.clincoo.buzz. Write the checklist on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'pagination-ukuran-halaman-konsisten',langs:{id:{title:'Samakan Ukuran Halaman Daftar Clincoo di Semua Filter',desc:'Limit 10 di Semua lalu 50 di Arsip merusak ekspektasi dan membingungkan URL.',content:'<p class=\"mb-4\">Filter di editor.clincoo.buzz mengganti page size diam-diam. Pengunjung pikir data hilang.</p><p class=\"mb-4\">Tetapkan satu default, misalnya 12. Jika pengguna mengubah ukuran, simpan di query URL.</p><p class=\"mb-4\">Jangan reset ke halaman 1 tanpa alasan saat hanya urutan yang berubah. Reset saat filter isi berubah.</p><p class=\"mb-4\">Tempel parser query ke AI. Uji di app.clincoo.buzz dan tautkan aturan di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Keep Clincoo List Page Size Consistent across Filters',desc:'A limit of 10 on All then 50 on Archive breaks expectations and confuses the URL.',content:'<p class=\"mb-4\">A filter on editor.clincoo.buzz silently changes page size. Visitors think data vanished.</p><p class=\"mb-4\">Pick one default, for example 12. If the user changes size, store it in the URL query.</p><p class=\"mb-4\">Do not reset to page 1 for a sort-only change. Reset when the filter values change.</p><p class=\"mb-4\">Paste the query parser to AI. Test on app.clincoo.buzz and link the rule on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['pagination']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['pagination'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
