// Clincoo Blog featureflag extra2 2026-09-30
(function(){
  var extra = [
    {id:'featureflag-cantumkan-pemilik-dan-review',langs:{id:{title:'Cantumkan Pemilik dan Jadwal Review Feature Flag Clincoo',desc:'Flag tanpa pemilik tidak pernah dihapus. Tulis nama penanggung jawab dan tanggal review berikutnya.',content:'<p class=\"mb-4\">Di editor.clincoo.buzz, flag yatim menumpuk karena tidak ada orang yang berani menghapusnya.</p><p class=\"mb-4\">Tambahkan dua kolom di daftar flag: pemilik dan tanggal review. Tanpa keduanya, flag tidak boleh masuk produksi app.clincoo.buzz.</p><p class=\"mb-4\">Review artinya memutuskan: tetap, naikan rollout, atau hapus cabang mati. Bukan sekadar centang dokumen.</p><p class=\"mb-4\">Tempel daftar flag ke AI dan minta tabel pemilik yang kosong. Jangan minta AI mengisi nama acak.</p><p class=\"mb-4\">Umumkan pemilik baru di blog.clincoo.buzz agar rekan tahu siapa yang dihubungi saat flag pecah.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Assign an Owner and a Review Date to Every Clincoo Feature Flag',desc:'A flag without an owner is never deleted. Write the owner name and the next review date.',content:'<p class=\"mb-4\">On editor.clincoo.buzz, orphan flags pile up because nobody feels allowed to delete them.</p><p class=\"mb-4\">Add two columns to the flag list: owner and review date. Without both, the flag must not ship to production on app.clincoo.buzz.</p><p class=\"mb-4\">Review means decide: keep, raise the rollout, or delete the dead branch. It is not a checkbox on a doc.</p><p class=\"mb-4\">Paste the flag list to AI and ask which owners are missing. Do not ask AI to invent names.</p><p class=\"mb-4\">Announce the new owner on blog.clincoo.buzz so teammates know whom to ping when the flag breaks.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'featureflag-jangan-andalkan-css-saja',langs:{id:{title:'Jangan Andalkan Kelas CSS Saja sebagai Feature Flag Clincoo',desc:'Menyembunyikan tombol dengan display none bukan flag. Logika fetch dan hak akses tetap berjalan di belakang layar.',content:'<p class=\"mb-4\">Kelas .is-hidden di editor.clincoo.buzz hanya menyembunyikan UI. Permintaan jaringan tetap terkirim.</p><p class=\"mb-4\">Guard fitur di JavaScript sebelum fetch, bukan hanya di stylesheet. Pengguna bisa membuka DevTools dan menampilkan tombol.</p><p class=\"mb-4\">Jika flag off, jangan muat skrip fitur. Hemat bundle dan tutup jalur yang tidak diuji.</p><p class=\"mb-4\">Tempel CSS plus handler klik ke AI. Minta pastikan cabang off tidak memanggil API. Jangan minta rewrite tema.</p><p class=\"mb-4\">Uji dengan flag off di app.clincoo.buzz sambil membuka tab Network. Nol permintaan rahasia adalah lulus.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Do Not Treat a CSS Class as a Clincoo Feature Flag',desc:'Hiding a button with display none is not a flag. Fetch logic and access checks still run in the background.',content:'<p class=\"mb-4\">An .is-hidden class on editor.clincoo.buzz only hides UI. The network request still fires.</p><p class=\"mb-4\">Guard the feature in JavaScript before fetch, not only in the stylesheet. A user can open DevTools and show the button.</p><p class=\"mb-4\">If the flag is off, do not load the feature script. You save bundle size and close an untested path.</p><p class=\"mb-4\">Paste the CSS plus the click handler to AI. Ask it to confirm the off branch never calls the API. Do not request a theme rewrite.</p><p class=\"mb-4\">Test with the flag off on app.clincoo.buzz while Network is open. Zero secret requests is a pass.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'featureflag-kill-switch-terpisah',langs:{id:{title:'Pisahkan Kill Switch Clincoo dari Flag Rollout',desc:'Flag persentase tidak cukup saat insiden. Sediakan sakelar mati darurat yang mengabaikan bucket.',content:'<p class=\"mb-4\">Rollout 5 persen di editor.clincoo.buzz tetap merusak sebagian pengguna jika bug parah. Anda butuh tombol mati instan.</p><p class=\"mb-4\">Kill switch harus default aman, tanpa deploy ulang, dan terdokumentasi siapa yang boleh membaliknya.</p><p class=\"mb-4\">Jangan gabungkan kill switch dengan eksperimen UI. Satu sakelar, satu keputusan: hidup atau mati.</p><p class=\"mb-4\">Minta AI meninjau urutan cek: kill switch dulu, baru persentase. Jangan minta menggabungkan kedua peta.</p><p class=\"mb-4\">Latih tim membalik sakelar di app.clincoo.buzz pada latihan insiden, lalu catat langkahnya di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Keep the Clincoo Kill Switch Separate from the Rollout Flag',desc:'A percentage flag is not enough during an incident. Provide an emergency off switch that ignores buckets.',content:'<p class=\"mb-4\">A 5 percent rollout on editor.clincoo.buzz still hurts some users if the bug is severe. You need an instant off switch.</p><p class=\"mb-4\">The kill switch must fail safe, require no redeploy, and document who may flip it.</p><p class=\"mb-4\">Do not merge the kill switch with a UI experiment. One switch, one decision: on or off.</p><p class=\"mb-4\">Ask AI to review the check order: kill switch first, then percentage. Do not ask it to merge both maps.</p><p class=\"mb-4\">Drill flipping the switch on app.clincoo.buzz during an incident exercise, then record the steps on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}},
    {id:'featureflag-catat-di-catatan-rilis',langs:{id:{title:'Catat Feature Flag Clincoo di Catatan Rilis',desc:'Rilis tanpa daftar flag membuat rollback buta. Tulis nama flag, default, dan persentase di setiap catatan.',content:'<p class=\"mb-4\">Saat halaman pecah di app.clincoo.buzz, tim bertanya flag mana yang berubah. Catatan rilis harus menjawab dalam satu menit.</p><p class=\"mb-4\">Cantumkan nama flag, nilai default, persentase, dan tautan uji on/off di editor.clincoo.buzz.</p><p class=\"mb-4\">Jangan mengubur flag di commit message panjang. Satu daftar di catatan rilis dibaca orang on-call.</p><p class=\"mb-4\">Tempel draf catatan ke AI dan minta kelengkapan tiga kolom saja. Jangan minta prosa pemasaran.</p><p class=\"mb-4\">Arsipkan catatan di blog.clincoo.buzz agar riwayat flag bisa diaudit tanpa membuka Git.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Record Clincoo Feature Flags in the Release Note',desc:'A release without a flag list makes rollback blind. Write the flag name, default, and percent in every note.',content:'<p class=\"mb-4\">When a page breaks on app.clincoo.buzz, the team asks which flag changed. The release note must answer in one minute.</p><p class=\"mb-4\">List the flag name, default value, percent, and an on/off test link on editor.clincoo.buzz.</p><p class=\"mb-4\">Do not bury flags in a long commit message. On-call reads one list in the release note.</p><p class=\"mb-4\">Paste the draft note to AI and ask only whether three columns are complete. Do not request marketing copy.</p><p class=\"mb-4\">Archive the note on blog.clincoo.buzz so flag history can be audited without opening Git.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['featureflag']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['featureflag'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
