// Clincoo Blog — artikel cors tambahan 2026-10-01
(function(){
  var extra = [
    {"id": "cors-localhost-vs-127-bukan-sama", "langs": {"id": {"title": "Bedakan localhost dan 127.0.0.1 saat Uji CORS Clincoo", "desc": "Browser menganggap localhost dan 127.0.0.1 origin berbeda. Daftar keduanya atau pilih satu.", "content": "<p class=\"mb-4\">Pratinjau editor.clincoo.buzz dari http://localhost:5173 lolos, lalu gagal saat Anda buka http://127.0.0.1:5173. Itu dua origin.</p><p class=\"mb-4\">Samakan URL uji. Tambah kedua origin ke Allow-Origin hanya jika Anda benar-benar memakai keduanya.</p><p class=\"mb-4\">Jangan minta AI menulis middleware CORS besar sebelum Anda salin origin persis dari window.location.origin.</p><p class=\"mb-4\">Uji fetch ke API dari app.clincoo.buzz setelah origin lokal konsisten. Catat hasil di blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Treat localhost and 127.0.0.1 as Different Origins in Clincoo CORS Tests", "desc": "Browsers treat localhost and 127.0.0.1 as different origins. List both or pick one.", "content": "<p class=\"mb-4\">A preview of editor.clincoo.buzz from http://localhost:5173 may pass, then fail on http://127.0.0.1:5173. Those are two origins.</p><p class=\"mb-4\">Keep the test URL consistent. Add both origins to Allow-Origin only if you actually use both.</p><p class=\"mb-4\">Do not ask AI for a large CORS middleware before you copy the exact origin from window.location.origin.</p><p class=\"mb-4\">Test the API fetch from app.clincoo.buzz after the local origin is consistent. Record the result on blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}},
    {"id": "cors-jangan-matikan-browser-flag", "langs": {"id": {"title": "Jangan Matikan Flag Keamanan Browser untuk Lolos CORS Clincoo", "desc": "Menonaktifkan CORS di Chrome membuat bug tersembunyi. Perbaiki header server, bukan browser.", "content": "<p class=\"mb-4\">Flag --disable-web-security membuat fetch di editor.clincoo.buzz seolah sehat. Produksi app.clincoo.buzz tetap menolak.</p><p class=\"mb-4\">Baca header preflight di tab Network. Perbaiki Allow-Origin, Allow-Methods, dan Allow-Headers di server.</p><p class=\"mb-4\">Tempel pesan konsol lengkap ke AI. Jangan minta AI menonaktifkan keamanan browser.</p><p class=\"mb-4\">Dokumentasikan perbaikan di blog.clincoo.buzz agar rekan tidak mengulang flag berbahaya.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Do Not Disable Browser Security Flags to Bypass Clincoo CORS", "desc": "Turning CORS off in Chrome hides the bug. Fix server headers, not the browser.", "content": "<p class=\"mb-4\">The --disable-web-security flag makes fetch on editor.clincoo.buzz look healthy. Production app.clincoo.buzz still rejects it.</p><p class=\"mb-4\">Read preflight headers in the Network tab. Fix Allow-Origin, Allow-Methods, and Allow-Headers on the server.</p><p class=\"mb-4\">Paste the full console message to AI. Do not ask AI to disable browser security.</p><p class=\"mb-4\">Document the fix on blog.clincoo.buzz so teammates do not reuse a dangerous flag.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}},
    {"id": "cors-fetch-mode-cors-eksplisit", "langs": {"id": {"title": "Setel mode cors secara Eksplisit pada Fetch Clincoo", "desc": "mode no-cors menyembunyikan body dan status. Pakai mode cors jika Anda perlu membaca JSON.", "content": "<p class=\"mb-4\">Fetch ke API dari editor.clincoo.buzz dengan mode: 'no-cors' menghasilkan opaque response. JSON.parse gagal diam-diam.</p><p class=\"mb-4\">Pakai mode: 'cors' (default untuk URL lintas origin yang Anda kendalikan) lalu cek res.ok sebelum res.json().</p><p class=\"mb-4\">Jika preflight gagal, perbaiki header server. Jangan ganti ke no-cors hanya agar Promise resolve.</p><p class=\"mb-4\">Uji di app.clincoo.buzz dan tempel status plus header ke AI. Catat langkah di blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Set Fetch mode cors Explicitly for Clincoo Requests", "desc": "mode no-cors hides the body and status. Use mode cors when you need to read JSON.", "content": "<p class=\"mb-4\">A fetch to the API from editor.clincoo.buzz with mode: 'no-cors' yields an opaque response. JSON.parse fails quietly.</p><p class=\"mb-4\">Use mode: 'cors' (the default for cross-origin URLs you control) and check res.ok before res.json().</p><p class=\"mb-4\">If preflight fails, fix server headers. Do not switch to no-cors just so the Promise resolves.</p><p class=\"mb-4\">Test on app.clincoo.buzz and paste the status plus headers to AI. Record the steps on blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}},
    {"id": "cors-cookie-samesite-lintas-situs", "langs": {"id": {"title": "Samakan SameSite Cookie dengan Kredensial CORS Clincoo", "desc": "Cookie SameSite=Lax tidak terkirim pada fetch lintas situs. Sesuaikan SameSite dan CORS credentials.", "content": "<p class=\"mb-4\">Login di app.clincoo.buzz tidak mengirim cookie ke API lain jika SameSite=Lax dan fetch credentials: include.</p><p class=\"mb-4\">Untuk API lintas situs yang sah, set SameSite=None; Secure dan Access-Control-Allow-Credentials: true plus origin pasti.</p><p class=\"mb-4\">Jangan pakai wildcard origin bersama cookie. Browser menolak kombinasi itu.</p><p class=\"mb-4\">Tempel Set-Cookie dan header CORS ke AI. Uji di editor.clincoo.buzz lalu catat di blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Align Cookie SameSite with Clincoo CORS Credentials", "desc": "SameSite=Lax cookies are not sent on cross-site fetch. Match SameSite and CORS credentials.", "content": "<p class=\"mb-4\">A login on app.clincoo.buzz will not send the cookie to another API if SameSite=Lax and fetch uses credentials: include.</p><p class=\"mb-4\">For a legitimate cross-site API, set SameSite=None; Secure plus Access-Control-Allow-Credentials: true and a concrete origin.</p><p class=\"mb-4\">Do not use a wildcard origin with cookies. The browser rejects that pair.</p><p class=\"mb-4\">Paste Set-Cookie and CORS headers to AI. Test on editor.clincoo.buzz and record it on blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}},
    {"id": "cors-error-network-bukan-selalu-cors", "langs": {"id": {"title": "Jangan Asumsikan Setiap Network Error adalah CORS Clincoo", "desc": "failed to fetch juga muncul saat DNS, mixed content, atau server mati. Cek Network dulu.", "content": "<p class=\"mb-4\">Konsol editor.clincoo.buzz menulis TypeError: Failed to fetch. Itu bukan bukti CORS.</p><p class=\"mb-4\">Buka tab Network. Jika tidak ada respons sama sekali, cek URL, HTTPS, dan status server sebelum menyalahkan origin.</p><p class=\"mb-4\">Baris CORS di konsol menyebut Access-Control. Jika baris itu tidak ada, perbaiki koneksi dulu.</p><p class=\"mb-4\">Tempel status Network ke AI, bukan seluruh app.js. Ringkas temuan di blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo", "source2": "Clincoo App", "source3": "Clincoo Blog"}, "en": {"title": "Do Not Assume Every Clincoo Network Error Is CORS", "desc": "failed to fetch also appears for DNS, mixed content, or a down server. Check Network first.", "content": "<p class=\"mb-4\">The editor.clincoo.buzz console writes TypeError: Failed to fetch. That is not proof of CORS.</p><p class=\"mb-4\">Open the Network tab. If there is no response at all, check the URL, HTTPS, and server status before blaming origin.</p><p class=\"mb-4\">A CORS console line mentions Access-Control. If that line is missing, fix connectivity first.</p><p class=\"mb-4\">Paste the Network status to AI, not the whole app.js. Summarize findings on blog.clincoo.buzz.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor", "source2": "Clincoo App", "source3": "Clincoo Blog"}}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["cors"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["cors"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
