// Clincoo Blog — artikel redirect tambahan 2026-10-02
(function(){
  var extra = [{"id": "redirect-hindari-meta-refresh", "langs": {"id": {"title": "Hindari meta refresh, Pakai Pengalihan 301 di Clincoo", "desc": "meta refresh menunda pindah halaman dan sering dihitung sebagai soft redirect. Untuk URL lama, pakai status 301.", "content": "<p class=\"mb-4\">Halaman lama di proyek Clincoo kadang memakai meta http-equiv refresh. Pengunjung melihat halaman kosong sejenak, lalu baru pindah.</p><p class=\"mb-4\">Mesin telusur memperlakukan refresh sebagai isyarat lemah. Tautan eksternal tetap menumpuk di URL lama.</p><p class=\"mb-4\">Ganti dengan pengalihan HTTP 301 dari path lama ke slug baru. Satu hop saja. Jangan rantai 301 ke 302 lalu ke meta refresh.</p><p class=\"mb-4\">Uji di app.clincoo.buzz: buka URL lama, pastikan bilah alamat langsung menjadi URL baru, dan tombol kembali tidak mengulang putaran.</p><p class=\"mb-4\">Jika hosting hanya bisa halaman statis, minta AI menulis satu halaman perantara dengan tautan jelas, lalu catat bahwa ini sementara, bukan pengganti 301.</p>", "source": "Clincoo Editor", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Clincoo Editor", "source2": "Clincoo App", "source3": "MDN Web Docs"}, "en": {"title": "Avoid meta refresh, Use a 301 Redirect in Clincoo", "desc": "meta refresh delays the move and is often treated as a soft redirect. For an old URL, use a 301 status.", "content": "<p class=\"mb-4\">Old pages in a Clincoo project sometimes use a meta http-equiv refresh. Visitors see a blank page briefly, then move.</p><p class=\"mb-4\">Search engines treat a refresh as a weak signal. External links keep pointing at the old URL.</p><p class=\"mb-4\">Replace it with an HTTP 301 from the old path to the new slug. One hop only. Do not chain a 301 into a 302 and then a meta refresh.</p><p class=\"mb-4\">Test in app.clincoo.buzz: open the old URL, confirm the address bar becomes the new URL immediately, and Back does not loop.</p><p class=\"mb-4\">If the host can only serve static pages, ask AI to write one interim page with a clear link, and note that it is temporary, not a 301 replacement.</p>", "source": "Clincoo Editor", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Clincoo Editor", "source2": "Clincoo App", "source3": "MDN Web Docs"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["redirect"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["redirect"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
