// Clincoo Blog — artikel pwa tambahan 2026-10-02
(function(){
  var extra = [{"id": "pwa-orientation-any-agar-hp-tidak-terkunci", "langs": {"id": {"title": "Set orientation any agar PWA Clincoo Tidak Mengunci Layar HP", "desc": "Manifest yang memaksa portrait mengunci situs saat pengguna memutar HP. Untuk situs konten, biarkan any.", "content": "<p class=\"mb-4\">Manifest PWA di situs Clincoo kadang menyalin orientation: portrait dari contoh aplikasi game. Situs blog atau company profile lalu tidak bisa dibaca landscape.</p><p class=\"mb-4\">Untuk situs konten, pakai orientation: any atau hapus field itu. Browser mengikuti orientasi perangkat. Portrait-primary hanya masuk akal untuk alur yang memang dirancang satu arah.</p><p class=\"mb-4\">Uji setelah install di Chrome Android: buka dari ikon layar utama, putar HP, pastikan layout tidak terpotong. CSS tetap butuh media query, manifest tidak menggantikan responsive.</p><p class=\"mb-4\">Jangan ubah orientation setelah pengguna sudah memasang aplikasi tanpa menjelaskan. Perubahan manifest bisa butuh install ulang agar terlihat.</p>", "source": "MDN Web App Manifest orientation", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/Manifest/reference/orientation", "sourceSnippet": "orientation sets the default orientation for the web app.", "source2": "web.dev Add a web app manifest", "source3": "Clincoo App"}, "en": {"title": "Set orientation to any so a Clincoo PWA Does Not Lock the Phone Screen", "desc": "A manifest that forces portrait locks the site when the user rotates the phone. For a content site, leave it as any.", "content": "<p class=\"mb-4\">A Clincoo site PWA manifest sometimes copies orientation: portrait from a game sample. A blog or company profile then cannot be read in landscape.</p><p class=\"mb-4\">For a content site, use orientation: any or omit the field. The browser follows the device. portrait-primary only makes sense for a flow designed for one direction.</p><p class=\"mb-4\">Test after install on Chrome Android: open from the home-screen icon, rotate the phone, and confirm the layout is not clipped. CSS still needs media queries; the manifest does not replace responsive layout.</p><p class=\"mb-4\">Do not change orientation after users have installed the app without saying so. A manifest change may need a reinstall before it shows up.</p>", "source": "MDN Web App Manifest orientation", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/Manifest/reference/orientation", "sourceSnippet": "orientation sets the default orientation for the web app.", "source2": "web.dev Add a web app manifest", "source3": "Clincoo App"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["pwa"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["pwa"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
