// Clincoo Blog — artikel regex tambahan 2026-10-01 WIB
(function(){
  var extra = [{"id": "regex-flag-u-untuk-karakter-unicode", "langs": {"id": {"title": "Pakai Flag u saat Regex Clincoo Menyentuh Huruf Unicode", "desc": "Tanpa flag u, titik dan kelas karakter bisa membelah emoji atau huruf beraksen. Flag u membuat hitungan kode lebih aman.", "content": "<p class=\"mb-4\">Validasi nama di editor.clincoo.buzz kadang memakai /./ tanpa flag u. Emoji dan huruf Latin beraksen terhitung dua unit.</p><p class=\"mb-4\">Tambahkan flag u pada pola yang membatasi panjang atau mengganti karakter. Contoh: /^[\\p{L}\\p{N} .'-]+$/u untuk nama longgar.</p><p class=\"mb-4\">Tanpa u, \\p{L} tidak didukung di banyak mesin. Jangan tempel pola Unicode dari AI sebelum flag-nya ada.</p><p class=\"mb-4\">Uji string Indonesia yang memakai é, ñ, atau emoji di console. Bandingkan length dengan jumlah kode poin, bukan code unit.</p><p class=\"mb-4\">Simpan pola yang lolos di blog.clincoo.buzz. Tolak rewrite seluruh form jika yang rusak hanya satu regex.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode", "sourceSnippet": "MDN: RegExp unicode", "source2": "MDN: Unicode property escapes", "source3": "MDN: RegExp"}, "en": {"title": "Use the u Flag when a Clincoo Regex Touches Unicode", "desc": "Without the u flag, the dot and character classes can split emoji or accented letters. The u flag makes code-point matching safer.", "content": "<p class=\"mb-4\">Name validation on editor.clincoo.buzz sometimes uses /./ without the u flag. Emoji and accented Latin letters count as two units.</p><p class=\"mb-4\">Add the u flag on patterns that limit length or replace characters. Example: /^[\\p{L}\\p{N} .'-]+$/u for a loose name.</p><p class=\"mb-4\">Without u, \\p{L} is unsupported in many engines. Do not paste a Unicode pattern from AI until the flag is present.</p><p class=\"mb-4\">Test Indonesian strings with é, ñ, or emoji in the console. Compare length with code points, not code units.</p><p class=\"mb-4\">Save the pattern that passed on blog.clincoo.buzz. Reject a full form rewrite if only one regex is broken.</p>", "source": "MDN", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode", "sourceSnippet": "MDN: RegExp unicode", "source2": "MDN: Unicode property escapes", "source3": "MDN: RegExp"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["regex"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["regex"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
