// Clincoo Blog security extra 2026-10-01
(function(){
  var extra = [{"id": "security-csp-meta-dasar-tanpa-unsafe-inline", "langs": {"id": {"title": "Pasang CSP Dasar di Meta tanpa unsafe-inline di Clincoo", "desc": "Content-Security-Policy menahan skrip asing. Mulai ketat, longgarkan hanya domain yang benar-benar dipakai.", "content": "<p class=\"mb-4\">Halaman hasil editor.clincoo.buzz sering memuat satu skrip analitik plus embed. Tanpa CSP, browser menerima skrip dari domain mana pun yang berhasil tertempel di HTML.</p><p class=\"mb-4\">Tambah meta Content-Security-Policy di head: default-src self, script-src self, style-src self unsafe-inline dulu hanya jika CSS inline masih ada, img-src self data https. Hindari script-src unsafe-inline kecuali tidak ada jalan lain.</p><p class=\"mb-4\">Uji di Chrome DevTools tab Console. Pelanggaran CSP muncul sebagai error jelas. Salin pesan itu ke asisten AI di app.clincoo.buzz beserta cuplikan head.</p><p class=\"mb-4\">Kalau widget pihak ketiga putus, izinkan domain itu satu per satu — jangan kembali ke wildcard. Deploy ulang ke blog.clincoo.buzz setelah meta stabil.</p>", "source": "MDN Content-Security-Policy", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy", "sourceSnippet": "CSP helps mitigate XSS by declaring allowed sources."}, "en": {"title": "Add a Basic CSP Meta without unsafe-inline on Clincoo", "desc": "Content-Security-Policy holds back foreign scripts. Start strict, then allow only domains you actually use.", "content": "<p class=\"mb-4\">Pages from editor.clincoo.buzz often load one analytics script plus an embed. Without CSP the browser accepts a script from any domain that lands in the HTML.</p><p class=\"mb-4\">Add a Content-Security-Policy meta in the head: default-src self, script-src self, style-src self unsafe-inline only while inline CSS remains, img-src self data https. Avoid script-src unsafe-inline unless there is no other path.</p><p class=\"mb-4\">Test in the Chrome DevTools Console tab. CSP violations show as clear errors. Paste that message into the assistant on app.clincoo.buzz with the head snippet.</p><p class=\"mb-4\">If a third-party widget breaks, allow that domain one by one — do not go back to a wildcard. Redeploy to blog.clincoo.buzz after the meta is stable.</p>", "source": "MDN Content-Security-Policy", "sourceUrl": "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy", "sourceSnippet": "CSP helps mitigate XSS by declaring allowed sources."}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['security']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['security'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
