// Clincoo Blog — artikel navigasi tambahan 2026-10-02
(function(){
  var extra = [{"id": "navigasi-skip-link-ke-konten-utama", "langs": {"id": {"title": "Pasang Skip Link ke Konten Utama di Situs Clincoo", "desc": "Pengguna keyboard tidak perlu menekan Tab belasan kali melewati menu. Tautan lompat ke konten utama harus muncul saat fokus.", "content": "<p class=\"mb-4\">Menu panjang di editor.clincoo.buzz memaksa pengguna keyboard menekan Tab berulang sebelum sampai ke isi. Skip link memotong jalur itu.</p><p class=\"mb-4\">Letakkan tautan pertama di body menuju id konten utama, misalnya #isi. Sembunyikan secara visual, lalu tampilkan saat :focus dengan posisi tetap di atas halaman.</p><p class=\"mb-4\">Elemen tujuan wajib bisa difokuskan. Pada main, tambahkan tabindex=-1 agar fokus benar-benar pindah setelah tautan diklik, bukan hanya scroll.</p><p class=\"mb-4\">Uji di pratinjau app.clincoo.buzz: muat halaman, tekan Tab sekali, pastikan tautan terlihat, lalu Enter memindahkan fokus ke judul konten.</p><p class=\"mb-4\">Jika skip link tidak muncul, tempel CSS :focus ke AI dan minta satu perbaikan. Jangan minta merombak seluruh navbar.</p>", "source": "Clincoo Editor", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Clincoo Editor", "source2": "Clincoo App", "source3": "MDN Web Docs"}, "en": {"title": "Add a Skip Link to Main Content on a Clincoo Site", "desc": "Keyboard users should not tab through the whole menu. A skip link to main content must appear on focus.", "content": "<p class=\"mb-4\">A long menu in editor.clincoo.buzz forces keyboard users to tab many times before the content. A skip link cuts that path.</p><p class=\"mb-4\">Place the first link in the body pointing at the main content id, such as #isi. Hide it visually, then show it on :focus with a fixed position at the top.</p><p class=\"mb-4\">The target must be focusable. On main, add tabindex=-1 so focus actually moves after the click, not only the scroll position.</p><p class=\"mb-4\">Test in the app.clincoo.buzz preview: load the page, press Tab once, confirm the link is visible, then Enter moves focus to the content heading.</p><p class=\"mb-4\">If the skip link never appears, paste the :focus CSS into AI and ask for one fix. Do not ask it to rebuild the navbar.</p>", "source": "Clincoo Editor", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Clincoo Editor", "source2": "Clincoo App", "source3": "MDN Web Docs"}}}];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles["navigasi"]) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles["navigasi"].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
