// Clincoo Blog timeout extra 2026-10-01
(function(){
  var extra = [
    {"id": "timeout-abortsignal-any-gabung-sinyal", "langs": {"id": {"title": "Gabungkan Timeout dan Batal Pengguna Clincoo dengan AbortSignal.any", "desc": "Dua controller terpisah mudah lupa di-abort. Satu sinyal gabungan membatalkan fetch dari waktu atau dari tombol batal.", "content": "<p class=\"mb-4\">Fetch simpan Clincoo punya timer sendiri dan tombol batal sendiri. Salah satu jalan, listener yang lain masih hidup.</p><p class=\"mb-4\">Pakai AbortSignal.any jika browser mendukung, atau bungkus dua sinyal di editor.clincoo.buzz. Abort sekali untuk semua alasan.</p><p class=\"mb-4\">Tampilkan pesan berbeda: habis waktu versus dibatalkan pengguna. Jangan samakan keduanya sebagai error jaringan.</p><p class=\"mb-4\">Minta AI menulis wrapper fetch dengan satu signal. Tempel cuplikan AbortController, bukan seluruh app.</p><p class=\"mb-4\">Clincoo di app.clincoo.buzz berhenti menunggu ketika pengguna batal atau batas waktu tercapai.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Editor resmi Clincoo"}, "en": {"title": "Combine Clincoo Timeout and User Cancel with AbortSignal.any", "desc": "Two separate controllers are easy to forget to abort. One combined signal cancels fetch from time or from a cancel button.", "content": "<p class=\"mb-4\">A Clincoo save fetch has its own timer and its own cancel button. One path fires, the other listener stays alive.</p><p class=\"mb-4\">Use AbortSignal.any when the browser supports it, or wrap two signals in editor.clincoo.buzz. Abort once for every reason.</p><p class=\"mb-4\">Show different copy: timed out versus user canceled. Do not treat both as a network error.</p><p class=\"mb-4\">Ask AI to write a fetch wrapper with one signal. Paste the AbortController snippet, not the whole app.</p><p class=\"mb-4\">Clincoo on app.clincoo.buzz stops waiting when the user cancels or the time limit hits.</p>", "source": "Clincoo", "sourceUrl": "https://editor.clincoo.buzz/", "sourceSnippet": "Official Clincoo editor"}}},
    {id:'timeout-debounce-simpan-otomatis',langs:{id:{title:'Debounce Simpan Otomatis Clincoo agar Timer Tidak Menumpuk',desc:'Setiap ketikan yang mereset setTimeout tanpa clearTimeout menumpuk simpan. Satu timer debounce cukup.',content:'<p class="mb-4">Di editor.clincoo.buzz, autosave dipasang di input. Setiap huruf membuat timeout baru sementara yang lama masih hidup.</p><p class="mb-4">Simpan id timer di variabel modul. clearTimeout sebelum setTimeout baru. Jangan buat interval untuk autosave.</p><p class="mb-4">Kirim handler input ke AI, bukan seluruh editor. Minta satu pola debounce 600ms.</p><p class="mb-4">Uji di app.clincoo.buzz: ketik cepat, pastikan hanya satu request setelah berhenti. Catat di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Debounce Clincoo Autosave so Timers Do Not Stack',desc:'Every keystroke that resets setTimeout without clearTimeout stacks saves. One debounce timer is enough.',content:'<p class="mb-4">On editor.clincoo.buzz, autosave sits on input. Each letter creates a new timeout while the old one still lives.</p><p class="mb-4">Keep the timer id in a module variable. clearTimeout before a new setTimeout. Do not use an interval for autosave.</p><p class="mb-4">Send the input handler to AI, not the whole editor. Ask for one 600ms debounce pattern.</p><p class="mb-4">Test on app.clincoo.buzz: type quickly and confirm only one request after you stop. Note it on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}},
    {id:'timeout-idle-callback-bukan-blok-ui',langs:{id:{title:'Pakai requestIdleCallback untuk Kerja Berat Clincoo, Bukan Timeout 0',desc:'setTimeout(fn,0) tetap bisa membekukan klik. Idle callback menunggu frame sepi.',content:'<p class="mb-4">Di editor.clincoo.buzz, indeks pencarian dijalankan lewat setTimeout 0 setelah muat. Klik pertama terasa macet.</p><p class="mb-4">Pakai requestIdleCallback dengan timeout cadangan. Batasi kerja per idle. Jangan parse seluruh proyek di satu callback.</p><p class="mb-4">Tempel fungsi indeks ke AI. Minta pecah per potongan, bukan rewrite app.</p><p class="mb-4">Ukur Interaction to Next Paint di app.clincoo.buzz. Tulis pola idle di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Use requestIdleCallback for Heavy Clincoo Work, Not Timeout 0',desc:'setTimeout(fn,0) can still freeze the first click. An idle callback waits for a quiet frame.',content:'<p class="mb-4">On editor.clincoo.buzz, search indexing runs via setTimeout 0 after load. The first click feels stuck.</p><p class="mb-4">Use requestIdleCallback with a fallback timeout. Cap work per idle. Do not parse the whole project in one callback.</p><p class="mb-4">Paste the index function to AI. Ask to split it into chunks, not rewrite the app.</p><p class="mb-4">Measure Interaction to Next Paint on app.clincoo.buzz. Write the idle pattern on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}},
    {id:'timeout-jangan-andalkan-alert-tutup',langs:{id:{title:'Jangan Andalkan alert() sebagai Timeout Clincoo',desc:'alert membekukan thread dan menunda timer. Pakai UI non-blokir untuk peringatan habis waktu.',content:'<p class="mb-4">Beberapa template di editor.clincoo.buzz memanggil alert saat fetch habis waktu. Timer lain berhenti sampai dialog ditutup.</p><p class="mb-4">Ganti alert dengan banner atau toast. Biarkan event loop jalan agar batal dan retry tetap hidup.</p><p class="mb-4">Minta AI satu komponen peringatan timeout. Jangan minta polyfill alert.</p><p class="mb-4">Uji di app.clincoo.buzz dengan dua request bersamaan. Catat perilaku di blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Editor resmi Clincoo',source2:'Clincoo App',source3:'Clincoo Blog'},en:{title:'Do Not Rely on alert() as a Clincoo Timeout',desc:'alert freezes the thread and delays other timers. Use a non-blocking UI for a time-limit warning.',content:'<p class="mb-4">Some templates on editor.clincoo.buzz call alert when a fetch times out. Other timers pause until the dialog closes.</p><p class="mb-4">Replace alert with a banner or toast. Keep the event loop running so cancel and retry still work.</p><p class="mb-4">Ask AI for one timeout-warning component. Do not ask for an alert polyfill.</p><p class="mb-4">Test on app.clincoo.buzz with two parallel requests. Record the behavior on blog.clincoo.buzz.</p>',source:'Clincoo',sourceUrl:'https://editor.clincoo.buzz/',sourceSnippet:'Official Clincoo editor',source2:'Clincoo App',source3:'Clincoo Blog'}}
  ];
  function merge(){
    if (!window.countryDataFiles || !window.countryDataFiles['timeout']) { setTimeout(merge, 30); return; }
    var arr = window.countryDataFiles['timeout'].articles;
    var have = {};
    for (var i = 0; i < arr.length; i++) have[arr[i].id] = true;
    for (var j = 0; j < extra.length; j++) { if (!have[extra[j].id]) arr.push(extra[j]); }
  }
  merge();
})();
